-- =====================================================================
-- 005_assessment_nctb.sql
-- NCTB assessment engine: CQ/MCQ item bank, question papers, exams,
-- mark entry, answer-script media, grading scale, GPA computation.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- Item bank
--
-- A Creative Question (সৃজনশীল প্রশ্ন) is a stimulus (উদ্দীপক) plus four
-- parts scored 1/2/3/4 against Bloom levels:
--   ক (knowledge, 1)  খ (comprehension, 2)  গ (application, 3)  ঘ (higher-order, 4)
-- Modelled as a parent question_items row + four question_item_parts rows,
-- so a school can reuse a stimulus with different part sets.
-- ---------------------------------------------------------------------
CREATE TYPE question_type   AS ENUM ('cq','mcq','short','true_false','matching','practical');
CREATE TYPE bloom_level     AS ENUM ('knowledge','comprehension','application','higher_order');
CREATE TYPE item_source     AS ENUM ('manual','sikhok_ai','board_past_paper','imported');
CREATE TYPE difficulty_band AS ENUM ('easy','medium','hard');

CREATE TABLE question_items (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  subject_id      uuid NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  class_id        uuid NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  chapter_no      smallint,
  chapter_name_bn text,
  topic           text,

  type            question_type NOT NULL,
  language        text NOT NULL DEFAULT 'bn' CHECK (language IN ('bn','en')),

  -- CQ stimulus / MCQ stem
  stem_text       text NOT NULL,
  stem_media_key  text,                             -- diagram/figure in object storage
  difficulty      difficulty_band NOT NULL DEFAULT 'medium',
  total_marks     numeric(5,2) NOT NULL DEFAULT 10,

  source          item_source NOT NULL DEFAULT 'manual',
  source_ref      text,                             -- 'Dhaka Board 2024 Q7'
  ai_session_id   uuid,                             -- provenance if generated by SikhokAI
  reviewed_by     uuid REFERENCES users(id),
  reviewed_at     timestamptz,
  is_approved     boolean NOT NULL DEFAULT false,

  -- Reuse tracking so a teacher does not repeat last term's paper
  times_used      integer NOT NULL DEFAULT 0,
  last_used_at    timestamptz,

  -- Duplicate detection + answer-leak guard (see 008)
  content_hash    bytea NOT NULL,
  embedding       vector(1024),

  created_by      uuid REFERENCES users(id),
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  deleted_at      timestamptz
);
CREATE INDEX ix_items_pick ON question_items
  (tenant_id, subject_id, class_id, chapter_no, type, difficulty)
  WHERE is_approved AND deleted_at IS NULL;
CREATE UNIQUE INDEX uq_items_hash ON question_items (tenant_id, content_hash)
  WHERE deleted_at IS NULL;
CREATE TRIGGER trg_items_tenant BEFORE INSERT OR UPDATE ON question_items
  FOR EACH ROW EXECUTE FUNCTION app.enforce_tenant();

-- CQ parts ক/খ/গ/ঘ
CREATE TABLE question_item_parts (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id     uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  item_id       uuid NOT NULL REFERENCES question_items(id) ON DELETE CASCADE,
  part_label    char(1) NOT NULL CHECK (part_label IN ('ক','খ','গ','ঘ','a','b','c','d')),
  ordinal       smallint NOT NULL CHECK (ordinal BETWEEN 1 AND 4),
  bloom         bloom_level NOT NULL,
  prompt_text   text NOT NULL,
  marks         numeric(4,2) NOT NULL CHECK (marks > 0),
  model_answer  text,
  rubric        jsonb NOT NULL DEFAULT '[]'::jsonb,  -- [{criterion, marks, descriptor}]
  UNIQUE (tenant_id, item_id, ordinal)
);
CREATE TRIGGER trg_item_parts_tenant BEFORE INSERT OR UPDATE ON question_item_parts
  FOR EACH ROW EXECUTE FUNCTION app.enforce_tenant();

-- Standard NCTB CQ mark split, enforced at the application layer and
-- documented here so nobody has to rediscover it:
COMMENT ON TABLE question_item_parts IS
  'NCTB CQ default marks: ক=1 (knowledge), খ=2 (comprehension), গ=3 (application), ঘ=4 (higher-order). '
  'Total 10 per CQ. Papers typically require answering 7 of 11 CQs = 70 marks.';

-- MCQ options
CREATE TABLE question_item_options (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  item_id     uuid NOT NULL REFERENCES question_items(id) ON DELETE CASCADE,
  ordinal     smallint NOT NULL,
  label       char(1) NOT NULL CHECK (label IN ('ক','খ','গ','ঘ','a','b','c','d')),
  option_text text NOT NULL,
  is_correct  boolean NOT NULL DEFAULT false,
  explanation text,
  UNIQUE (tenant_id, item_id, ordinal)
);
-- Exactly one correct option per MCQ.
CREATE UNIQUE INDEX uq_mcq_single_correct ON question_item_options (tenant_id, item_id)
  WHERE is_correct;
CREATE TRIGGER trg_item_opts_tenant BEFORE INSERT OR UPDATE ON question_item_options
  FOR EACH ROW EXECUTE FUNCTION app.enforce_tenant();

-- ---------------------------------------------------------------------
-- Question papers — a selected, ordered, optionally per-student randomised
-- set of items. `randomisation_seed` + student id deterministically derives
-- each student's option order, so an answer key can be regenerated later
-- without storing N copies of the paper.
-- ---------------------------------------------------------------------
CREATE TABLE question_papers (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  title_bn          text NOT NULL,
  subject_id        uuid NOT NULL REFERENCES subjects(id),
  class_id          uuid NOT NULL REFERENCES classes(id),
  total_marks       numeric(6,2) NOT NULL,
  duration_minutes  smallint NOT NULL,
  cq_answer_count   smallint,                       -- 'answer any 7 of 11'
  cq_offered_count  smallint,
  mcq_count         smallint,
  randomise_mcq_order    boolean NOT NULL DEFAULT true,
  randomise_option_order boolean NOT NULL DEFAULT true,
  randomisation_seed     bigint NOT NULL DEFAULT (random() * 9e15)::bigint,
  instructions_bn   text,
  status            text NOT NULL DEFAULT 'draft'
                      CHECK (status IN ('draft','finalised','used','archived')),
  created_by        uuid REFERENCES users(id),
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_papers_tenant BEFORE INSERT OR UPDATE ON question_papers
  FOR EACH ROW EXECUTE FUNCTION app.enforce_tenant();

CREATE TABLE question_paper_items (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  paper_id     uuid NOT NULL REFERENCES question_papers(id) ON DELETE CASCADE,
  item_id      uuid NOT NULL REFERENCES question_items(id) ON DELETE RESTRICT,
  section_label text NOT NULL DEFAULT 'ক',           -- paper sections: CQ part / MCQ part
  ordinal      smallint NOT NULL,
  marks_override numeric(5,2),
  UNIQUE (tenant_id, paper_id, ordinal)
);
CREATE TRIGGER trg_paper_items_tenant BEFORE INSERT OR UPDATE ON question_paper_items
  FOR EACH ROW EXECUTE FUNCTION app.enforce_tenant();

-- ---------------------------------------------------------------------
-- Exams and mark entry
-- ---------------------------------------------------------------------
CREATE TYPE exam_status AS ENUM ('planned','ongoing','marking','moderation','published','locked');

CREATE TABLE exams (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  academic_year_id  uuid NOT NULL REFERENCES academic_years(id) ON DELETE CASCADE,
  term_id           uuid REFERENCES terms(id) ON DELETE SET NULL,
  name_bn           text NOT NULL,                  -- 'বার্ষিক পরীক্ষা ২০২৬'
  name_en           text NOT NULL,
  exam_type         text NOT NULL CHECK (exam_type IN
                      ('class_test','monthly','half_yearly','pre_test','test','annual','model','board')),
  weight_percent    numeric(5,2) NOT NULL DEFAULT 100,
  starts_on         date,
  ends_on           date,
  status            exam_status NOT NULL DEFAULT 'planned',
  is_gpa_bearing    boolean NOT NULL DEFAULT true,
  published_at      timestamptz,
  published_by      uuid REFERENCES users(id),
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_exams_year ON exams (tenant_id, academic_year_id, status);
CREATE TRIGGER trg_exams_tenant BEFORE INSERT OR UPDATE ON exams
  FOR EACH ROW EXECUTE FUNCTION app.enforce_tenant();

CREATE TABLE exam_subjects (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id        uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  exam_id          uuid NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
  section_id       uuid NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
  subject_id       uuid NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  paper_id         uuid REFERENCES question_papers(id) ON DELETE SET NULL,
  exam_date        date,
  start_time       time,
  duration_minutes smallint,
  room_id          uuid REFERENCES rooms(id),
  invigilator_id   uuid REFERENCES users(id),
  -- Component maxima (copied from class_subjects at creation, then frozen)
  cq_max           numeric(5,2) NOT NULL DEFAULT 70,
  mcq_max          numeric(5,2) NOT NULL DEFAULT 30,
  practical_max    numeric(5,2) NOT NULL DEFAULT 0,
  ca_max           numeric(5,2) NOT NULL DEFAULT 0,
  cq_pass          numeric(5,2) NOT NULL DEFAULT 23,
  mcq_pass         numeric(5,2) NOT NULL DEFAULT 10,
  marking_locked   boolean NOT NULL DEFAULT false,
  UNIQUE (tenant_id, exam_id, section_id, subject_id)
);
CREATE TRIGGER trg_examsubj_tenant BEFORE INSERT OR UPDATE ON exam_subjects
  FOR EACH ROW EXECUTE FUNCTION app.enforce_tenant();

-- Marks. Component-wise, because NCTB requires separate CQ/MCQ pass marks —
-- a student can total 45 and still fail on the CQ component alone.
CREATE TABLE exam_marks (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  exam_subject_id   uuid NOT NULL REFERENCES exam_subjects(id) ON DELETE CASCADE,
  student_id        uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  academic_year_id  uuid NOT NULL REFERENCES academic_years(id) ON DELETE CASCADE,

  cq_marks          numeric(5,2) CHECK (cq_marks >= 0),
  mcq_marks         numeric(5,2) CHECK (mcq_marks >= 0),
  practical_marks   numeric(5,2) CHECK (practical_marks >= 0),
  ca_marks          numeric(5,2) CHECK (ca_marks >= 0),
  total_marks       numeric(6,2) GENERATED ALWAYS AS
                      (COALESCE(cq_marks,0) + COALESCE(mcq_marks,0)
                       + COALESCE(practical_marks,0) + COALESCE(ca_marks,0)) STORED,

  is_absent         boolean NOT NULL DEFAULT false,
  is_expelled       boolean NOT NULL DEFAULT false,

  -- Computed at publish time by app.compute_subject_grade()
  grade_letter      varchar(2),
  grade_point       numeric(3,2),
  component_failed  boolean NOT NULL DEFAULT false,

  entered_by        uuid REFERENCES users(id),
  entered_at        timestamptz NOT NULL DEFAULT now(),
  op_id             uuid,                            -- offline provenance
  moderated_by      uuid REFERENCES users(id),
  moderated_at      timestamptz,
  row_version       integer NOT NULL DEFAULT 1,
  UNIQUE (tenant_id, exam_subject_id, student_id)
);
CREATE INDEX ix_marks_student ON exam_marks (tenant_id, student_id, academic_year_id);
CREATE INDEX ix_marks_entry   ON exam_marks (tenant_id, exam_subject_id) INCLUDE (student_id, total_marks);
CREATE TRIGGER trg_marks_tenant BEFORE INSERT OR UPDATE ON exam_marks
  FOR EACH ROW EXECUTE FUNCTION app.enforce_tenant();

-- Published marks are immutable; changes go through an approved correction.
CREATE TABLE mark_corrections (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  exam_mark_id    uuid NOT NULL REFERENCES exam_marks(id) ON DELETE CASCADE,
  field           text NOT NULL,
  old_value       numeric(6,2),
  new_value       numeric(6,2),
  reason          text NOT NULL,
  requested_by    uuid NOT NULL REFERENCES users(id),
  approved_by     uuid REFERENCES users(id),
  approved_at     timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_markcorr_tenant BEFORE INSERT OR UPDATE ON mark_corrections
  FOR EACH ROW EXECUTE FUNCTION app.enforce_tenant();

CREATE OR REPLACE FUNCTION app.block_published_mark_update() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE published boolean;
BEGIN
  SELECT e.status = 'published' INTO published
  FROM exam_subjects es JOIN exams e ON e.id = es.exam_id
  WHERE es.id = NEW.exam_subject_id;

  IF published AND NEW.moderated_by IS NULL THEN
    RAISE EXCEPTION 'published marks are immutable; file a mark_correction'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_marks_immutable BEFORE UPDATE OF cq_marks, mcq_marks, practical_marks, ca_marks
  ON exam_marks FOR EACH ROW EXECUTE FUNCTION app.block_published_mark_update();

-- ---------------------------------------------------------------------
-- Answer-script media — photos of handwritten scripts, compressed on-device.
-- ---------------------------------------------------------------------
CREATE TABLE answer_scripts (
  id               uuid PRIMARY KEY,                 -- client UUIDv7 = the outbox opId
  tenant_id        uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  exam_subject_id  uuid NOT NULL REFERENCES exam_subjects(id) ON DELETE CASCADE,
  student_id       uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  page_no          smallint NOT NULL DEFAULT 1,
  object_key       text NOT NULL,                    -- s3://scripts/{tenant}/{year}/{exam}/…
  content_type     text NOT NULL DEFAULT 'image/jpeg',
  byte_size        integer NOT NULL,
  sha256           bytea NOT NULL,
  original_bytes   integer,                          -- pre-compression, for telemetry
  captured_at      timestamptz NOT NULL,
  captured_by      uuid NOT NULL REFERENCES users(id),
  upload_state     text NOT NULL DEFAULT 'pending'
                     CHECK (upload_state IN ('pending','uploading','complete','failed')),
  uploaded_at      timestamptz,
  UNIQUE (tenant_id, exam_subject_id, student_id, page_no)
);
CREATE INDEX ix_scripts_pending ON answer_scripts (tenant_id, upload_state)
  WHERE upload_state <> 'complete';
CREATE TRIGGER trg_scripts_tenant BEFORE INSERT OR UPDATE ON answer_scripts
  FOR EACH ROW EXECUTE FUNCTION app.enforce_tenant();

-- ---------------------------------------------------------------------
-- Grading scale — per tenant, versioned, because boards revise it and a
-- 2025 transcript must keep its 2025 grades.
-- Default rows are the standard Bangladesh board scale.
-- ---------------------------------------------------------------------
CREATE TABLE grading_scales (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name         text NOT NULL,
  effective_from date NOT NULL,
  effective_to   date,
  is_default   boolean NOT NULL DEFAULT false,
  UNIQUE (tenant_id, name, effective_from)
);
CREATE TRIGGER trg_gscale_tenant BEFORE INSERT OR UPDATE ON grading_scales
  FOR EACH ROW EXECUTE FUNCTION app.enforce_tenant();

CREATE TABLE grading_bands (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id     uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  scale_id      uuid NOT NULL REFERENCES grading_scales(id) ON DELETE CASCADE,
  min_percent   numeric(5,2) NOT NULL,
  max_percent   numeric(5,2) NOT NULL,
  letter        varchar(2) NOT NULL,
  grade_point   numeric(3,2) NOT NULL,
  description_bn text,
  CHECK (max_percent >= min_percent),
  UNIQUE (tenant_id, scale_id, letter)
);
CREATE TRIGGER trg_gband_tenant BEFORE INSERT OR UPDATE ON grading_bands
  FOR EACH ROW EXECUTE FUNCTION app.enforce_tenant();

COMMENT ON TABLE grading_bands IS
  'Standard BD board scale seeded per tenant: '
  '80-100 A+ 5.00 | 70-79 A 4.00 | 60-69 A- 3.50 | 50-59 B 3.00 | '
  '40-49 C 2.00 | 33-39 D 1.00 | 0-32 F 0.00';

-- ---------------------------------------------------------------------
-- Result summary — one row per student per exam, the report-card source.
-- ---------------------------------------------------------------------
CREATE TABLE exam_results (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id          uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  exam_id            uuid NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
  student_id         uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  section_id         uuid NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
  academic_year_id   uuid NOT NULL REFERENCES academic_years(id) ON DELETE CASCADE,

  total_marks        numeric(8,2),
  total_max          numeric(8,2),
  percentage         numeric(5,2),
  gpa                numeric(3,2),                  -- capped at 5.00
  gpa_without_optional numeric(3,2),
  letter_grade       varchar(2),
  subjects_failed    smallint NOT NULL DEFAULT 0,
  is_pass            boolean NOT NULL DEFAULT false,

  rank_in_section    smallint,
  rank_in_class      smallint,
  attendance_percent numeric(5,2),

  computed_at        timestamptz NOT NULL DEFAULT now(),
  published_at       timestamptz,
  UNIQUE (tenant_id, exam_id, student_id)
);
CREATE INDEX ix_results_rank ON exam_results (tenant_id, exam_id, section_id, gpa DESC);
CREATE INDEX ix_results_student ON exam_results (tenant_id, student_id, academic_year_id);
CREATE TRIGGER trg_results_tenant BEFORE INSERT OR UPDATE ON exam_results
  FOR EACH ROW EXECUTE FUNCTION app.enforce_tenant();

-- ---------------------------------------------------------------------
-- Grade + GPA computation
--
-- Bangladesh board rules encoded here:
--   1. A subject grade is F if EITHER component (CQ or MCQ) is below its own
--      pass mark, regardless of the total. This is the rule most systems get wrong.
--   2. Any F in a compulsory subject ⇒ overall GPA 0.00 and result "Fail".
--   3. The optional (4th) subject contributes only (grade_point − 2), floored at 0,
--      and is excluded from the divisor.
--   4. Final GPA is capped at 5.00.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION app.compute_subject_grade(
  p_tenant       uuid,
  p_cq           numeric, p_cq_max numeric, p_cq_pass numeric,
  p_mcq          numeric, p_mcq_max numeric, p_mcq_pass numeric,
  p_practical    numeric, p_ca numeric,
  p_total_max    numeric,
  p_is_absent    boolean,
  p_scale_id     uuid
) RETURNS TABLE (letter varchar(2), grade_point numeric, component_failed boolean)
LANGUAGE plpgsql STABLE AS $$
DECLARE
  v_total   numeric;
  v_pct     numeric;
  v_failed  boolean := false;
BEGIN
  IF p_is_absent THEN
    RETURN QUERY SELECT 'F'::varchar(2), 0.00::numeric, true;
    RETURN;
  END IF;

  -- Rule 1: component-wise pass requirement
  IF (p_cq_max  > 0 AND COALESCE(p_cq, 0)  < p_cq_pass)
  OR (p_mcq_max > 0 AND COALESCE(p_mcq, 0) < p_mcq_pass) THEN
    v_failed := true;
  END IF;

  v_total := COALESCE(p_cq,0) + COALESCE(p_mcq,0) + COALESCE(p_practical,0) + COALESCE(p_ca,0);
  v_pct   := CASE WHEN p_total_max > 0 THEN (v_total / p_total_max) * 100 ELSE 0 END;

  IF v_failed THEN
    RETURN QUERY SELECT 'F'::varchar(2), 0.00::numeric, true;
    RETURN;
  END IF;

  RETURN QUERY
    SELECT gb.letter, gb.grade_point, false
    FROM grading_bands gb
    WHERE gb.tenant_id = p_tenant
      AND gb.scale_id  = p_scale_id
      AND v_pct >= gb.min_percent AND v_pct <= gb.max_percent
    LIMIT 1;
END $$;

CREATE OR REPLACE FUNCTION app.compute_exam_gpa(p_tenant uuid, p_exam uuid, p_student uuid)
RETURNS TABLE (gpa numeric, gpa_no_optional numeric, failed_count smallint, is_pass boolean)
LANGUAGE plpgsql STABLE AS $$
DECLARE
  v_sum_compulsory numeric := 0;
  v_count_compulsory integer := 0;
  v_optional_bonus numeric := 0;
  v_failed integer := 0;
  r RECORD;
BEGIN
  FOR r IN
    SELECT em.grade_point, em.component_failed, s.is_optional,
           (e.optional_subject_id = es.subject_id) AS is_students_optional
    FROM exam_marks em
    JOIN exam_subjects es ON es.id = em.exam_subject_id
    JOIN subjects s       ON s.id  = es.subject_id
    LEFT JOIN enrolments e ON e.student_id = em.student_id
                          AND e.academic_year_id = em.academic_year_id
    WHERE em.tenant_id = p_tenant
      AND em.student_id = p_student
      AND es.exam_id = p_exam
  LOOP
    IF COALESCE(r.is_students_optional, false) THEN
      -- Rule 3: only the excess over 2.00 counts, and it never subtracts.
      v_optional_bonus := v_optional_bonus + GREATEST(COALESCE(r.grade_point,0) - 2.00, 0);
    ELSE
      v_count_compulsory := v_count_compulsory + 1;
      v_sum_compulsory := v_sum_compulsory + COALESCE(r.grade_point, 0);
      IF COALESCE(r.grade_point, 0) = 0 THEN v_failed := v_failed + 1; END IF;
    END IF;
  END LOOP;

  IF v_count_compulsory = 0 THEN
    RETURN QUERY SELECT 0.00::numeric, 0.00::numeric, 0::smallint, false;
    RETURN;
  END IF;

  -- Rule 2: any compulsory F ⇒ 0.00
  IF v_failed > 0 THEN
    RETURN QUERY SELECT 0.00::numeric,
                        round(v_sum_compulsory / v_count_compulsory, 2),
                        v_failed::smallint, false;
    RETURN;
  END IF;

  RETURN QUERY SELECT
    LEAST(round((v_sum_compulsory + v_optional_bonus) / v_count_compulsory, 2), 5.00),  -- Rule 4
    round(v_sum_compulsory / v_count_compulsory, 2),
    0::smallint,
    true;
END $$;

COMMIT;
