// GENERATED by scripts/build.mjs from services/finance-svc/api/webhooks/[provider].ts — do not edit directly.

// packages/server-core/src/db.ts
import pg from "pg";
function createDb(connectionString, opts = {}) {
  const pool = new pg.Pool({
    connectionString,
    max: 10,
    idleTimeoutMillis: 3e4,
    statement_timeout: 15e3,
    ...opts
  });
  async function inTx(setup, fn) {
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      await setup(client);
      const out = await fn(client);
      await client.query("COMMIT");
      return out;
    } catch (err) {
      try {
        await client.query("ROLLBACK");
      } catch {
      }
      throw err;
    } finally {
      client.release();
    }
  }
  return {
    pool,
    withTenant(ctx, fn) {
      if (!ctx.tenantId) throw new Error("tenant context required");
      return inTx(async (c) => {
        await c.query(
          `SELECT set_config('app.tenant_id', $1, true),
                  set_config('app.user_id',   $2, true),
                  set_config('app.role',      $3, true)`,
          [ctx.tenantId, ctx.userId, ctx.role]
        );
      }, fn);
    },
    withSystemRole(role, fn) {
      return inTx(async (c) => {
        await c.query(`SELECT set_config('app.role', $1, true)`, [role]);
      }, fn);
    },
    end: () => pool.end()
  };
}
async function assertRlsEnforced(db) {
  const { rows } = await db.pool.query(
    `SELECT rolname, rolbypassrls, rolsuper FROM pg_roles WHERE rolname = current_user`
  );
  const me = rows[0];
  if (!me) throw new Error("cannot resolve current_user");
  if (me.rolbypassrls || me.rolsuper) {
    throw new Error(
      `refusing to start: connected as "${me.rolname}" which has ${me.rolsuper ? "SUPERUSER" : "BYPASSRLS"} \u2014 RLS would not be enforced. Connect as the non-privileged runtime role instead.`
    );
  }
}
var _db = null;
async function sharedDb() {
  if (_db) return _db;
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL env var is not set");
  const db = createDb(url, { max: 5 });
  await assertRlsEnforced(db);
  _db = db;
  return db;
}

// packages/server-core/src/http.ts
function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on("data", (c) => chunks.push(c));
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}
function json(res, code, body, cors) {
  const payload = JSON.stringify(body);
  res.writeHead(code, { ...cors, "Content-Type": "application/json" });
  res.end(payload);
}

// packages/server-core/src/rate-limit.ts
var perHour = (n) => n / 3600;
var RATE_LIMITS = {
  // Hammering one phone with OTPs is the attack; 3/hour per phone stops it
  // dead. The IP allowance has to clear a whole school activating at once.
  otp_request: { ip: { capacity: 240, refill: perHour(240) }, identity: { capacity: 3, refill: perHour(3) } },
  // Verification is a guessing attack against a 6-digit code. identity-svc
  // already caps attempts per challenge; this bounds the outer loop of
  // requesting a fresh challenge and guessing again.
  otp_verify: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 10, refill: perHour(10) } },
  // Refresh and logout — authenticated, cheap, but part of the auth surface.
  auth: { ip: { capacity: 600, refill: perHour(600) } },
  // The only endpoint class with real per-request cost. Per-identity is the
  // spend control until F-1310's proper token metering lands.
  ai: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 30, refill: perHour(30) } },
  // Ordinary authenticated traffic. Sized for a school, not a person: a
  // sync/push after a day offline is one request, not many.
  mutation: { ip: { capacity: 900, refill: 15 } },
  read: { ip: { capacity: 1800, refill: 30 } },
  // Machine-to-machine: MFS webhooks, cron workers, ANS dispatch. Already
  // gated by signature or service key; this is a backstop against a loop.
  service: { ip: { capacity: 3e3, refill: 50 } }
};
function clientIp(req) {
  const xff = req.headers["x-forwarded-for"];
  const first = Array.isArray(xff) ? xff[0] : xff;
  const ip = first?.split(",")[0]?.trim() || req.headers["x-real-ip"]?.trim() || req.socket?.remoteAddress || "unknown";
  return ip.slice(0, 64);
}
function buildBuckets(cls, ip, identity) {
  const policy = RATE_LIMITS[cls];
  const buckets = [];
  if (ip) {
    buckets.push({ key: `${cls}:ip:${ip}`, capacity: policy.ip.capacity, refill: policy.ip.refill });
  }
  if (policy.identity && identity) {
    buckets.push({
      key: `${cls}:id:${identity}`,
      capacity: policy.identity.capacity,
      refill: policy.identity.refill
    });
  }
  return buckets;
}
async function consumeRateLimit(cls, ip, identity) {
  const buckets = buildBuckets(cls, ip, identity);
  if (buckets.length === 0) return { allowed: true, retryAfterSec: 0 };
  try {
    const db = await sharedDb();
    const { rows } = await db.pool.query("SELECT * FROM app.rate_limit_consume($1::jsonb)", [JSON.stringify(buckets)]);
    const row = rows[0];
    if (!row) return { allowed: true, retryAfterSec: 0 };
    if (!row.allowed) {
      console.warn(`[rate-limit] refused ${cls}, bucket=${row.blocked_key}, retry=${row.retry_after_sec}s`);
    }
    return { allowed: row.allowed, retryAfterSec: row.retry_after_sec };
  } catch (err) {
    console.error("[rate-limit] check failed, allowing request:", err);
    return { allowed: true, retryAfterSec: 0 };
  }
}
async function enforceRateLimit(req, res, cors, cls, identity) {
  const verdict = await consumeRateLimit(cls, clientIp(req), identity);
  return sendIfRefused(res, cors, verdict);
}
function sendIfRefused(res, cors, verdict) {
  if (verdict.allowed) return true;
  json(
    res,
    429,
    {
      error: "rate_limited",
      message: "too many requests \u2014 please wait before trying again",
      retryAfterSec: verdict.retryAfterSec
    },
    { ...cors, "Retry-After": String(verdict.retryAfterSec) }
  );
  return false;
}

// packages/server-core/src/crypto.ts
import { randomBytes, randomInt, createHash, timingSafeEqual } from "node:crypto";
function sha256Hex(input) {
  return createHash("sha256").update(input, "utf8").digest("hex");
}

// services/finance-svc/src/webhook.ts
var PROVIDER_FIELD_MAPS = {
  bkash: {
    orderIdFields: ["merchantInvoiceNumber", "merchantInvoiceNo", "orderID"],
    gatewayPaymentIdFields: ["paymentID"],
    gatewayTrxIdFields: ["trxID"],
    msisdnFields: ["customerMsisdn", "payerAccount"],
    amountFields: ["amount"],
    statusFields: ["transactionStatus", "status"],
    eventIdFields: ["trxID", "paymentID"]
  },
  nagad: {
    orderIdFields: ["merchantOrderId", "orderId"],
    gatewayPaymentIdFields: ["paymentRefId"],
    gatewayTrxIdFields: ["issuerPaymentRefNo", "paymentRefId"],
    msisdnFields: ["clientMobileNo", "customerMsisdn"],
    amountFields: ["amount"],
    statusFields: ["status"],
    eventIdFields: ["paymentRefId", "issuerPaymentRefNo"]
  },
  rocket: {
    orderIdFields: ["merchantOrderId", "orderId"],
    gatewayPaymentIdFields: ["paymentId"],
    gatewayTrxIdFields: ["transactionId", "trxId"],
    msisdnFields: ["msisdn", "customerMsisdn"],
    amountFields: ["amount"],
    statusFields: ["status"],
    eventIdFields: ["transactionId", "trxId"]
  }
};
var UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function mapStatus(raw) {
  const s = (raw ?? "").toLowerCase();
  if (["completed", "success", "successful", "paid"].includes(s)) return "completed";
  if (["failed", "failure", "error"].includes(s)) return "failed";
  if (["cancelled", "canceled"].includes(s)) return "cancelled";
  if (["authorised", "authorized"].includes(s)) return "authorised";
  if (["reversed"].includes(s)) return "reversed";
  if (["refunded"].includes(s)) return "refunded";
  return "pending";
}
function firstString(payload, fields) {
  for (const f of fields) {
    const v = payload[f];
    if (typeof v === "string" && v) return v;
    if (typeof v === "number") return String(v);
  }
  return void 0;
}
function parseOrderId(orderId) {
  const [tenantId, invoiceId] = orderId.split(".");
  if (!tenantId || !invoiceId || !UUID_RE.test(tenantId) || !UUID_RE.test(invoiceId)) return null;
  return { tenantId, invoiceId };
}
var MfsWebhookProcessor = class {
  // Longhand, not a constructor parameter property: `node --test` strips
  // types rather than compiling them, and parameter properties are the one
  // TS-only construct it cannot strip — the failure is a runtime
  // SyntaxError, not a type error. Same reason as HttpError in
  // packages/server-core/src/http.ts.
  db;
  constructor(db) {
    this.db = db;
  }
  async process(provider, rawBody, headers, sourceIp) {
    let payload = {};
    try {
      const parsed = JSON.parse(rawBody);
      if (parsed && typeof parsed === "object") payload = parsed;
    } catch {
    }
    const map = PROVIDER_FIELD_MAPS[provider];
    const providerEventId = firstString(payload, map.eventIdFields) ?? sha256Hex(rawBody);
    const rawStatus = firstString(payload, map.statusFields);
    const webhookRow = await this.db.withSystemRole("system_ingest", async (client) => {
      const { rows } = await client.query(
        `INSERT INTO mfs_webhook_events
           (tenant_id, provider, event_type, provider_event_id, raw_body, headers, source_ip, processing_state)
         VALUES (NULL, $1, $2, $3, $4, $5::jsonb, $6, 'received')
         ON CONFLICT (provider, provider_event_id)
         DO UPDATE SET attempts = mfs_webhook_events.attempts + 1
         RETURNING id, processing_state`,
        [provider, rawStatus ?? null, providerEventId, rawBody, JSON.stringify(headers), sourceIp]
      );
      return rows[0];
    });
    if (webhookRow.processing_state === "processed" || webhookRow.processing_state === "duplicate") {
      return { status: 200, body: { ok: true, note: "already processed" } };
    }
    const orderId = firstString(payload, map.orderIdFields);
    const parsedOrderId = orderId ? parseOrderId(orderId) : null;
    if (!parsedOrderId) {
      await this.db.withSystemRole(
        "system_ingest",
        (client) => client.query(
          `UPDATE mfs_webhook_events SET processing_state = 'deferred', reject_reason = $2
            WHERE id = $1 AND tenant_id IS NULL`,
          [
            webhookRow.id,
            orderId ? "order id does not match the tenantId.invoiceId.suffix convention" : "no recognizable order id field in payload"
          ]
        )
      );
      return { status: 200, body: { ok: true, note: "deferred: could not resolve tenant from order id" } };
    }
    const { tenantId, invoiceId } = parsedOrderId;
    const status = mapStatus(rawStatus);
    const amountRaw = firstString(payload, map.amountFields);
    const amount = amountRaw ? Number(amountRaw) : null;
    const gatewayPaymentId = firstString(payload, map.gatewayPaymentIdFields) ?? null;
    const gatewayTrxId = firstString(payload, map.gatewayTrxIdFields) ?? null;
    const msisdn = firstString(payload, map.msisdnFields) ?? null;
    const ctx = { tenantId, userId: "", role: "accountant" };
    const result = await this.db.withTenant(ctx, async (client) => {
      const invoiceRes = await client.query(
        `SELECT id, student_id FROM invoices WHERE id = $1`,
        [invoiceId]
      );
      const invoice = invoiceRes.rows[0];
      if (!invoice) {
        await client.query(
          `UPDATE mfs_webhook_events
              SET tenant_id = $2, processing_state = 'rejected', reject_reason = $3
            WHERE id = $1 AND tenant_id IS NULL`,
          [webhookRow.id, tenantId, "invoice not found in resolved tenant"]
        );
        return { outcome: "rejected", reason: "invoice not found in resolved tenant" };
      }
      if (amount === null || !Number.isFinite(amount) || amount <= 0) {
        await client.query(
          `UPDATE mfs_webhook_events
              SET tenant_id = $2, processing_state = 'rejected', reject_reason = $3
            WHERE id = $1 AND tenant_id IS NULL`,
          [webhookRow.id, tenantId, "missing or non-positive amount in payload"]
        );
        return { outcome: "rejected", reason: "missing or non-positive amount in payload" };
      }
      const existing = await client.query(
        `SELECT id, status FROM mfs_transactions WHERE tenant_id = $1 AND merchant_order_id = $2`,
        [tenantId, orderId]
      );
      let txId;
      const alreadyCompleted = existing.rows[0]?.status === "completed";
      if (existing.rows[0]) {
        txId = existing.rows[0].id;
        await client.query(
          `UPDATE mfs_transactions
              SET status = $2,
                  gateway_payment_id = COALESCE($3, gateway_payment_id),
                  gateway_trx_id = COALESCE($4, gateway_trx_id),
                  payer_msisdn = COALESCE($5, payer_msisdn),
                  response_payload = $6::jsonb,
                  completed_at = CASE WHEN $2 = 'completed' AND completed_at IS NULL THEN now() ELSE completed_at END
            WHERE id = $1`,
          [txId, status, gatewayPaymentId, gatewayTrxId, msisdn, JSON.stringify(payload)]
        );
      } else {
        const inserted = await client.query(
          `INSERT INTO mfs_transactions
             (tenant_id, invoice_id, student_id, provider, merchant_order_id, gateway_payment_id, gateway_trx_id,
              payer_msisdn, amount, status, response_payload, idempotency_key, completed_at)
           VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11::jsonb, $12,
                   CASE WHEN $10 = 'completed' THEN now() ELSE NULL END)
           ON CONFLICT (tenant_id, merchant_order_id) DO UPDATE SET status = EXCLUDED.status
           RETURNING id`,
          [
            tenantId,
            invoiceId,
            invoice.student_id,
            provider,
            orderId,
            gatewayPaymentId,
            gatewayTrxId,
            msisdn,
            amount,
            status,
            JSON.stringify(payload),
            providerEventId
          ]
        );
        txId = inserted.rows[0].id;
      }
      let invoiceStatus = null;
      let receiptNo = null;
      let ledgerBatchId = null;
      if (status === "completed" && !alreadyCompleted) {
        const applied = await client.query(
          `SELECT app.apply_payment_to_invoice($1, $2, $3) AS status`,
          [tenantId, invoiceId, amount]
        );
        invoiceStatus = applied.rows[0]?.status ?? null;
        const receiptInsert = await client.query(
          `INSERT INTO payment_receipts
             (tenant_id, receipt_no, mfs_transaction_id, invoice_id, student_id,
              amount, method)
           VALUES (
             app.current_tenant(),
             'RCP-' || to_char(now(), 'YYYY-MM') || '-' ||
               lpad(
                 (1 + COALESCE((
                   SELECT max(substring(receipt_no from '\\d+$')::int)
                     FROM payment_receipts
                    WHERE receipt_no LIKE 'RCP-' || to_char(now(), 'YYYY-MM') || '-%'
                 ), 0))::text,
                 5, '0'
               ),
             $1, $2, $3, $4, $5)
           ON CONFLICT (tenant_id, receipt_no) DO NOTHING
           RETURNING receipt_no`,
          [txId, invoiceId, invoice.student_id, amount, provider]
        );
        receiptNo = receiptInsert.rows[0]?.receipt_no ?? null;
        const bankCode = provider === "bkash" ? "MFS-BKASH" : provider === "nagad" ? "MFS-NAGAD" : provider === "rocket" ? "MFS-ROCKET" : "CASH";
        const accounts = await client.query(
          `SELECT code, id FROM ledger_accounts
            WHERE code IN ($1, 'FEE-INCOME')`,
          [bankCode]
        );
        const bankAcct = accounts.rows.find((r) => r.code === bankCode)?.id;
        const incomeAcct = accounts.rows.find((r) => r.code === "FEE-INCOME")?.id;
        if (bankAcct && incomeAcct) {
          const batch = await client.query(
            `INSERT INTO ledger_entries
               (tenant_id, batch_id, account_id, entry_date, debit, credit,
                reference_type, reference_id, memo)
             VALUES
               (app.current_tenant(), gen_random_uuid(), $1, CURRENT_DATE,
                $3, 0, 'mfs_transaction', $2, 'MFS payment received')
             RETURNING batch_id AS id`,
            [bankAcct, txId, amount]
          );
          ledgerBatchId = batch.rows[0].id;
          await client.query(
            `INSERT INTO ledger_entries
               (tenant_id, batch_id, account_id, entry_date, debit, credit,
                reference_type, reference_id, memo)
             VALUES (app.current_tenant(), $1, $2, CURRENT_DATE, 0, $4,
                     'mfs_transaction', $3, 'Fee income')`,
            [ledgerBatchId, incomeAcct, txId, amount]
          );
        }
      }
      await client.query(
        `UPDATE mfs_webhook_events
            SET tenant_id = $2, mfs_transaction_id = $3, processing_state = 'processed', processed_at = now()
          WHERE id = $1`,
        [webhookRow.id, tenantId, txId]
      );
      return { outcome: "processed", txId, status, invoiceStatus, receiptNo, ledgerBatchId };
    });
    if (result.outcome === "rejected") {
      return { status: 200, body: { ok: true, note: result.reason } };
    }
    return {
      status: 200,
      body: {
        ok: true,
        transactionId: result.txId,
        status: result.status,
        invoiceStatus: result.invoiceStatus,
        receiptNo: result.receiptNo,
        ledgerBatchId: result.ledgerBatchId
      }
    };
  }
};

// services/finance-svc/api/webhooks/[provider].ts
var _processor = null;
async function processor() {
  if (_processor) return _processor;
  _processor = new MfsWebhookProcessor(await sharedDb());
  return _processor;
}
var KNOWN_PROVIDERS = /* @__PURE__ */ new Set(["bkash", "nagad", "rocket"]);
var CORS = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Methods": "POST, OPTIONS" };
function providerFromUrl(url) {
  const path = new URL(url ?? "/", "http://internal").pathname;
  const segment = path.split("/").filter(Boolean).pop() ?? "";
  return segment.toLowerCase();
}
async function handler(req, res) {
  if (req.method === "OPTIONS") {
    res.writeHead(204, CORS);
    res.end();
    return;
  }
  if (req.method !== "POST") {
    json(res, 405, { error: "method_not_allowed" }, CORS);
    return;
  }
  const provider = providerFromUrl(req.url);
  if (!KNOWN_PROVIDERS.has(provider)) {
    json(res, 404, { error: "unknown_provider" }, CORS);
    return;
  }
  if (!await enforceRateLimit(req, res, CORS, "service")) return;
  try {
    const rawBody = await readBody(req);
    const headers = Object.fromEntries(
      Object.entries(req.headers).map(([k, v]) => [k, Array.isArray(v) ? v.join(", ") : v ?? ""])
    );
    const sourceIp = req.headers["x-forwarded-for"]?.split(",")[0]?.trim() ?? null;
    const p = await processor();
    const result = await p.process(provider, rawBody, headers, sourceIp);
    json(res, result.status, result.body, CORS);
  } catch (err) {
    console.error(`[finance/webhooks/${provider}] unexpected error`, err);
    json(res, 500, { error: "internal_error" }, CORS);
  }
}
export {
  handler as default
};
