// GENERATED by scripts/build.mjs from services/rms-svc/api/index.ts — do not edit directly.

// packages/server-core/src/http.ts
function corsHeaders(extraHeaders = [], methods = "GET, POST, OPTIONS") {
  return {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": methods,
    "Access-Control-Allow-Headers": [
      "Content-Type",
      "Authorization",
      "X-Tenant-ID",
      "X-User-ID",
      "X-Role",
      ...extraHeaders
    ].join(", ")
  };
}
function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on("data", (c) => chunks.push(c));
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}
function header(req, name) {
  const v = req.headers[name.toLowerCase()];
  return Array.isArray(v) ? v[0] ?? "" : v ?? "";
}
function query(req) {
  const url = new URL(req.url ?? "/", "http://internal");
  return url.searchParams;
}
async function readJson(req) {
  const raw = await readBody(req);
  return JSON.parse(raw);
}
function json(res, code, body, cors) {
  const payload = JSON.stringify(body);
  res.writeHead(code, { ...cors, "Content-Type": "application/json" });
  res.end(payload);
}
var HttpError = class extends Error {
  // Longhand rather than constructor parameter properties: node --test
  // strips types instead of compiling them, and parameter properties are the
  // one TS-only construct it cannot strip. Since every server module reaches
  // this file, that single construct made all of server-core un-testable
  // under the project's `node --test file.ts` convention.
  status;
  code;
  constructor(status, message2, code) {
    super(message2);
    this.status = status;
    this.code = code;
  }
};

// packages/server-core/src/db.ts
import pg from "pg";
function createDb(connectionString, opts = {}) {
  const pool = new pg.Pool({
    connectionString,
    max: 10,
    idleTimeoutMillis: 3e4,
    statement_timeout: 15e3,
    ...opts
  });
  async function inTx(setup, fn) {
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      await setup(client);
      const out = await fn(client);
      await client.query("COMMIT");
      return out;
    } catch (err) {
      try {
        await client.query("ROLLBACK");
      } catch {
      }
      throw err;
    } finally {
      client.release();
    }
  }
  return {
    pool,
    withTenant(ctx, fn) {
      if (!ctx.tenantId) throw new Error("tenant context required");
      return inTx(async (c) => {
        await c.query(
          `SELECT set_config('app.tenant_id', $1, true),
                  set_config('app.user_id',   $2, true),
                  set_config('app.role',      $3, true)`,
          [ctx.tenantId, ctx.userId, ctx.role]
        );
      }, fn);
    },
    withSystemRole(role, fn) {
      return inTx(async (c) => {
        await c.query(`SELECT set_config('app.role', $1, true)`, [role]);
      }, fn);
    },
    end: () => pool.end()
  };
}
async function assertRlsEnforced(db) {
  const { rows } = await db.pool.query(
    `SELECT rolname, rolbypassrls, rolsuper FROM pg_roles WHERE rolname = current_user`
  );
  const me = rows[0];
  if (!me) throw new Error("cannot resolve current_user");
  if (me.rolbypassrls || me.rolsuper) {
    throw new Error(
      `refusing to start: connected as "${me.rolname}" which has ${me.rolsuper ? "SUPERUSER" : "BYPASSRLS"} \u2014 RLS would not be enforced. Connect as the non-privileged runtime role instead.`
    );
  }
}
var _db = null;
async function sharedDb() {
  if (_db) return _db;
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL env var is not set");
  const db = createDb(url, { max: 5 });
  await assertRlsEnforced(db);
  _db = db;
  return db;
}

// packages/server-core/src/rate-limit.ts
var perHour = (n) => n / 3600;
var RATE_LIMITS = {
  // Hammering one phone with OTPs is the attack; 3/hour per phone stops it
  // dead. The IP allowance has to clear a whole school activating at once.
  otp_request: { ip: { capacity: 240, refill: perHour(240) }, identity: { capacity: 3, refill: perHour(3) } },
  // Verification is a guessing attack against a 6-digit code. identity-svc
  // already caps attempts per challenge; this bounds the outer loop of
  // requesting a fresh challenge and guessing again.
  otp_verify: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 10, refill: perHour(10) } },
  // Refresh and logout — authenticated, cheap, but part of the auth surface.
  auth: { ip: { capacity: 600, refill: perHour(600) } },
  // The only endpoint class with real per-request cost. Per-identity is the
  // spend control until F-1310's proper token metering lands.
  ai: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 30, refill: perHour(30) } },
  // Ordinary authenticated traffic. Sized for a school, not a person: a
  // sync/push after a day offline is one request, not many.
  mutation: { ip: { capacity: 900, refill: 15 } },
  read: { ip: { capacity: 1800, refill: 30 } },
  // Machine-to-machine: MFS webhooks, cron workers, ANS dispatch. Already
  // gated by signature or service key; this is a backstop against a loop.
  service: { ip: { capacity: 3e3, refill: 50 } }
};
function clientIp(req) {
  const xff = req.headers["x-forwarded-for"];
  const first = Array.isArray(xff) ? xff[0] : xff;
  const ip = first?.split(",")[0]?.trim() || req.headers["x-real-ip"]?.trim() || req.socket?.remoteAddress || "unknown";
  return ip.slice(0, 64);
}
function buildBuckets(cls, ip, identity) {
  const policy = RATE_LIMITS[cls];
  const buckets = [];
  if (ip) {
    buckets.push({ key: `${cls}:ip:${ip}`, capacity: policy.ip.capacity, refill: policy.ip.refill });
  }
  if (policy.identity && identity) {
    buckets.push({
      key: `${cls}:id:${identity}`,
      capacity: policy.identity.capacity,
      refill: policy.identity.refill
    });
  }
  return buckets;
}
async function consumeRateLimit(cls, ip, identity) {
  const buckets = buildBuckets(cls, ip, identity);
  if (buckets.length === 0) return { allowed: true, retryAfterSec: 0 };
  try {
    const db = await sharedDb();
    const { rows } = await db.pool.query("SELECT * FROM app.rate_limit_consume($1::jsonb)", [JSON.stringify(buckets)]);
    const row = rows[0];
    if (!row) return { allowed: true, retryAfterSec: 0 };
    if (!row.allowed) {
      console.warn(`[rate-limit] refused ${cls}, bucket=${row.blocked_key}, retry=${row.retry_after_sec}s`);
    }
    return { allowed: row.allowed, retryAfterSec: row.retry_after_sec };
  } catch (err) {
    console.error("[rate-limit] check failed, allowing request:", err);
    return { allowed: true, retryAfterSec: 0 };
  }
}
async function enforceRateLimit(req, res, cors, cls, identity) {
  const verdict = await consumeRateLimit(cls, clientIp(req), identity);
  return sendIfRefused(res, cors, verdict);
}
function sendIfRefused(res, cors, verdict) {
  if (verdict.allowed) return true;
  json(
    res,
    429,
    {
      error: "rate_limited",
      message: "too many requests \u2014 please wait before trying again",
      retryAfterSec: verdict.retryAfterSec
    },
    { ...cors, "Retry-After": String(verdict.retryAfterSec) }
  );
  return false;
}

// node_modules/jose/dist/node/esm/runtime/base64url.js
import { Buffer as Buffer2 } from "node:buffer";

// node_modules/jose/dist/node/esm/lib/buffer_utils.js
var encoder = new TextEncoder();
var decoder = new TextDecoder();
var MAX_INT32 = 2 ** 32;
function concat(...buffers) {
  const size = buffers.reduce((acc, { length }) => acc + length, 0);
  const buf = new Uint8Array(size);
  let i = 0;
  for (const buffer of buffers) {
    buf.set(buffer, i);
    i += buffer.length;
  }
  return buf;
}

// node_modules/jose/dist/node/esm/runtime/base64url.js
function normalize(input) {
  let encoded = input;
  if (encoded instanceof Uint8Array) {
    encoded = decoder.decode(encoded);
  }
  return encoded;
}
var decode = (input) => new Uint8Array(Buffer2.from(normalize(input), "base64url"));

// node_modules/jose/dist/node/esm/util/errors.js
var JOSEError = class extends Error {
  static code = "ERR_JOSE_GENERIC";
  code = "ERR_JOSE_GENERIC";
  constructor(message2, options) {
    super(message2, options);
    this.name = this.constructor.name;
    Error.captureStackTrace?.(this, this.constructor);
  }
};
var JWTClaimValidationFailed = class extends JOSEError {
  static code = "ERR_JWT_CLAIM_VALIDATION_FAILED";
  code = "ERR_JWT_CLAIM_VALIDATION_FAILED";
  claim;
  reason;
  payload;
  constructor(message2, payload, claim = "unspecified", reason = "unspecified") {
    super(message2, { cause: { claim, reason, payload } });
    this.claim = claim;
    this.reason = reason;
    this.payload = payload;
  }
};
var JWTExpired = class extends JOSEError {
  static code = "ERR_JWT_EXPIRED";
  code = "ERR_JWT_EXPIRED";
  claim;
  reason;
  payload;
  constructor(message2, payload, claim = "unspecified", reason = "unspecified") {
    super(message2, { cause: { claim, reason, payload } });
    this.claim = claim;
    this.reason = reason;
    this.payload = payload;
  }
};
var JOSEAlgNotAllowed = class extends JOSEError {
  static code = "ERR_JOSE_ALG_NOT_ALLOWED";
  code = "ERR_JOSE_ALG_NOT_ALLOWED";
};
var JOSENotSupported = class extends JOSEError {
  static code = "ERR_JOSE_NOT_SUPPORTED";
  code = "ERR_JOSE_NOT_SUPPORTED";
};
var JWSInvalid = class extends JOSEError {
  static code = "ERR_JWS_INVALID";
  code = "ERR_JWS_INVALID";
};
var JWTInvalid = class extends JOSEError {
  static code = "ERR_JWT_INVALID";
  code = "ERR_JWT_INVALID";
};
var JWSSignatureVerificationFailed = class extends JOSEError {
  static code = "ERR_JWS_SIGNATURE_VERIFICATION_FAILED";
  code = "ERR_JWS_SIGNATURE_VERIFICATION_FAILED";
  constructor(message2 = "signature verification failed", options) {
    super(message2, options);
  }
};

// node_modules/jose/dist/node/esm/runtime/is_key_object.js
import * as util from "node:util";
var is_key_object_default = (obj) => util.types.isKeyObject(obj);

// node_modules/jose/dist/node/esm/runtime/webcrypto.js
import * as crypto from "node:crypto";
import * as util2 from "node:util";
var webcrypto2 = crypto.webcrypto;
var webcrypto_default = webcrypto2;
var isCryptoKey = (key) => util2.types.isCryptoKey(key);

// node_modules/jose/dist/node/esm/lib/crypto_key.js
function unusable(name, prop = "algorithm.name") {
  return new TypeError(`CryptoKey does not support this operation, its ${prop} must be ${name}`);
}
function isAlgorithm(algorithm, name) {
  return algorithm.name === name;
}
function getHashLength(hash) {
  return parseInt(hash.name.slice(4), 10);
}
function getNamedCurve(alg) {
  switch (alg) {
    case "ES256":
      return "P-256";
    case "ES384":
      return "P-384";
    case "ES512":
      return "P-521";
    default:
      throw new Error("unreachable");
  }
}
function checkUsage(key, usages) {
  if (usages.length && !usages.some((expected) => key.usages.includes(expected))) {
    let msg = "CryptoKey does not support this operation, its usages must include ";
    if (usages.length > 2) {
      const last = usages.pop();
      msg += `one of ${usages.join(", ")}, or ${last}.`;
    } else if (usages.length === 2) {
      msg += `one of ${usages[0]} or ${usages[1]}.`;
    } else {
      msg += `${usages[0]}.`;
    }
    throw new TypeError(msg);
  }
}
function checkSigCryptoKey(key, alg, ...usages) {
  switch (alg) {
    case "HS256":
    case "HS384":
    case "HS512": {
      if (!isAlgorithm(key.algorithm, "HMAC"))
        throw unusable("HMAC");
      const expected = parseInt(alg.slice(2), 10);
      const actual = getHashLength(key.algorithm.hash);
      if (actual !== expected)
        throw unusable(`SHA-${expected}`, "algorithm.hash");
      break;
    }
    case "RS256":
    case "RS384":
    case "RS512": {
      if (!isAlgorithm(key.algorithm, "RSASSA-PKCS1-v1_5"))
        throw unusable("RSASSA-PKCS1-v1_5");
      const expected = parseInt(alg.slice(2), 10);
      const actual = getHashLength(key.algorithm.hash);
      if (actual !== expected)
        throw unusable(`SHA-${expected}`, "algorithm.hash");
      break;
    }
    case "PS256":
    case "PS384":
    case "PS512": {
      if (!isAlgorithm(key.algorithm, "RSA-PSS"))
        throw unusable("RSA-PSS");
      const expected = parseInt(alg.slice(2), 10);
      const actual = getHashLength(key.algorithm.hash);
      if (actual !== expected)
        throw unusable(`SHA-${expected}`, "algorithm.hash");
      break;
    }
    case "EdDSA": {
      if (key.algorithm.name !== "Ed25519" && key.algorithm.name !== "Ed448") {
        throw unusable("Ed25519 or Ed448");
      }
      break;
    }
    case "Ed25519": {
      if (!isAlgorithm(key.algorithm, "Ed25519"))
        throw unusable("Ed25519");
      break;
    }
    case "ES256":
    case "ES384":
    case "ES512": {
      if (!isAlgorithm(key.algorithm, "ECDSA"))
        throw unusable("ECDSA");
      const expected = getNamedCurve(alg);
      const actual = key.algorithm.namedCurve;
      if (actual !== expected)
        throw unusable(expected, "algorithm.namedCurve");
      break;
    }
    default:
      throw new TypeError("CryptoKey does not support this operation");
  }
  checkUsage(key, usages);
}

// node_modules/jose/dist/node/esm/lib/invalid_key_input.js
function message(msg, actual, ...types4) {
  types4 = types4.filter(Boolean);
  if (types4.length > 2) {
    const last = types4.pop();
    msg += `one of type ${types4.join(", ")}, or ${last}.`;
  } else if (types4.length === 2) {
    msg += `one of type ${types4[0]} or ${types4[1]}.`;
  } else {
    msg += `of type ${types4[0]}.`;
  }
  if (actual == null) {
    msg += ` Received ${actual}`;
  } else if (typeof actual === "function" && actual.name) {
    msg += ` Received function ${actual.name}`;
  } else if (typeof actual === "object" && actual != null) {
    if (actual.constructor?.name) {
      msg += ` Received an instance of ${actual.constructor.name}`;
    }
  }
  return msg;
}
var invalid_key_input_default = (actual, ...types4) => {
  return message("Key must be ", actual, ...types4);
};
function withAlg(alg, actual, ...types4) {
  return message(`Key for the ${alg} algorithm must be `, actual, ...types4);
}

// node_modules/jose/dist/node/esm/runtime/is_key_like.js
var is_key_like_default = (key) => is_key_object_default(key) || isCryptoKey(key);
var types3 = ["KeyObject"];
if (globalThis.CryptoKey || webcrypto_default?.CryptoKey) {
  types3.push("CryptoKey");
}

// node_modules/jose/dist/node/esm/lib/is_disjoint.js
var isDisjoint = (...headers) => {
  const sources = headers.filter(Boolean);
  if (sources.length === 0 || sources.length === 1) {
    return true;
  }
  let acc;
  for (const header2 of sources) {
    const parameters = Object.keys(header2);
    if (!acc || acc.size === 0) {
      acc = new Set(parameters);
      continue;
    }
    for (const parameter of parameters) {
      if (acc.has(parameter)) {
        return false;
      }
      acc.add(parameter);
    }
  }
  return true;
};
var is_disjoint_default = isDisjoint;

// node_modules/jose/dist/node/esm/lib/is_object.js
function isObjectLike(value) {
  return typeof value === "object" && value !== null;
}
function isObject(input) {
  if (!isObjectLike(input) || Object.prototype.toString.call(input) !== "[object Object]") {
    return false;
  }
  if (Object.getPrototypeOf(input) === null) {
    return true;
  }
  let proto = input;
  while (Object.getPrototypeOf(proto) !== null) {
    proto = Object.getPrototypeOf(proto);
  }
  return Object.getPrototypeOf(input) === proto;
}

// node_modules/jose/dist/node/esm/runtime/get_named_curve.js
import { KeyObject } from "node:crypto";

// node_modules/jose/dist/node/esm/lib/is_jwk.js
function isJWK(key) {
  return isObject(key) && typeof key.kty === "string";
}
function isPrivateJWK(key) {
  return key.kty !== "oct" && typeof key.d === "string";
}
function isPublicJWK(key) {
  return key.kty !== "oct" && typeof key.d === "undefined";
}
function isSecretJWK(key) {
  return isJWK(key) && key.kty === "oct" && typeof key.k === "string";
}

// node_modules/jose/dist/node/esm/runtime/get_named_curve.js
var namedCurveToJOSE = (namedCurve) => {
  switch (namedCurve) {
    case "prime256v1":
      return "P-256";
    case "secp384r1":
      return "P-384";
    case "secp521r1":
      return "P-521";
    case "secp256k1":
      return "secp256k1";
    default:
      throw new JOSENotSupported("Unsupported key curve for this operation");
  }
};
var getNamedCurve2 = (kee, raw) => {
  let key;
  if (isCryptoKey(kee)) {
    key = KeyObject.from(kee);
  } else if (is_key_object_default(kee)) {
    key = kee;
  } else if (isJWK(kee)) {
    return kee.crv;
  } else {
    throw new TypeError(invalid_key_input_default(kee, ...types3));
  }
  if (key.type === "secret") {
    throw new TypeError('only "private" or "public" type keys can be used for this operation');
  }
  switch (key.asymmetricKeyType) {
    case "ed25519":
    case "ed448":
      return `Ed${key.asymmetricKeyType.slice(2)}`;
    case "x25519":
    case "x448":
      return `X${key.asymmetricKeyType.slice(1)}`;
    case "ec": {
      const namedCurve = key.asymmetricKeyDetails.namedCurve;
      if (raw) {
        return namedCurve;
      }
      return namedCurveToJOSE(namedCurve);
    }
    default:
      throw new TypeError("Invalid asymmetric key type for this operation");
  }
};
var get_named_curve_default = getNamedCurve2;

// node_modules/jose/dist/node/esm/runtime/check_key_length.js
import { KeyObject as KeyObject2 } from "node:crypto";
var check_key_length_default = (key, alg) => {
  let modulusLength;
  try {
    if (key instanceof KeyObject2) {
      modulusLength = key.asymmetricKeyDetails?.modulusLength;
    } else {
      modulusLength = Buffer.from(key.n, "base64url").byteLength << 3;
    }
  } catch {
  }
  if (typeof modulusLength !== "number" || modulusLength < 2048) {
    throw new TypeError(`${alg} requires key modulusLength to be 2048 bits or larger`);
  }
};

// node_modules/jose/dist/node/esm/runtime/asn1.js
import { createPrivateKey, createPublicKey, KeyObject as KeyObject3 } from "node:crypto";
import { Buffer as Buffer3 } from "node:buffer";
var fromSPKI = (pem2) => createPublicKey({
  key: Buffer3.from(pem2.replace(/(?:-----(?:BEGIN|END) PUBLIC KEY-----|\s)/g, ""), "base64"),
  type: "spki",
  format: "der"
});

// node_modules/jose/dist/node/esm/runtime/jwk_to_key.js
import { createPrivateKey as createPrivateKey2, createPublicKey as createPublicKey2 } from "node:crypto";
var parse = (key) => {
  if (key.d) {
    return createPrivateKey2({ format: "jwk", key });
  }
  return createPublicKey2({ format: "jwk", key });
};
var jwk_to_key_default = parse;

// node_modules/jose/dist/node/esm/key/import.js
async function importSPKI(spki, alg, options) {
  if (typeof spki !== "string" || spki.indexOf("-----BEGIN PUBLIC KEY-----") !== 0) {
    throw new TypeError('"spki" must be SPKI formatted string');
  }
  return fromSPKI(spki, alg, options);
}
async function importJWK(jwk, alg) {
  if (!isObject(jwk)) {
    throw new TypeError("JWK must be an object");
  }
  alg ||= jwk.alg;
  switch (jwk.kty) {
    case "oct":
      if (typeof jwk.k !== "string" || !jwk.k) {
        throw new TypeError('missing "k" (Key Value) Parameter value');
      }
      return decode(jwk.k);
    case "RSA":
      if ("oth" in jwk && jwk.oth !== void 0) {
        throw new JOSENotSupported('RSA JWK "oth" (Other Primes Info) Parameter value is not supported');
      }
    case "EC":
    case "OKP":
      return jwk_to_key_default({ ...jwk, alg });
    default:
      throw new JOSENotSupported('Unsupported "kty" (Key Type) Parameter value');
  }
}

// node_modules/jose/dist/node/esm/lib/check_key_type.js
var tag = (key) => key?.[Symbol.toStringTag];
var jwkMatchesOp = (alg, key, usage) => {
  if (key.use !== void 0 && key.use !== "sig") {
    throw new TypeError("Invalid key for this operation, when present its use must be sig");
  }
  if (key.key_ops !== void 0 && key.key_ops.includes?.(usage) !== true) {
    throw new TypeError(`Invalid key for this operation, when present its key_ops must include ${usage}`);
  }
  if (key.alg !== void 0 && key.alg !== alg) {
    throw new TypeError(`Invalid key for this operation, when present its alg must be ${alg}`);
  }
  return true;
};
var symmetricTypeCheck = (alg, key, usage, allowJwk) => {
  if (key instanceof Uint8Array)
    return;
  if (allowJwk && isJWK(key)) {
    if (isSecretJWK(key) && jwkMatchesOp(alg, key, usage))
      return;
    throw new TypeError(`JSON Web Key for symmetric algorithms must have JWK "kty" (Key Type) equal to "oct" and the JWK "k" (Key Value) present`);
  }
  if (!is_key_like_default(key)) {
    throw new TypeError(withAlg(alg, key, ...types3, "Uint8Array", allowJwk ? "JSON Web Key" : null));
  }
  if (key.type !== "secret") {
    throw new TypeError(`${tag(key)} instances for symmetric algorithms must be of type "secret"`);
  }
};
var asymmetricTypeCheck = (alg, key, usage, allowJwk) => {
  if (allowJwk && isJWK(key)) {
    switch (usage) {
      case "sign":
        if (isPrivateJWK(key) && jwkMatchesOp(alg, key, usage))
          return;
        throw new TypeError(`JSON Web Key for this operation be a private JWK`);
      case "verify":
        if (isPublicJWK(key) && jwkMatchesOp(alg, key, usage))
          return;
        throw new TypeError(`JSON Web Key for this operation be a public JWK`);
    }
  }
  if (!is_key_like_default(key)) {
    throw new TypeError(withAlg(alg, key, ...types3, allowJwk ? "JSON Web Key" : null));
  }
  if (key.type === "secret") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithms must not be of type "secret"`);
  }
  if (usage === "sign" && key.type === "public") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm signing must be of type "private"`);
  }
  if (usage === "decrypt" && key.type === "public") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm decryption must be of type "private"`);
  }
  if (key.algorithm && usage === "verify" && key.type === "private") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm verifying must be of type "public"`);
  }
  if (key.algorithm && usage === "encrypt" && key.type === "private") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm encryption must be of type "public"`);
  }
};
function checkKeyType(allowJwk, alg, key, usage) {
  const symmetric = alg.startsWith("HS") || alg === "dir" || alg.startsWith("PBES2") || /^A\d{3}(?:GCM)?KW$/.test(alg);
  if (symmetric) {
    symmetricTypeCheck(alg, key, usage, allowJwk);
  } else {
    asymmetricTypeCheck(alg, key, usage, allowJwk);
  }
}
var check_key_type_default = checkKeyType.bind(void 0, false);
var checkKeyTypeWithJwk = checkKeyType.bind(void 0, true);

// node_modules/jose/dist/node/esm/lib/validate_crit.js
function validateCrit(Err, recognizedDefault, recognizedOption, protectedHeader, joseHeader) {
  if (joseHeader.crit !== void 0 && protectedHeader?.crit === void 0) {
    throw new Err('"crit" (Critical) Header Parameter MUST be integrity protected');
  }
  if (!protectedHeader || protectedHeader.crit === void 0) {
    return /* @__PURE__ */ new Set();
  }
  if (!Array.isArray(protectedHeader.crit) || protectedHeader.crit.length === 0 || protectedHeader.crit.some((input) => typeof input !== "string" || input.length === 0)) {
    throw new Err('"crit" (Critical) Header Parameter MUST be an array of non-empty strings when present');
  }
  let recognized;
  if (recognizedOption !== void 0) {
    recognized = new Map([...Object.entries(recognizedOption), ...recognizedDefault.entries()]);
  } else {
    recognized = recognizedDefault;
  }
  for (const parameter of protectedHeader.crit) {
    if (!recognized.has(parameter)) {
      throw new JOSENotSupported(`Extension Header Parameter "${parameter}" is not recognized`);
    }
    if (joseHeader[parameter] === void 0) {
      throw new Err(`Extension Header Parameter "${parameter}" is missing`);
    }
    if (recognized.get(parameter) && protectedHeader[parameter] === void 0) {
      throw new Err(`Extension Header Parameter "${parameter}" MUST be integrity protected`);
    }
  }
  return new Set(protectedHeader.crit);
}
var validate_crit_default = validateCrit;

// node_modules/jose/dist/node/esm/lib/validate_algorithms.js
var validateAlgorithms = (option, algorithms) => {
  if (algorithms !== void 0 && (!Array.isArray(algorithms) || algorithms.some((s) => typeof s !== "string"))) {
    throw new TypeError(`"${option}" option must be an array of strings`);
  }
  if (!algorithms) {
    return void 0;
  }
  return new Set(algorithms);
};
var validate_algorithms_default = validateAlgorithms;

// node_modules/jose/dist/node/esm/runtime/verify.js
import * as crypto3 from "node:crypto";
import { promisify as promisify2 } from "node:util";

// node_modules/jose/dist/node/esm/runtime/dsa_digest.js
function dsaDigest(alg) {
  switch (alg) {
    case "PS256":
    case "RS256":
    case "ES256":
    case "ES256K":
      return "sha256";
    case "PS384":
    case "RS384":
    case "ES384":
      return "sha384";
    case "PS512":
    case "RS512":
    case "ES512":
      return "sha512";
    case "Ed25519":
    case "EdDSA":
      return void 0;
    default:
      throw new JOSENotSupported(`alg ${alg} is not supported either by JOSE or your javascript runtime`);
  }
}

// node_modules/jose/dist/node/esm/runtime/node_key.js
import { constants, KeyObject as KeyObject4 } from "node:crypto";
var ecCurveAlgMap = /* @__PURE__ */ new Map([
  ["ES256", "P-256"],
  ["ES256K", "secp256k1"],
  ["ES384", "P-384"],
  ["ES512", "P-521"]
]);
function keyForCrypto(alg, key) {
  let asymmetricKeyType;
  let asymmetricKeyDetails;
  let isJWK2;
  if (key instanceof KeyObject4) {
    asymmetricKeyType = key.asymmetricKeyType;
    asymmetricKeyDetails = key.asymmetricKeyDetails;
  } else {
    isJWK2 = true;
    switch (key.kty) {
      case "RSA":
        asymmetricKeyType = "rsa";
        break;
      case "EC":
        asymmetricKeyType = "ec";
        break;
      case "OKP": {
        if (key.crv === "Ed25519") {
          asymmetricKeyType = "ed25519";
          break;
        }
        if (key.crv === "Ed448") {
          asymmetricKeyType = "ed448";
          break;
        }
        throw new TypeError("Invalid key for this operation, its crv must be Ed25519 or Ed448");
      }
      default:
        throw new TypeError("Invalid key for this operation, its kty must be RSA, OKP, or EC");
    }
  }
  let options;
  switch (alg) {
    case "Ed25519":
      if (asymmetricKeyType !== "ed25519") {
        throw new TypeError(`Invalid key for this operation, its asymmetricKeyType must be ed25519`);
      }
      break;
    case "EdDSA":
      if (!["ed25519", "ed448"].includes(asymmetricKeyType)) {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be ed25519 or ed448");
      }
      break;
    case "RS256":
    case "RS384":
    case "RS512":
      if (asymmetricKeyType !== "rsa") {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be rsa");
      }
      check_key_length_default(key, alg);
      break;
    case "PS256":
    case "PS384":
    case "PS512":
      if (asymmetricKeyType === "rsa-pss") {
        const { hashAlgorithm, mgf1HashAlgorithm, saltLength } = asymmetricKeyDetails;
        const length = parseInt(alg.slice(-3), 10);
        if (hashAlgorithm !== void 0 && (hashAlgorithm !== `sha${length}` || mgf1HashAlgorithm !== hashAlgorithm)) {
          throw new TypeError(`Invalid key for this operation, its RSA-PSS parameters do not meet the requirements of "alg" ${alg}`);
        }
        if (saltLength !== void 0 && saltLength > length >> 3) {
          throw new TypeError(`Invalid key for this operation, its RSA-PSS parameter saltLength does not meet the requirements of "alg" ${alg}`);
        }
      } else if (asymmetricKeyType !== "rsa") {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be rsa or rsa-pss");
      }
      check_key_length_default(key, alg);
      options = {
        padding: constants.RSA_PKCS1_PSS_PADDING,
        saltLength: constants.RSA_PSS_SALTLEN_DIGEST
      };
      break;
    case "ES256":
    case "ES256K":
    case "ES384":
    case "ES512": {
      if (asymmetricKeyType !== "ec") {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be ec");
      }
      const actual = get_named_curve_default(key);
      const expected = ecCurveAlgMap.get(alg);
      if (actual !== expected) {
        throw new TypeError(`Invalid key curve for the algorithm, its curve must be ${expected}, got ${actual}`);
      }
      options = { dsaEncoding: "ieee-p1363" };
      break;
    }
    default:
      throw new JOSENotSupported(`alg ${alg} is not supported either by JOSE or your javascript runtime`);
  }
  if (isJWK2) {
    return { format: "jwk", key, ...options };
  }
  return options ? { ...options, key } : key;
}

// node_modules/jose/dist/node/esm/runtime/sign.js
import * as crypto2 from "node:crypto";
import { promisify } from "node:util";

// node_modules/jose/dist/node/esm/runtime/hmac_digest.js
function hmacDigest(alg) {
  switch (alg) {
    case "HS256":
      return "sha256";
    case "HS384":
      return "sha384";
    case "HS512":
      return "sha512";
    default:
      throw new JOSENotSupported(`alg ${alg} is not supported either by JOSE or your javascript runtime`);
  }
}

// node_modules/jose/dist/node/esm/runtime/get_sign_verify_key.js
import { KeyObject as KeyObject5, createSecretKey } from "node:crypto";
function getSignVerifyKey(alg, key, usage) {
  if (key instanceof Uint8Array) {
    if (!alg.startsWith("HS")) {
      throw new TypeError(invalid_key_input_default(key, ...types3));
    }
    return createSecretKey(key);
  }
  if (key instanceof KeyObject5) {
    return key;
  }
  if (isCryptoKey(key)) {
    checkSigCryptoKey(key, alg, usage);
    return KeyObject5.from(key);
  }
  if (isJWK(key)) {
    if (alg.startsWith("HS")) {
      return createSecretKey(Buffer.from(key.k, "base64url"));
    }
    return key;
  }
  throw new TypeError(invalid_key_input_default(key, ...types3, "Uint8Array", "JSON Web Key"));
}

// node_modules/jose/dist/node/esm/runtime/sign.js
var oneShotSign = promisify(crypto2.sign);
var sign2 = async (alg, key, data) => {
  const k = getSignVerifyKey(alg, key, "sign");
  if (alg.startsWith("HS")) {
    const hmac = crypto2.createHmac(hmacDigest(alg), k);
    hmac.update(data);
    return hmac.digest();
  }
  return oneShotSign(dsaDigest(alg), data, keyForCrypto(alg, k));
};
var sign_default = sign2;

// node_modules/jose/dist/node/esm/runtime/verify.js
var oneShotVerify = promisify2(crypto3.verify);
var verify2 = async (alg, key, signature, data) => {
  const k = getSignVerifyKey(alg, key, "verify");
  if (alg.startsWith("HS")) {
    const expected = await sign_default(alg, k, data);
    const actual = signature;
    try {
      return crypto3.timingSafeEqual(actual, expected);
    } catch {
      return false;
    }
  }
  const algorithm = dsaDigest(alg);
  const keyInput = keyForCrypto(alg, k);
  try {
    return await oneShotVerify(algorithm, data, keyInput, signature);
  } catch {
    return false;
  }
};
var verify_default = verify2;

// node_modules/jose/dist/node/esm/jws/flattened/verify.js
async function flattenedVerify(jws, key, options) {
  if (!isObject(jws)) {
    throw new JWSInvalid("Flattened JWS must be an object");
  }
  if (jws.protected === void 0 && jws.header === void 0) {
    throw new JWSInvalid('Flattened JWS must have either of the "protected" or "header" members');
  }
  if (jws.protected !== void 0 && typeof jws.protected !== "string") {
    throw new JWSInvalid("JWS Protected Header incorrect type");
  }
  if (jws.payload === void 0) {
    throw new JWSInvalid("JWS Payload missing");
  }
  if (typeof jws.signature !== "string") {
    throw new JWSInvalid("JWS Signature missing or incorrect type");
  }
  if (jws.header !== void 0 && !isObject(jws.header)) {
    throw new JWSInvalid("JWS Unprotected Header incorrect type");
  }
  let parsedProt = {};
  if (jws.protected) {
    try {
      const protectedHeader = decode(jws.protected);
      parsedProt = JSON.parse(decoder.decode(protectedHeader));
    } catch {
      throw new JWSInvalid("JWS Protected Header is invalid");
    }
  }
  if (!is_disjoint_default(parsedProt, jws.header)) {
    throw new JWSInvalid("JWS Protected and JWS Unprotected Header Parameter names must be disjoint");
  }
  const joseHeader = {
    ...parsedProt,
    ...jws.header
  };
  const extensions = validate_crit_default(JWSInvalid, /* @__PURE__ */ new Map([["b64", true]]), options?.crit, parsedProt, joseHeader);
  let b64 = true;
  if (extensions.has("b64")) {
    b64 = parsedProt.b64;
    if (typeof b64 !== "boolean") {
      throw new JWSInvalid('The "b64" (base64url-encode payload) Header Parameter must be a boolean');
    }
  }
  const { alg } = joseHeader;
  if (typeof alg !== "string" || !alg) {
    throw new JWSInvalid('JWS "alg" (Algorithm) Header Parameter missing or invalid');
  }
  const algorithms = options && validate_algorithms_default("algorithms", options.algorithms);
  if (algorithms && !algorithms.has(alg)) {
    throw new JOSEAlgNotAllowed('"alg" (Algorithm) Header Parameter value not allowed');
  }
  if (b64) {
    if (typeof jws.payload !== "string") {
      throw new JWSInvalid("JWS Payload must be a string");
    }
  } else if (typeof jws.payload !== "string" && !(jws.payload instanceof Uint8Array)) {
    throw new JWSInvalid("JWS Payload must be a string or an Uint8Array instance");
  }
  let resolvedKey = false;
  if (typeof key === "function") {
    key = await key(parsedProt, jws);
    resolvedKey = true;
    checkKeyTypeWithJwk(alg, key, "verify");
    if (isJWK(key)) {
      key = await importJWK(key, alg);
    }
  } else {
    checkKeyTypeWithJwk(alg, key, "verify");
  }
  const data = concat(encoder.encode(jws.protected ?? ""), encoder.encode("."), typeof jws.payload === "string" ? encoder.encode(jws.payload) : jws.payload);
  let signature;
  try {
    signature = decode(jws.signature);
  } catch {
    throw new JWSInvalid("Failed to base64url decode the signature");
  }
  const verified = await verify_default(alg, key, signature, data);
  if (!verified) {
    throw new JWSSignatureVerificationFailed();
  }
  let payload;
  if (b64) {
    try {
      payload = decode(jws.payload);
    } catch {
      throw new JWSInvalid("Failed to base64url decode the payload");
    }
  } else if (typeof jws.payload === "string") {
    payload = encoder.encode(jws.payload);
  } else {
    payload = jws.payload;
  }
  const result = { payload };
  if (jws.protected !== void 0) {
    result.protectedHeader = parsedProt;
  }
  if (jws.header !== void 0) {
    result.unprotectedHeader = jws.header;
  }
  if (resolvedKey) {
    return { ...result, key };
  }
  return result;
}

// node_modules/jose/dist/node/esm/jws/compact/verify.js
async function compactVerify(jws, key, options) {
  if (jws instanceof Uint8Array) {
    jws = decoder.decode(jws);
  }
  if (typeof jws !== "string") {
    throw new JWSInvalid("Compact JWS must be a string or Uint8Array");
  }
  const { 0: protectedHeader, 1: payload, 2: signature, length } = jws.split(".");
  if (length !== 3) {
    throw new JWSInvalid("Invalid Compact JWS");
  }
  const verified = await flattenedVerify({ payload, protected: protectedHeader, signature }, key, options);
  const result = { payload: verified.payload, protectedHeader: verified.protectedHeader };
  if (typeof key === "function") {
    return { ...result, key: verified.key };
  }
  return result;
}

// node_modules/jose/dist/node/esm/lib/epoch.js
var epoch_default = (date) => Math.floor(date.getTime() / 1e3);

// node_modules/jose/dist/node/esm/lib/secs.js
var minute = 60;
var hour = minute * 60;
var day = hour * 24;
var week = day * 7;
var year = day * 365.25;
var REGEX = /^(\+|\-)? ?(\d+|\d+\.\d+) ?(seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d|weeks?|w|years?|yrs?|y)(?: (ago|from now))?$/i;
var secs_default = (str) => {
  const matched = REGEX.exec(str);
  if (!matched || matched[4] && matched[1]) {
    throw new TypeError("Invalid time period format");
  }
  const value = parseFloat(matched[2]);
  const unit = matched[3].toLowerCase();
  let numericDate;
  switch (unit) {
    case "sec":
    case "secs":
    case "second":
    case "seconds":
    case "s":
      numericDate = Math.round(value);
      break;
    case "minute":
    case "minutes":
    case "min":
    case "mins":
    case "m":
      numericDate = Math.round(value * minute);
      break;
    case "hour":
    case "hours":
    case "hr":
    case "hrs":
    case "h":
      numericDate = Math.round(value * hour);
      break;
    case "day":
    case "days":
    case "d":
      numericDate = Math.round(value * day);
      break;
    case "week":
    case "weeks":
    case "w":
      numericDate = Math.round(value * week);
      break;
    default:
      numericDate = Math.round(value * year);
      break;
  }
  if (matched[1] === "-" || matched[4] === "ago") {
    return -numericDate;
  }
  return numericDate;
};

// node_modules/jose/dist/node/esm/lib/jwt_claims_set.js
var normalizeTyp = (value) => value.toLowerCase().replace(/^application\//, "");
var checkAudiencePresence = (audPayload, audOption) => {
  if (typeof audPayload === "string") {
    return audOption.includes(audPayload);
  }
  if (Array.isArray(audPayload)) {
    return audOption.some(Set.prototype.has.bind(new Set(audPayload)));
  }
  return false;
};
var jwt_claims_set_default = (protectedHeader, encodedPayload, options = {}) => {
  let payload;
  try {
    payload = JSON.parse(decoder.decode(encodedPayload));
  } catch {
  }
  if (!isObject(payload)) {
    throw new JWTInvalid("JWT Claims Set must be a top-level JSON object");
  }
  const { typ } = options;
  if (typ && (typeof protectedHeader.typ !== "string" || normalizeTyp(protectedHeader.typ) !== normalizeTyp(typ))) {
    throw new JWTClaimValidationFailed('unexpected "typ" JWT header value', payload, "typ", "check_failed");
  }
  const { requiredClaims = [], issuer, subject, audience, maxTokenAge } = options;
  const presenceCheck = [...requiredClaims];
  if (maxTokenAge !== void 0)
    presenceCheck.push("iat");
  if (audience !== void 0)
    presenceCheck.push("aud");
  if (subject !== void 0)
    presenceCheck.push("sub");
  if (issuer !== void 0)
    presenceCheck.push("iss");
  for (const claim of new Set(presenceCheck.reverse())) {
    if (!(claim in payload)) {
      throw new JWTClaimValidationFailed(`missing required "${claim}" claim`, payload, claim, "missing");
    }
  }
  if (issuer && !(Array.isArray(issuer) ? issuer : [issuer]).includes(payload.iss)) {
    throw new JWTClaimValidationFailed('unexpected "iss" claim value', payload, "iss", "check_failed");
  }
  if (subject && payload.sub !== subject) {
    throw new JWTClaimValidationFailed('unexpected "sub" claim value', payload, "sub", "check_failed");
  }
  if (audience && !checkAudiencePresence(payload.aud, typeof audience === "string" ? [audience] : audience)) {
    throw new JWTClaimValidationFailed('unexpected "aud" claim value', payload, "aud", "check_failed");
  }
  let tolerance;
  switch (typeof options.clockTolerance) {
    case "string":
      tolerance = secs_default(options.clockTolerance);
      break;
    case "number":
      tolerance = options.clockTolerance;
      break;
    case "undefined":
      tolerance = 0;
      break;
    default:
      throw new TypeError("Invalid clockTolerance option type");
  }
  const { currentDate } = options;
  const now = epoch_default(currentDate || /* @__PURE__ */ new Date());
  if ((payload.iat !== void 0 || maxTokenAge) && typeof payload.iat !== "number") {
    throw new JWTClaimValidationFailed('"iat" claim must be a number', payload, "iat", "invalid");
  }
  if (payload.nbf !== void 0) {
    if (typeof payload.nbf !== "number") {
      throw new JWTClaimValidationFailed('"nbf" claim must be a number', payload, "nbf", "invalid");
    }
    if (payload.nbf > now + tolerance) {
      throw new JWTClaimValidationFailed('"nbf" claim timestamp check failed', payload, "nbf", "check_failed");
    }
  }
  if (payload.exp !== void 0) {
    if (typeof payload.exp !== "number") {
      throw new JWTClaimValidationFailed('"exp" claim must be a number', payload, "exp", "invalid");
    }
    if (payload.exp <= now - tolerance) {
      throw new JWTExpired('"exp" claim timestamp check failed', payload, "exp", "check_failed");
    }
  }
  if (maxTokenAge) {
    const age = now - payload.iat;
    const max = typeof maxTokenAge === "number" ? maxTokenAge : secs_default(maxTokenAge);
    if (age - tolerance > max) {
      throw new JWTExpired('"iat" claim timestamp check failed (too far in the past)', payload, "iat", "check_failed");
    }
    if (age < 0 - tolerance) {
      throw new JWTClaimValidationFailed('"iat" claim timestamp check failed (it should be in the past)', payload, "iat", "check_failed");
    }
  }
  return payload;
};

// node_modules/jose/dist/node/esm/jwt/verify.js
async function jwtVerify(jwt, key, options) {
  const verified = await compactVerify(jwt, key, options);
  if (verified.protectedHeader.crit?.includes("b64") && verified.protectedHeader.b64 === false) {
    throw new JWTInvalid("JWTs MUST NOT use unencoded payload");
  }
  const payload = jwt_claims_set_default(verified.protectedHeader, verified.payload, options);
  const result = { payload, protectedHeader: verified.protectedHeader };
  if (typeof key === "function") {
    return { ...result, key: verified.key };
  }
  return result;
}

// packages/server-core/src/jwt.ts
var ALG = "EdDSA";
var ISSUER = "shikhon-lms";
function pem(envVar) {
  const v = process.env[envVar];
  if (!v) throw new Error(`${envVar} env var is not set`);
  return v.includes("\\n") ? v.replace(/\\n/g, "\n") : v;
}
var _publicKey = null;
function publicKey() {
  if (!_publicKey) _publicKey = importSPKI(pem("JWT_PUBLIC_KEY"), ALG);
  return _publicKey;
}
async function verifyAccessToken(token) {
  const key = await publicKey();
  const { payload } = await jwtVerify(token, key, { issuer: ISSUER });
  if (!payload.sub || !payload.tid || !payload.role) {
    throw new Error("access token missing required claims");
  }
  return {
    sub: payload.sub,
    tid: payload.tid,
    role: payload.role,
    roles: payload.roles ?? [payload.role]
  };
}

// packages/server-core/src/auth.ts
async function authenticate(req) {
  const authHeader = header(req, "authorization");
  const token = authHeader.startsWith("Bearer ") ? authHeader.slice(7) : "";
  if (!token) throw new HttpError(401, "missing bearer token", "unauthorized");
  try {
    return await verifyAccessToken(token);
  } catch {
    throw new HttpError(401, "invalid or expired access token", "unauthorized");
  }
}
var STAFF_BLOCKLIST = /* @__PURE__ */ new Set(["student", "guardian"]);
function requireStaff(claims) {
  if (STAFF_BLOCKLIST.has(claims.role)) {
    throw new HttpError(403, "this endpoint is restricted to staff", "forbidden");
  }
}
function requireRole(claims, allowed) {
  if (!allowed.includes(claims.role)) {
    throw new HttpError(403, `this endpoint requires one of: ${allowed.join(", ")}`, "forbidden");
  }
}

// services/rms-svc/api/routine.ts
var DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
function mapRow(r) {
  return {
    slotId: r.slot_id,
    periodNo: r.period_no,
    startsAt: r.starts_at,
    endsAt: r.ends_at,
    slotKind: r.slot_kind,
    subjectBn: r.subject_bn,
    sectionLabel: r.section_label,
    roomCode: r.room_code,
    isSubstitution: r.is_substitution,
    coveringForBn: r.covering_for,
    studentCount: r.student_count,
    attendanceTaken: r.attendance_taken,
    deliveryLogged: r.delivery_logged
  };
}
function todayIso() {
  return (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
}
function sundayOnOrBefore(iso) {
  const d = /* @__PURE__ */ new Date(`${iso}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() - d.getUTCDay());
  return d.toISOString().slice(0, 10);
}
function addDays(iso, n) {
  const d = /* @__PURE__ */ new Date(`${iso}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + n);
  return d.toISOString().slice(0, 10);
}
async function handler(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "GET") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const claims = await authenticate(req);
    requireStaff(claims);
    const q = query(req);
    const scope = q.get("scope") === "week" ? "week" : "day";
    const db = await sharedDb();
    const ctx = { tenantId: claims.tid, userId: claims.sub, role: claims.role };
    if (scope === "day") {
      const date = q.get("date") ?? todayIso();
      if (!DATE_RE.test(date)) throw new HttpError(400, "date must be YYYY-MM-DD", "invalid_date");
      const slots = await db.withTenant(ctx, async (client) => {
        const r = await client.query(
          `SELECT * FROM app.teacher_day($1, $2::date)`,
          [claims.sub, date]
        );
        return r.rows.map(mapRow);
      });
      json(res, 200, { scope, date, slots }, cors);
      return;
    }
    const rawStart = q.get("weekStart") ?? sundayOnOrBefore(todayIso());
    if (!DATE_RE.test(rawStart)) throw new HttpError(400, "weekStart must be YYYY-MM-DD", "invalid_date");
    const weekStart = sundayOnOrBefore(rawStart);
    const days = await db.withTenant(ctx, async (client) => {
      const out = [];
      for (let i = 0; i < 7; i++) {
        const date = addDays(weekStart, i);
        const r = await client.query(
          `SELECT * FROM app.teacher_day($1, $2::date)`,
          [claims.sub, date]
        );
        out.push({ date, slots: r.rows.map(mapRow) });
      }
      return out;
    });
    json(res, 200, { scope, weekStart, days }, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error("[rms/routine] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/rms-svc/src/solve.ts
import { randomUUID } from "node:crypto";
var IntervalBook = class {
  byKey = /* @__PURE__ */ new Map();
  add(resourceId, day2, startsAt, endsAt) {
    const k = `${resourceId}|${day2}`;
    const list = this.byKey.get(k);
    if (list) list.push([startsAt, endsAt]);
    else this.byKey.set(k, [[startsAt, endsAt]]);
  }
  overlaps(resourceId, day2, startsAt, endsAt) {
    const list = this.byKey.get(`${resourceId}|${day2}`);
    if (!list) return false;
    const s = norm(startsAt);
    const e = norm(endsAt);
    return list.some(([bs, be]) => s < norm(be) && norm(bs) < e);
  }
};
function norm(t) {
  return t.length === 5 ? `${t}:00` : t;
}
var RmsSolver = class {
  db;
  now;
  constructor(db, opts = {}) {
    this.db = db;
    this.now = opts.now ?? Date.now;
  }
  async solve(routineId, ctx) {
    const startedAt = this.now();
    return this.db.withTenant(ctx, async (client) => {
      const routine = await this.loadRoutine(client, routineId);
      const teachingDays = this.teachingDays(routine.weekendDays);
      const periods = await this.loadTeachingPeriods(client, routine.periodTemplateId);
      if (periods.length === 0) {
        throw Object.assign(new Error("period template has no teaching periods"), { code: "NO_TEACHING_PERIODS" });
      }
      const sections = await this.loadSections(client, routine.academicYearId, routine.shift);
      const demand = await this.loadDemand(client, routine.academicYearId, routine.shift);
      const existing = await this.loadExistingSlots(client, routineId, routine.academicYearId);
      const unavailability = await this.loadUnavailability(client, [...new Set(demand.map((d) => d.teacherId))]);
      const teacherBusy = new IntervalBook();
      const roomBusy = new IntervalBook();
      const sectionBusy = new IntervalBook();
      const sectionSubjectDays = /* @__PURE__ */ new Map();
      const placedCount = /* @__PURE__ */ new Map();
      for (const row of existing) {
        if (row.teacher_id) teacherBusy.add(row.teacher_id, row.day_of_week, row.starts_at, row.ends_at);
        if (row.room_id) roomBusy.add(row.room_id, row.day_of_week, row.starts_at, row.ends_at);
        if (!row.is_mine) continue;
        sectionBusy.add(row.primary_section_id, row.day_of_week, row.starts_at, row.ends_at);
        const ssKey = `${row.primary_section_id}|${row.subject_id}`;
        if (!sectionSubjectDays.has(ssKey)) sectionSubjectDays.set(ssKey, /* @__PURE__ */ new Set());
        sectionSubjectDays.get(ssKey).add(row.day_of_week);
        placedCount.set(ssKey, (placedCount.get(ssKey) ?? 0) + 1);
      }
      const roomBySection = new Map(sections.map((s) => [s.id, s.homeRoomId]));
      const isUnavailable = (teacherId, day2, startsAt, endsAt) => {
        const rows = unavailability.get(teacherId);
        if (!rows) return false;
        return rows.some((u) => u.dayOfWeek === day2 && u.startsAt < endsAt && u.endsAt > startsAt);
      };
      const placements = [];
      const unplaced = [];
      const sorted = [...demand].sort((a, b) => b.periodsPerWeek - a.periodsPerWeek);
      for (const d of sorted) {
        const ssKey = `${d.sectionId}|${d.subjectId}`;
        const already = placedCount.get(ssKey) ?? 0;
        const remaining = Math.max(0, d.periodsPerWeek - already);
        let placedForThis = 0;
        for (let i = 0; i < remaining; i++) {
          const usedDays = sectionSubjectDays.get(ssKey) ?? /* @__PURE__ */ new Set();
          let found = null;
          for (const preferUnusedDay of [true, false]) {
            for (const day3 of teachingDays) {
              if (preferUnusedDay && usedDays.has(day3)) continue;
              for (const period2 of periods) {
                const room = roomBySection.get(d.sectionId) ?? null;
                if (teacherBusy.overlaps(d.teacherId, day3, period2.startsAt, period2.endsAt)) continue;
                if (sectionBusy.overlaps(d.sectionId, day3, period2.startsAt, period2.endsAt)) continue;
                if (room && roomBusy.overlaps(room, day3, period2.startsAt, period2.endsAt)) continue;
                if (isUnavailable(d.teacherId, day3, period2.startsAt, period2.endsAt)) continue;
                found = { day: day3, period: period2 };
                break;
              }
              if (found) break;
            }
            if (found) break;
          }
          if (!found) break;
          const { day: day2, period } = found;
          const roomId = roomBySection.get(d.sectionId) ?? null;
          teacherBusy.add(d.teacherId, day2, period.startsAt, period.endsAt);
          sectionBusy.add(d.sectionId, day2, period.startsAt, period.endsAt);
          if (roomId) roomBusy.add(roomId, day2, period.startsAt, period.endsAt);
          if (!sectionSubjectDays.has(ssKey)) sectionSubjectDays.set(ssKey, /* @__PURE__ */ new Set());
          sectionSubjectDays.get(ssKey).add(day2);
          placements.push({
            sectionId: d.sectionId,
            subjectId: d.subjectId,
            teacherId: d.teacherId,
            dayOfWeek: day2,
            periodNo: period.periodNo,
            periodDefinitionId: period.periodDefinitionId,
            startsAt: period.startsAt,
            endsAt: period.endsAt,
            roomId
          });
          placedForThis++;
        }
        if (placedForThis < remaining) {
          unplaced.push({
            sectionId: d.sectionId,
            subjectId: d.subjectId,
            teacherId: d.teacherId,
            missing: remaining - placedForThis,
            reason: "no_free_slot"
          });
        }
      }
      let inserted = 0;
      for (const p of placements) {
        try {
          await client.query(
            `INSERT INTO routine_slots
               (tenant_id, routine_id, day_of_week, period_no, period_definition_id,
                starts_at, ends_at, slot_kind, primary_section_id, subject_id, teacher_id, room_id)
             VALUES (app.current_tenant(), $1, $2, $3, $4, $5, $6, 'teaching', $7, $8, $9, $10)`,
            [
              routineId,
              p.dayOfWeek,
              p.periodNo,
              p.periodDefinitionId,
              p.startsAt,
              p.endsAt,
              p.sectionId,
              p.subjectId,
              p.teacherId,
              p.roomId
            ]
          );
          inserted++;
        } catch (err) {
          const code = err.code;
          if (code === "23P01" || code === "23505") {
            unplaced.push({
              sectionId: p.sectionId,
              subjectId: p.subjectId,
              teacherId: p.teacherId,
              missing: 1,
              reason: "db_conflict"
            });
            continue;
          }
          throw err;
        }
      }
      const totalDemand = demand.reduce((sum, d) => sum + d.periodsPerWeek, 0);
      const totalPlaced = existing.filter((r) => r.is_mine).length + inserted;
      const objectiveScore = totalDemand > 0 ? Math.round(totalPlaced / totalDemand * 1e4) / 100 : 100;
      const solverRunId = randomUUID();
      const solverSeconds = Math.round((this.now() - startedAt) / 1e3 * 100) / 100;
      await client.query(
        `UPDATE routines
            SET generated_by = 'solver', solver_run_id = $2, solver_seconds = $3,
                objective_score = $4, soft_violations = $5::jsonb, updated_at = now()
          WHERE id = $1`,
        [routineId, solverRunId, solverSeconds, objectiveScore, JSON.stringify(unplaced)]
      );
      return { routineId, solverRunId, totalDemand, placed: totalPlaced, unplaced, objectiveScore, solverSeconds };
    });
  }
  async loadRoutine(client, routineId) {
    const { rows } = await client.query(`SELECT id, academic_year_id, shift, period_template_id, status FROM routines WHERE id = $1`, [routineId]);
    const routine = rows[0];
    if (!routine) throw Object.assign(new Error("routine not found"), { code: "ROUTINE_NOT_FOUND" });
    if (routine.status !== "draft") {
      throw Object.assign(new Error("only draft routines can be solved"), { code: "ROUTINE_NOT_DRAFT" });
    }
    const tenantRes = await client.query(
      `SELECT weekend_days FROM tenants WHERE id = app.current_tenant()`
    );
    return {
      academicYearId: routine.academic_year_id,
      shift: routine.shift,
      periodTemplateId: routine.period_template_id,
      weekendDays: new Set(tenantRes.rows[0]?.weekend_days ?? [5, 6])
    };
  }
  teachingDays(weekendDays) {
    const days = [];
    for (let d = 0; d <= 6; d++) if (!weekendDays.has(d)) days.push(d);
    return days;
  }
  async loadTeachingPeriods(client, templateId) {
    const { rows } = await client.query(
      `SELECT id, period_no, starts_at, ends_at FROM period_definitions
        WHERE template_id = $1 AND kind = 'teaching' ORDER BY period_no`,
      [templateId]
    );
    return rows.map((r) => ({
      periodNo: r.period_no,
      startsAt: r.starts_at,
      endsAt: r.ends_at,
      periodDefinitionId: r.id
    }));
  }
  async loadSections(client, academicYearId, shift) {
    const { rows } = await client.query(
      `SELECT id, home_room_id FROM sections WHERE academic_year_id = $1 AND shift = $2`,
      [academicYearId, shift]
    );
    return rows.map((r) => ({ id: r.id, homeRoomId: r.home_room_id }));
  }
  async loadDemand(client, academicYearId, shift) {
    const { rows } = await client.query(
      `SELECT sst.section_id, sst.subject_id, sst.teacher_id, cs.periods_per_week
         FROM section_subject_teachers sst
         JOIN sections s ON s.id = sst.section_id
         JOIN class_subjects cs ON cs.class_id = s.class_id
          AND cs.subject_id = sst.subject_id AND cs.academic_year_id = sst.academic_year_id
        WHERE sst.academic_year_id = $1 AND s.shift = $2`,
      [academicYearId, shift]
    );
    return rows.map((r) => ({
      sectionId: r.section_id,
      subjectId: r.subject_id,
      teacherId: r.teacher_id,
      periodsPerWeek: r.periods_per_week
    }));
  }
  async loadExistingSlots(client, routineId, academicYearId) {
    const { rows } = await client.query(
      // F-506. This routine's own slots, PLUS every slot in any other
      // ACTIVE routine for the same year — which is the other shift. A
      // teacher booked in the morning is not free in the afternoon just
      // because a different routine_id owns that hour.
      `SELECT rs.primary_section_id, rs.subject_id, rs.teacher_id, rs.day_of_week,
              rs.period_no, rs.starts_at, rs.ends_at, rs.room_id,
              (rs.routine_id = $1) AS is_mine
         FROM routine_slots rs
        WHERE rs.academic_year_id = $2
          AND rs.status = 'active'
          AND rs.slot_kind = 'teaching'
          AND (rs.routine_id = $1 OR rs.routine_status = 'active')`,
      [routineId, academicYearId]
    );
    return rows;
  }
  async loadUnavailability(client, teacherIds) {
    const map = /* @__PURE__ */ new Map();
    if (teacherIds.length === 0) return map;
    const { rows } = await client.query(
      `SELECT teacher_id, day_of_week, starts_at, ends_at FROM teacher_availability
        WHERE teacher_id = ANY($1) AND kind = 'unavailable'`,
      [teacherIds]
    );
    for (const r of rows) {
      if (!map.has(r.teacher_id)) map.set(r.teacher_id, []);
      map.get(r.teacher_id).push({ dayOfWeek: r.day_of_week, startsAt: r.starts_at, endsAt: r.ends_at });
    }
    return map;
  }
};

// services/rms-svc/api/solve.ts
var UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var RMS_ROLES = ["principal", "school_owner", "academic_coordinator"];
async function handler2(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "POST") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const claims = await authenticate(req);
    requireRole(claims, RMS_ROLES);
    const body = await readJson(req);
    const routineId = body.routineId ?? "";
    if (!UUID_RE.test(routineId)) throw new HttpError(400, "routineId must be a valid uuid", "invalid_routine_id");
    const db = await sharedDb();
    const solver = new RmsSolver(db);
    const result = await solver.solve(routineId, { tenantId: claims.tid, userId: claims.sub, role: claims.role });
    json(res, 200, { ok: true, ...result }, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    const code = err.code;
    if (code === "ROUTINE_NOT_FOUND") {
      json(res, 404, { error: code, message: err.message }, cors);
      return;
    }
    if (code === "ROUTINE_NOT_DRAFT" || code === "NO_TEACHING_PERIODS") {
      json(res, 409, { error: code, message: err.message }, cors);
      return;
    }
    console.error("[rms/solve] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/rms-svc/api/substitute.ts
var UUID_RE2 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var DATE_RE2 = /^\d{4}-\d{2}-\d{2}$/;
var SUB_ROLES = ["principal", "school_owner", "academic_coordinator", "dept_head"];
async function handler3(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "POST") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const claims = await authenticate(req);
    requireRole(claims, SUB_ROLES);
    const body = await readJson(req);
    const slotId = body.slotId ?? "";
    const date = body.date ?? "";
    if (!UUID_RE2.test(slotId)) throw new HttpError(400, "slotId must be a valid uuid", "invalid_slot_id");
    if (!DATE_RE2.test(date)) throw new HttpError(400, "date must be YYYY-MM-DD", "invalid_date");
    const db = await sharedDb();
    const ctx = { tenantId: claims.tid, userId: claims.sub, role: claims.role };
    if (body.assign) {
      const substituteTeacherId = body.substituteTeacherId ?? "";
      if (!UUID_RE2.test(substituteTeacherId)) {
        throw new HttpError(400, "substituteTeacherId must be a valid uuid", "invalid_substitute_teacher_id");
      }
      const result = await db.withTenant(ctx, async (client) => {
        const slot = await client.query(
          `SELECT teacher_id FROM routine_slots WHERE id = $1`,
          [slotId]
        );
        if (!slot.rows[0]) throw new HttpError(404, "slot not found", "slot_not_found");
        const inserted = await client.query(
          `INSERT INTO routine_substitutions
             (tenant_id, slot_id, substitution_date, action,
              original_teacher_id, substitute_teacher_id, reason,
              assignment_mode, status, assigned_by)
           VALUES (app.current_tenant(), $1, $2, 'assign', $3, $4, $5, 'manual', 'assigned', $6)
           RETURNING id`,
          [slotId, date, slot.rows[0].teacher_id, substituteTeacherId, body.reason ?? null, claims.sub]
        );
        return { substitutionId: inserted.rows[0].id };
      });
      json(res, 200, { ok: true, ...result }, cors);
      return;
    }
    const candidates = await db.withTenant(ctx, async (client) => {
      const slot = await client.query(
        `SELECT teacher_id, subject_id, time_range, day_of_week
           FROM routine_slots WHERE id = $1`,
        [slotId]
      );
      if (!slot.rows[0]) throw new HttpError(404, "slot not found", "slot_not_found");
      const s = slot.rows[0];
      const r = await client.query(
        `WITH slot_ctx AS (
           SELECT $2::uuid AS subject_id, $3::timerange AS tr, $4::smallint AS dow, $5::date AS d
         ),
         teachers AS (
           SELECT DISTINCT u.id, u.full_name_bn, u.full_name_en
             FROM users u
             JOIN user_roles ur ON ur.user_id = u.id
            WHERE ur.role_code IN ('class_teacher','subject_teacher','dept_head','academic_coordinator')
              AND u.status = 'active'
              AND u.id <> $6
         )
         SELECT t.id AS teacher_id, t.full_name_bn, t.full_name_en,
                EXISTS (SELECT 1 FROM routine_slots rs2
                         WHERE rs2.teacher_id = t.id
                           AND rs2.status = 'active'
                           AND rs2.subject_id IS NOT DISTINCT FROM (SELECT subject_id FROM slot_ctx)
                           AND (SELECT subject_id FROM slot_ctx) IS NOT NULL) AS teaches_subject,
                (SELECT count(*)::int FROM routine_slots rs3
                  WHERE rs3.teacher_id = t.id
                    AND rs3.status = 'active'
                    AND rs3.day_of_week = (SELECT dow FROM slot_ctx)
                    AND rs3.slot_kind = 'teaching') AS load_today,
                (SELECT count(*)::int FROM routine_substitutions sub30
                  WHERE sub30.substitute_teacher_id = t.id
                    AND sub30.substitution_date > (SELECT d FROM slot_ctx) - 30
                    AND sub30.status IN ('assigned','completed')) AS subs_last_30d
           FROM teachers t
          WHERE NOT EXISTS (              -- teaching an overlapping period that weekday
                  SELECT 1 FROM routine_slots busy
                   WHERE busy.teacher_id = t.id
                     AND busy.status = 'active'
                     AND busy.day_of_week = (SELECT dow FROM slot_ctx)
                     AND busy.time_range && (SELECT tr FROM slot_ctx))
            AND NOT EXISTS (              -- already substituting an overlapping period that date
                  SELECT 1 FROM routine_substitutions rsub
                   JOIN routine_slots bslot ON bslot.id = rsub.slot_id
                   WHERE rsub.substitute_teacher_id = t.id
                     AND rsub.substitution_date = (SELECT d FROM slot_ctx)
                     AND rsub.status IN ('proposed','assigned')
                     AND bslot.time_range && (SELECT tr FROM slot_ctx))
            AND NOT EXISTS (              -- on approved leave that date
                  SELECT 1 FROM teacher_leaves tl
                   WHERE tl.teacher_id = t.id
                     AND tl.status IN ('approved','taken')
                     AND (SELECT d FROM slot_ctx) BETWEEN tl.starts_on AND tl.ends_on)
            AND NOT EXISTS (              -- marked unavailable in that window
                  SELECT 1 FROM teacher_availability ta
                   WHERE ta.teacher_id = t.id
                     AND ta.kind = 'unavailable'
                     AND ta.day_of_week = (SELECT dow FROM slot_ctx)
                     AND ta.time_range && (SELECT tr FROM slot_ctx)
                     AND ta.effective_from <= (SELECT d FROM slot_ctx)
                     AND (ta.effective_to IS NULL OR ta.effective_to >= (SELECT d FROM slot_ctx)))
          ORDER BY teaches_subject DESC, load_today ASC, subs_last_30d ASC, t.full_name_bn
          LIMIT 10`,
        [slotId, s.subject_id, s.time_range, s.day_of_week, date, s.teacher_id]
      );
      return r.rows.map((row, i) => ({
        teacherId: row.teacher_id,
        fullName: { bn: row.full_name_bn, en: row.full_name_en },
        rank: i + 1,
        matchScore: (row.teaches_subject ? 50 : 0) + Math.max(0, 30 - row.load_today * 5) + Math.max(0, 20 - row.subs_last_30d * 4),
        matchReasons: [
          row.teaches_subject ? "subject_expertise" : "no_subject_match",
          `load_today:${row.load_today}`,
          `subs_last_30d:${row.subs_last_30d}`
        ]
      }));
    });
    json(res, 200, { ok: true, slotId, date, candidates }, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    const pgErr = err;
    if (pgErr.code === "P0001" || pgErr.code === "23505") {
      json(res, 409, { error: "substitute_conflict", message: pgErr.message ?? "substitute is no longer free" }, cors);
      return;
    }
    console.error("[substitute] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/rms-svc/api/examroutine.ts
var UUID_RE3 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var DATE_RE3 = /^\d{4}-\d{2}-\d{2}$/;
var TIME_RE = /^([01]\d|2[0-3]):[0-5]\d$/;
var EXAM_ROLES = ["principal", "school_owner", "academic_coordinator", "dept_head"];
function endTime(start, minutes) {
  if (!start) return null;
  const [h, m] = start.split(":").map(Number);
  const total = h * 60 + m + (minutes ?? 0);
  const hh = Math.floor(total / 60) % 24;
  return `${String(hh).padStart(2, "0")}:${String(total % 60).padStart(2, "0")}`;
}
function hhmm(t) {
  return t ? t.slice(0, 5) : null;
}
function isoDate(v) {
  if (v === null || v === void 0) return null;
  if (v instanceof Date) {
    return `${v.getFullYear()}-${String(v.getMonth() + 1).padStart(2, "0")}-${String(v.getDate()).padStart(2, "0")}`;
  }
  return String(v).slice(0, 10);
}
async function handler4(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  try {
    const claims = await authenticate(req);
    requireRole(claims, EXAM_ROLES);
    const url = new URL(req.url ?? "/", "http://internal");
    let examId = url.searchParams.get("examId") ?? "";
    let publish = false;
    let reschedule = null;
    if (req.method === "POST") {
      const body = await readJson(req);
      examId = body.examId ?? examId;
      publish = body.publish === true;
      reschedule = body.reschedule ?? null;
      if (reschedule) {
        if (!UUID_RE3.test(reschedule.examSubjectId ?? "")) {
          throw new HttpError(400, "examSubjectId must be a valid uuid", "invalid_exam_subject_id");
        }
        if (!DATE_RE3.test(reschedule.examDate ?? "")) {
          throw new HttpError(400, "examDate must be YYYY-MM-DD", "invalid_exam_date");
        }
        if (!TIME_RE.test(reschedule.startTime ?? "")) {
          throw new HttpError(400, "startTime must be HH:MM", "invalid_start_time");
        }
      }
    } else if (req.method !== "GET") {
      json(res, 405, { error: "method_not_allowed" }, cors);
      return;
    }
    const db = await sharedDb();
    const ctx = { tenantId: claims.tid, userId: claims.sub, role: claims.role };
    if (req.method === "GET" && examId === "") {
      const exams = await db.withTenant(ctx, async (client) => {
        const r = await client.query(
          `SELECT e.id, e.name_bn, e.exam_type, e.starts_on, e.ends_on, e.status
             FROM exams e
             JOIN academic_years y ON y.id = e.academic_year_id
            WHERE y.is_current
            ORDER BY e.starts_on DESC`
        );
        return r.rows.map((e) => ({
          id: e.id,
          nameBn: e.name_bn,
          examType: e.exam_type,
          startsOn: isoDate(e.starts_on),
          endsOn: isoDate(e.ends_on),
          status: e.status
        }));
      });
      json(res, 200, { exams }, cors);
      return;
    }
    if (!UUID_RE3.test(examId)) {
      throw new HttpError(400, "examId must be a valid uuid", "invalid_exam_id");
    }
    const payload = await db.withTenant(ctx, async (client) => {
      const exam = await client.query(
        `SELECT id, name_bn, exam_type, starts_on, ends_on, status FROM exams WHERE id = $1`,
        [examId]
      );
      if (!exam.rows[0]) throw new HttpError(404, "exam not found", "exam_not_found");
      if (reschedule) {
        if (exam.rows[0].status === "published") {
          throw new HttpError(
            409,
            "a published exam routine cannot be rescheduled here",
            "exam_published"
          );
        }
        const moved = await client.query(
          `UPDATE exam_subjects SET exam_date = $2, start_time = $3
            WHERE id = $1 AND exam_id = $4`,
          [reschedule.examSubjectId, reschedule.examDate, reschedule.startTime, examId]
        );
        if (moved.rowCount === 0) {
          throw new HttpError(404, "paper not found in this exam", "paper_not_found");
        }
      }
      if (publish) {
        try {
          await client.query(`UPDATE exams SET status = 'published' WHERE id = $1`, [examId]);
          exam.rows[0].status = "published";
        } catch (err) {
          const code = err.code;
          if (code !== "23514") throw err;
          throw new HttpError(
            409,
            err.message,
            "exam_routine_clash"
          );
        }
      }
      const papers = await client.query(
        `SELECT es.id            AS exam_subject_id,
                sec.name         AS section_name,
                sub.name_bn      AS subject_bn,
                es.exam_date, es.start_time, es.duration_minutes
           FROM exam_subjects es
           JOIN sections sec ON sec.id = es.section_id
           JOIN subjects sub ON sub.id = es.subject_id
          WHERE es.exam_id = $1
          ORDER BY es.exam_date NULLS LAST, es.start_time NULLS LAST, sub.name_bn, sec.name`,
        [examId]
      );
      const clashes = await client.query(
        `SELECT student_name_bn, roll_no, section_name, exam_date,
                subject_a_bn, subject_b_bn, start_a, start_b
           FROM app.exam_student_clashes($1)`,
        [examId]
      );
      const flagged = /* @__PURE__ */ new Set();
      for (const c of clashes.rows) {
        const d = isoDate(c.exam_date);
        flagged.add(`${d}|${c.subject_a_bn}`);
        flagged.add(`${d}|${c.subject_b_bn}`);
      }
      return {
        exam: {
          id: exam.rows[0].id,
          nameBn: exam.rows[0].name_bn,
          examType: exam.rows[0].exam_type,
          startsOn: isoDate(exam.rows[0].starts_on),
          endsOn: isoDate(exam.rows[0].ends_on),
          status: exam.rows[0].status
        },
        papers: papers.rows.map((p) => {
          const date = isoDate(p.exam_date);
          return {
            examSubjectId: p.exam_subject_id,
            sectionName: p.section_name,
            subjectBn: p.subject_bn,
            examDate: date,
            startTime: hhmm(p.start_time),
            endTime: endTime(p.start_time, p.duration_minutes),
            durationMinutes: p.duration_minutes,
            hasClash: date !== null && flagged.has(`${date}|${p.subject_bn}`)
          };
        }),
        clashes: clashes.rows.map((c) => ({
          studentNameBn: c.student_name_bn,
          rollNo: c.roll_no,
          sectionName: c.section_name,
          examDate: isoDate(c.exam_date),
          subjectABn: c.subject_a_bn,
          subjectBBn: c.subject_b_bn,
          startA: hhmm(c.start_a),
          startB: hhmm(c.start_b)
        })),
        // §8.3 counts STUDENTS ("৪ জন শিক্ষার্থীর"), not clash rows. One
        // student with three overlapping papers is one affected child.
        affectedStudents: new Set(
          clashes.rows.map((c) => `${c.section_name}|${c.roll_no}`)
        ).size,
        canPublish: clashes.rows.length === 0
      };
    });
    json(res, 200, payload, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/rms-svc/api/index.ts
var ROUTES = { routine: handler, solve: handler2, substitute: handler3, examroutine: handler4 };
async function handler5(req, res) {
  const path = new URL(req.url ?? "/", "http://internal").pathname;
  const sub = path.split("/").filter(Boolean).pop() ?? "";
  const route = ROUTES[sub];
  if (!route) {
    json(res, 404, { error: "not_found" }, corsHeaders());
    return;
  }
  if (req.method !== "OPTIONS") {
    const cls = req.method === "GET" ? "read" : "mutation";
    if (!await enforceRateLimit(req, res, corsHeaders(), cls)) return;
  }
  return route(req, res);
}
export {
  handler5 as default
};
