// GENERATED by scripts/build.mjs from services/academics-svc/api/index.ts — do not edit directly.

// packages/server-core/src/http.ts
function corsHeaders(extraHeaders = [], methods = "GET, POST, OPTIONS") {
  return {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": methods,
    "Access-Control-Allow-Headers": [
      "Content-Type",
      "Authorization",
      "X-Tenant-ID",
      "X-User-ID",
      "X-Role",
      ...extraHeaders
    ].join(", ")
  };
}
function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on("data", (c) => chunks.push(c));
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}
function header(req, name) {
  const v = req.headers[name.toLowerCase()];
  return Array.isArray(v) ? v[0] ?? "" : v ?? "";
}
function query(req) {
  const url = new URL(req.url ?? "/", "http://internal");
  return url.searchParams;
}
async function readJson(req) {
  const raw = await readBody(req);
  return JSON.parse(raw);
}
function json(res, code, body, cors) {
  const payload = JSON.stringify(body);
  res.writeHead(code, { ...cors, "Content-Type": "application/json" });
  res.end(payload);
}
var HttpError = class extends Error {
  // Longhand rather than constructor parameter properties: node --test
  // strips types instead of compiling them, and parameter properties are the
  // one TS-only construct it cannot strip. Since every server module reaches
  // this file, that single construct made all of server-core un-testable
  // under the project's `node --test file.ts` convention.
  status;
  code;
  constructor(status, message2, code) {
    super(message2);
    this.status = status;
    this.code = code;
  }
};

// packages/server-core/src/db.ts
import pg from "pg";
function createDb(connectionString, opts = {}) {
  const pool = new pg.Pool({
    connectionString,
    max: 10,
    idleTimeoutMillis: 3e4,
    statement_timeout: 15e3,
    ...opts
  });
  async function inTx(setup, fn) {
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      await setup(client);
      const out = await fn(client);
      await client.query("COMMIT");
      return out;
    } catch (err) {
      try {
        await client.query("ROLLBACK");
      } catch {
      }
      throw err;
    } finally {
      client.release();
    }
  }
  return {
    pool,
    withTenant(ctx, fn) {
      if (!ctx.tenantId) throw new Error("tenant context required");
      return inTx(async (c) => {
        await c.query(
          `SELECT set_config('app.tenant_id', $1, true),
                  set_config('app.user_id',   $2, true),
                  set_config('app.role',      $3, true)`,
          [ctx.tenantId, ctx.userId, ctx.role]
        );
      }, fn);
    },
    withSystemRole(role, fn) {
      return inTx(async (c) => {
        await c.query(`SELECT set_config('app.role', $1, true)`, [role]);
      }, fn);
    },
    end: () => pool.end()
  };
}
async function assertRlsEnforced(db) {
  const { rows } = await db.pool.query(
    `SELECT rolname, rolbypassrls, rolsuper FROM pg_roles WHERE rolname = current_user`
  );
  const me = rows[0];
  if (!me) throw new Error("cannot resolve current_user");
  if (me.rolbypassrls || me.rolsuper) {
    throw new Error(
      `refusing to start: connected as "${me.rolname}" which has ${me.rolsuper ? "SUPERUSER" : "BYPASSRLS"} \u2014 RLS would not be enforced. Connect as the non-privileged runtime role instead.`
    );
  }
}
var _db = null;
async function sharedDb() {
  if (_db) return _db;
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL env var is not set");
  const db = createDb(url, { max: 5 });
  await assertRlsEnforced(db);
  _db = db;
  return db;
}

// packages/server-core/src/rate-limit.ts
var perHour = (n) => n / 3600;
var RATE_LIMITS = {
  // Hammering one phone with OTPs is the attack; 3/hour per phone stops it
  // dead. The IP allowance has to clear a whole school activating at once.
  otp_request: { ip: { capacity: 240, refill: perHour(240) }, identity: { capacity: 3, refill: perHour(3) } },
  // Verification is a guessing attack against a 6-digit code. identity-svc
  // already caps attempts per challenge; this bounds the outer loop of
  // requesting a fresh challenge and guessing again.
  otp_verify: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 10, refill: perHour(10) } },
  // Refresh and logout — authenticated, cheap, but part of the auth surface.
  auth: { ip: { capacity: 600, refill: perHour(600) } },
  // The only endpoint class with real per-request cost. Per-identity is the
  // spend control until F-1310's proper token metering lands.
  ai: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 30, refill: perHour(30) } },
  // Ordinary authenticated traffic. Sized for a school, not a person: a
  // sync/push after a day offline is one request, not many.
  mutation: { ip: { capacity: 900, refill: 15 } },
  read: { ip: { capacity: 1800, refill: 30 } },
  // Machine-to-machine: MFS webhooks, cron workers, ANS dispatch. Already
  // gated by signature or service key; this is a backstop against a loop.
  service: { ip: { capacity: 3e3, refill: 50 } }
};
function clientIp(req) {
  const xff = req.headers["x-forwarded-for"];
  const first = Array.isArray(xff) ? xff[0] : xff;
  const ip = first?.split(",")[0]?.trim() || req.headers["x-real-ip"]?.trim() || req.socket?.remoteAddress || "unknown";
  return ip.slice(0, 64);
}
function buildBuckets(cls, ip, identity) {
  const policy = RATE_LIMITS[cls];
  const buckets = [];
  if (ip) {
    buckets.push({ key: `${cls}:ip:${ip}`, capacity: policy.ip.capacity, refill: policy.ip.refill });
  }
  if (policy.identity && identity) {
    buckets.push({
      key: `${cls}:id:${identity}`,
      capacity: policy.identity.capacity,
      refill: policy.identity.refill
    });
  }
  return buckets;
}
async function consumeRateLimit(cls, ip, identity) {
  const buckets = buildBuckets(cls, ip, identity);
  if (buckets.length === 0) return { allowed: true, retryAfterSec: 0 };
  try {
    const db = await sharedDb();
    const { rows } = await db.pool.query("SELECT * FROM app.rate_limit_consume($1::jsonb)", [JSON.stringify(buckets)]);
    const row = rows[0];
    if (!row) return { allowed: true, retryAfterSec: 0 };
    if (!row.allowed) {
      console.warn(`[rate-limit] refused ${cls}, bucket=${row.blocked_key}, retry=${row.retry_after_sec}s`);
    }
    return { allowed: row.allowed, retryAfterSec: row.retry_after_sec };
  } catch (err) {
    console.error("[rate-limit] check failed, allowing request:", err);
    return { allowed: true, retryAfterSec: 0 };
  }
}
async function enforceRateLimit(req, res, cors, cls, identity) {
  const verdict = await consumeRateLimit(cls, clientIp(req), identity);
  return sendIfRefused(res, cors, verdict);
}
function sendIfRefused(res, cors, verdict) {
  if (verdict.allowed) return true;
  json(
    res,
    429,
    {
      error: "rate_limited",
      message: "too many requests \u2014 please wait before trying again",
      retryAfterSec: verdict.retryAfterSec
    },
    { ...cors, "Retry-After": String(verdict.retryAfterSec) }
  );
  return false;
}

// node_modules/jose/dist/node/esm/runtime/base64url.js
import { Buffer as Buffer2 } from "node:buffer";

// node_modules/jose/dist/node/esm/lib/buffer_utils.js
var encoder = new TextEncoder();
var decoder = new TextDecoder();
var MAX_INT32 = 2 ** 32;
function concat(...buffers) {
  const size = buffers.reduce((acc, { length }) => acc + length, 0);
  const buf = new Uint8Array(size);
  let i = 0;
  for (const buffer of buffers) {
    buf.set(buffer, i);
    i += buffer.length;
  }
  return buf;
}

// node_modules/jose/dist/node/esm/runtime/base64url.js
function normalize(input) {
  let encoded = input;
  if (encoded instanceof Uint8Array) {
    encoded = decoder.decode(encoded);
  }
  return encoded;
}
var decode = (input) => new Uint8Array(Buffer2.from(normalize(input), "base64url"));

// node_modules/jose/dist/node/esm/util/errors.js
var JOSEError = class extends Error {
  static code = "ERR_JOSE_GENERIC";
  code = "ERR_JOSE_GENERIC";
  constructor(message2, options) {
    super(message2, options);
    this.name = this.constructor.name;
    Error.captureStackTrace?.(this, this.constructor);
  }
};
var JWTClaimValidationFailed = class extends JOSEError {
  static code = "ERR_JWT_CLAIM_VALIDATION_FAILED";
  code = "ERR_JWT_CLAIM_VALIDATION_FAILED";
  claim;
  reason;
  payload;
  constructor(message2, payload, claim = "unspecified", reason = "unspecified") {
    super(message2, { cause: { claim, reason, payload } });
    this.claim = claim;
    this.reason = reason;
    this.payload = payload;
  }
};
var JWTExpired = class extends JOSEError {
  static code = "ERR_JWT_EXPIRED";
  code = "ERR_JWT_EXPIRED";
  claim;
  reason;
  payload;
  constructor(message2, payload, claim = "unspecified", reason = "unspecified") {
    super(message2, { cause: { claim, reason, payload } });
    this.claim = claim;
    this.reason = reason;
    this.payload = payload;
  }
};
var JOSEAlgNotAllowed = class extends JOSEError {
  static code = "ERR_JOSE_ALG_NOT_ALLOWED";
  code = "ERR_JOSE_ALG_NOT_ALLOWED";
};
var JOSENotSupported = class extends JOSEError {
  static code = "ERR_JOSE_NOT_SUPPORTED";
  code = "ERR_JOSE_NOT_SUPPORTED";
};
var JWSInvalid = class extends JOSEError {
  static code = "ERR_JWS_INVALID";
  code = "ERR_JWS_INVALID";
};
var JWTInvalid = class extends JOSEError {
  static code = "ERR_JWT_INVALID";
  code = "ERR_JWT_INVALID";
};
var JWSSignatureVerificationFailed = class extends JOSEError {
  static code = "ERR_JWS_SIGNATURE_VERIFICATION_FAILED";
  code = "ERR_JWS_SIGNATURE_VERIFICATION_FAILED";
  constructor(message2 = "signature verification failed", options) {
    super(message2, options);
  }
};

// node_modules/jose/dist/node/esm/runtime/is_key_object.js
import * as util from "node:util";
var is_key_object_default = (obj) => util.types.isKeyObject(obj);

// node_modules/jose/dist/node/esm/runtime/webcrypto.js
import * as crypto from "node:crypto";
import * as util2 from "node:util";
var webcrypto2 = crypto.webcrypto;
var webcrypto_default = webcrypto2;
var isCryptoKey = (key) => util2.types.isCryptoKey(key);

// node_modules/jose/dist/node/esm/lib/crypto_key.js
function unusable(name, prop = "algorithm.name") {
  return new TypeError(`CryptoKey does not support this operation, its ${prop} must be ${name}`);
}
function isAlgorithm(algorithm, name) {
  return algorithm.name === name;
}
function getHashLength(hash) {
  return parseInt(hash.name.slice(4), 10);
}
function getNamedCurve(alg) {
  switch (alg) {
    case "ES256":
      return "P-256";
    case "ES384":
      return "P-384";
    case "ES512":
      return "P-521";
    default:
      throw new Error("unreachable");
  }
}
function checkUsage(key, usages) {
  if (usages.length && !usages.some((expected) => key.usages.includes(expected))) {
    let msg = "CryptoKey does not support this operation, its usages must include ";
    if (usages.length > 2) {
      const last = usages.pop();
      msg += `one of ${usages.join(", ")}, or ${last}.`;
    } else if (usages.length === 2) {
      msg += `one of ${usages[0]} or ${usages[1]}.`;
    } else {
      msg += `${usages[0]}.`;
    }
    throw new TypeError(msg);
  }
}
function checkSigCryptoKey(key, alg, ...usages) {
  switch (alg) {
    case "HS256":
    case "HS384":
    case "HS512": {
      if (!isAlgorithm(key.algorithm, "HMAC"))
        throw unusable("HMAC");
      const expected = parseInt(alg.slice(2), 10);
      const actual = getHashLength(key.algorithm.hash);
      if (actual !== expected)
        throw unusable(`SHA-${expected}`, "algorithm.hash");
      break;
    }
    case "RS256":
    case "RS384":
    case "RS512": {
      if (!isAlgorithm(key.algorithm, "RSASSA-PKCS1-v1_5"))
        throw unusable("RSASSA-PKCS1-v1_5");
      const expected = parseInt(alg.slice(2), 10);
      const actual = getHashLength(key.algorithm.hash);
      if (actual !== expected)
        throw unusable(`SHA-${expected}`, "algorithm.hash");
      break;
    }
    case "PS256":
    case "PS384":
    case "PS512": {
      if (!isAlgorithm(key.algorithm, "RSA-PSS"))
        throw unusable("RSA-PSS");
      const expected = parseInt(alg.slice(2), 10);
      const actual = getHashLength(key.algorithm.hash);
      if (actual !== expected)
        throw unusable(`SHA-${expected}`, "algorithm.hash");
      break;
    }
    case "EdDSA": {
      if (key.algorithm.name !== "Ed25519" && key.algorithm.name !== "Ed448") {
        throw unusable("Ed25519 or Ed448");
      }
      break;
    }
    case "Ed25519": {
      if (!isAlgorithm(key.algorithm, "Ed25519"))
        throw unusable("Ed25519");
      break;
    }
    case "ES256":
    case "ES384":
    case "ES512": {
      if (!isAlgorithm(key.algorithm, "ECDSA"))
        throw unusable("ECDSA");
      const expected = getNamedCurve(alg);
      const actual = key.algorithm.namedCurve;
      if (actual !== expected)
        throw unusable(expected, "algorithm.namedCurve");
      break;
    }
    default:
      throw new TypeError("CryptoKey does not support this operation");
  }
  checkUsage(key, usages);
}

// node_modules/jose/dist/node/esm/lib/invalid_key_input.js
function message(msg, actual, ...types4) {
  types4 = types4.filter(Boolean);
  if (types4.length > 2) {
    const last = types4.pop();
    msg += `one of type ${types4.join(", ")}, or ${last}.`;
  } else if (types4.length === 2) {
    msg += `one of type ${types4[0]} or ${types4[1]}.`;
  } else {
    msg += `of type ${types4[0]}.`;
  }
  if (actual == null) {
    msg += ` Received ${actual}`;
  } else if (typeof actual === "function" && actual.name) {
    msg += ` Received function ${actual.name}`;
  } else if (typeof actual === "object" && actual != null) {
    if (actual.constructor?.name) {
      msg += ` Received an instance of ${actual.constructor.name}`;
    }
  }
  return msg;
}
var invalid_key_input_default = (actual, ...types4) => {
  return message("Key must be ", actual, ...types4);
};
function withAlg(alg, actual, ...types4) {
  return message(`Key for the ${alg} algorithm must be `, actual, ...types4);
}

// node_modules/jose/dist/node/esm/runtime/is_key_like.js
var is_key_like_default = (key) => is_key_object_default(key) || isCryptoKey(key);
var types3 = ["KeyObject"];
if (globalThis.CryptoKey || webcrypto_default?.CryptoKey) {
  types3.push("CryptoKey");
}

// node_modules/jose/dist/node/esm/lib/is_disjoint.js
var isDisjoint = (...headers) => {
  const sources = headers.filter(Boolean);
  if (sources.length === 0 || sources.length === 1) {
    return true;
  }
  let acc;
  for (const header2 of sources) {
    const parameters = Object.keys(header2);
    if (!acc || acc.size === 0) {
      acc = new Set(parameters);
      continue;
    }
    for (const parameter of parameters) {
      if (acc.has(parameter)) {
        return false;
      }
      acc.add(parameter);
    }
  }
  return true;
};
var is_disjoint_default = isDisjoint;

// node_modules/jose/dist/node/esm/lib/is_object.js
function isObjectLike(value) {
  return typeof value === "object" && value !== null;
}
function isObject(input) {
  if (!isObjectLike(input) || Object.prototype.toString.call(input) !== "[object Object]") {
    return false;
  }
  if (Object.getPrototypeOf(input) === null) {
    return true;
  }
  let proto = input;
  while (Object.getPrototypeOf(proto) !== null) {
    proto = Object.getPrototypeOf(proto);
  }
  return Object.getPrototypeOf(input) === proto;
}

// node_modules/jose/dist/node/esm/runtime/get_named_curve.js
import { KeyObject } from "node:crypto";

// node_modules/jose/dist/node/esm/lib/is_jwk.js
function isJWK(key) {
  return isObject(key) && typeof key.kty === "string";
}
function isPrivateJWK(key) {
  return key.kty !== "oct" && typeof key.d === "string";
}
function isPublicJWK(key) {
  return key.kty !== "oct" && typeof key.d === "undefined";
}
function isSecretJWK(key) {
  return isJWK(key) && key.kty === "oct" && typeof key.k === "string";
}

// node_modules/jose/dist/node/esm/runtime/get_named_curve.js
var namedCurveToJOSE = (namedCurve) => {
  switch (namedCurve) {
    case "prime256v1":
      return "P-256";
    case "secp384r1":
      return "P-384";
    case "secp521r1":
      return "P-521";
    case "secp256k1":
      return "secp256k1";
    default:
      throw new JOSENotSupported("Unsupported key curve for this operation");
  }
};
var getNamedCurve2 = (kee, raw) => {
  let key;
  if (isCryptoKey(kee)) {
    key = KeyObject.from(kee);
  } else if (is_key_object_default(kee)) {
    key = kee;
  } else if (isJWK(kee)) {
    return kee.crv;
  } else {
    throw new TypeError(invalid_key_input_default(kee, ...types3));
  }
  if (key.type === "secret") {
    throw new TypeError('only "private" or "public" type keys can be used for this operation');
  }
  switch (key.asymmetricKeyType) {
    case "ed25519":
    case "ed448":
      return `Ed${key.asymmetricKeyType.slice(2)}`;
    case "x25519":
    case "x448":
      return `X${key.asymmetricKeyType.slice(1)}`;
    case "ec": {
      const namedCurve = key.asymmetricKeyDetails.namedCurve;
      if (raw) {
        return namedCurve;
      }
      return namedCurveToJOSE(namedCurve);
    }
    default:
      throw new TypeError("Invalid asymmetric key type for this operation");
  }
};
var get_named_curve_default = getNamedCurve2;

// node_modules/jose/dist/node/esm/runtime/check_key_length.js
import { KeyObject as KeyObject2 } from "node:crypto";
var check_key_length_default = (key, alg) => {
  let modulusLength;
  try {
    if (key instanceof KeyObject2) {
      modulusLength = key.asymmetricKeyDetails?.modulusLength;
    } else {
      modulusLength = Buffer.from(key.n, "base64url").byteLength << 3;
    }
  } catch {
  }
  if (typeof modulusLength !== "number" || modulusLength < 2048) {
    throw new TypeError(`${alg} requires key modulusLength to be 2048 bits or larger`);
  }
};

// node_modules/jose/dist/node/esm/runtime/asn1.js
import { createPrivateKey, createPublicKey, KeyObject as KeyObject3 } from "node:crypto";
import { Buffer as Buffer3 } from "node:buffer";
var fromSPKI = (pem2) => createPublicKey({
  key: Buffer3.from(pem2.replace(/(?:-----(?:BEGIN|END) PUBLIC KEY-----|\s)/g, ""), "base64"),
  type: "spki",
  format: "der"
});

// node_modules/jose/dist/node/esm/runtime/jwk_to_key.js
import { createPrivateKey as createPrivateKey2, createPublicKey as createPublicKey2 } from "node:crypto";
var parse = (key) => {
  if (key.d) {
    return createPrivateKey2({ format: "jwk", key });
  }
  return createPublicKey2({ format: "jwk", key });
};
var jwk_to_key_default = parse;

// node_modules/jose/dist/node/esm/key/import.js
async function importSPKI(spki, alg, options) {
  if (typeof spki !== "string" || spki.indexOf("-----BEGIN PUBLIC KEY-----") !== 0) {
    throw new TypeError('"spki" must be SPKI formatted string');
  }
  return fromSPKI(spki, alg, options);
}
async function importJWK(jwk, alg) {
  if (!isObject(jwk)) {
    throw new TypeError("JWK must be an object");
  }
  alg ||= jwk.alg;
  switch (jwk.kty) {
    case "oct":
      if (typeof jwk.k !== "string" || !jwk.k) {
        throw new TypeError('missing "k" (Key Value) Parameter value');
      }
      return decode(jwk.k);
    case "RSA":
      if ("oth" in jwk && jwk.oth !== void 0) {
        throw new JOSENotSupported('RSA JWK "oth" (Other Primes Info) Parameter value is not supported');
      }
    case "EC":
    case "OKP":
      return jwk_to_key_default({ ...jwk, alg });
    default:
      throw new JOSENotSupported('Unsupported "kty" (Key Type) Parameter value');
  }
}

// node_modules/jose/dist/node/esm/lib/check_key_type.js
var tag = (key) => key?.[Symbol.toStringTag];
var jwkMatchesOp = (alg, key, usage) => {
  if (key.use !== void 0 && key.use !== "sig") {
    throw new TypeError("Invalid key for this operation, when present its use must be sig");
  }
  if (key.key_ops !== void 0 && key.key_ops.includes?.(usage) !== true) {
    throw new TypeError(`Invalid key for this operation, when present its key_ops must include ${usage}`);
  }
  if (key.alg !== void 0 && key.alg !== alg) {
    throw new TypeError(`Invalid key for this operation, when present its alg must be ${alg}`);
  }
  return true;
};
var symmetricTypeCheck = (alg, key, usage, allowJwk) => {
  if (key instanceof Uint8Array)
    return;
  if (allowJwk && isJWK(key)) {
    if (isSecretJWK(key) && jwkMatchesOp(alg, key, usage))
      return;
    throw new TypeError(`JSON Web Key for symmetric algorithms must have JWK "kty" (Key Type) equal to "oct" and the JWK "k" (Key Value) present`);
  }
  if (!is_key_like_default(key)) {
    throw new TypeError(withAlg(alg, key, ...types3, "Uint8Array", allowJwk ? "JSON Web Key" : null));
  }
  if (key.type !== "secret") {
    throw new TypeError(`${tag(key)} instances for symmetric algorithms must be of type "secret"`);
  }
};
var asymmetricTypeCheck = (alg, key, usage, allowJwk) => {
  if (allowJwk && isJWK(key)) {
    switch (usage) {
      case "sign":
        if (isPrivateJWK(key) && jwkMatchesOp(alg, key, usage))
          return;
        throw new TypeError(`JSON Web Key for this operation be a private JWK`);
      case "verify":
        if (isPublicJWK(key) && jwkMatchesOp(alg, key, usage))
          return;
        throw new TypeError(`JSON Web Key for this operation be a public JWK`);
    }
  }
  if (!is_key_like_default(key)) {
    throw new TypeError(withAlg(alg, key, ...types3, allowJwk ? "JSON Web Key" : null));
  }
  if (key.type === "secret") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithms must not be of type "secret"`);
  }
  if (usage === "sign" && key.type === "public") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm signing must be of type "private"`);
  }
  if (usage === "decrypt" && key.type === "public") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm decryption must be of type "private"`);
  }
  if (key.algorithm && usage === "verify" && key.type === "private") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm verifying must be of type "public"`);
  }
  if (key.algorithm && usage === "encrypt" && key.type === "private") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm encryption must be of type "public"`);
  }
};
function checkKeyType(allowJwk, alg, key, usage) {
  const symmetric = alg.startsWith("HS") || alg === "dir" || alg.startsWith("PBES2") || /^A\d{3}(?:GCM)?KW$/.test(alg);
  if (symmetric) {
    symmetricTypeCheck(alg, key, usage, allowJwk);
  } else {
    asymmetricTypeCheck(alg, key, usage, allowJwk);
  }
}
var check_key_type_default = checkKeyType.bind(void 0, false);
var checkKeyTypeWithJwk = checkKeyType.bind(void 0, true);

// node_modules/jose/dist/node/esm/lib/validate_crit.js
function validateCrit(Err, recognizedDefault, recognizedOption, protectedHeader, joseHeader) {
  if (joseHeader.crit !== void 0 && protectedHeader?.crit === void 0) {
    throw new Err('"crit" (Critical) Header Parameter MUST be integrity protected');
  }
  if (!protectedHeader || protectedHeader.crit === void 0) {
    return /* @__PURE__ */ new Set();
  }
  if (!Array.isArray(protectedHeader.crit) || protectedHeader.crit.length === 0 || protectedHeader.crit.some((input) => typeof input !== "string" || input.length === 0)) {
    throw new Err('"crit" (Critical) Header Parameter MUST be an array of non-empty strings when present');
  }
  let recognized;
  if (recognizedOption !== void 0) {
    recognized = new Map([...Object.entries(recognizedOption), ...recognizedDefault.entries()]);
  } else {
    recognized = recognizedDefault;
  }
  for (const parameter of protectedHeader.crit) {
    if (!recognized.has(parameter)) {
      throw new JOSENotSupported(`Extension Header Parameter "${parameter}" is not recognized`);
    }
    if (joseHeader[parameter] === void 0) {
      throw new Err(`Extension Header Parameter "${parameter}" is missing`);
    }
    if (recognized.get(parameter) && protectedHeader[parameter] === void 0) {
      throw new Err(`Extension Header Parameter "${parameter}" MUST be integrity protected`);
    }
  }
  return new Set(protectedHeader.crit);
}
var validate_crit_default = validateCrit;

// node_modules/jose/dist/node/esm/lib/validate_algorithms.js
var validateAlgorithms = (option, algorithms) => {
  if (algorithms !== void 0 && (!Array.isArray(algorithms) || algorithms.some((s) => typeof s !== "string"))) {
    throw new TypeError(`"${option}" option must be an array of strings`);
  }
  if (!algorithms) {
    return void 0;
  }
  return new Set(algorithms);
};
var validate_algorithms_default = validateAlgorithms;

// node_modules/jose/dist/node/esm/runtime/verify.js
import * as crypto3 from "node:crypto";
import { promisify as promisify2 } from "node:util";

// node_modules/jose/dist/node/esm/runtime/dsa_digest.js
function dsaDigest(alg) {
  switch (alg) {
    case "PS256":
    case "RS256":
    case "ES256":
    case "ES256K":
      return "sha256";
    case "PS384":
    case "RS384":
    case "ES384":
      return "sha384";
    case "PS512":
    case "RS512":
    case "ES512":
      return "sha512";
    case "Ed25519":
    case "EdDSA":
      return void 0;
    default:
      throw new JOSENotSupported(`alg ${alg} is not supported either by JOSE or your javascript runtime`);
  }
}

// node_modules/jose/dist/node/esm/runtime/node_key.js
import { constants, KeyObject as KeyObject4 } from "node:crypto";
var ecCurveAlgMap = /* @__PURE__ */ new Map([
  ["ES256", "P-256"],
  ["ES256K", "secp256k1"],
  ["ES384", "P-384"],
  ["ES512", "P-521"]
]);
function keyForCrypto(alg, key) {
  let asymmetricKeyType;
  let asymmetricKeyDetails;
  let isJWK2;
  if (key instanceof KeyObject4) {
    asymmetricKeyType = key.asymmetricKeyType;
    asymmetricKeyDetails = key.asymmetricKeyDetails;
  } else {
    isJWK2 = true;
    switch (key.kty) {
      case "RSA":
        asymmetricKeyType = "rsa";
        break;
      case "EC":
        asymmetricKeyType = "ec";
        break;
      case "OKP": {
        if (key.crv === "Ed25519") {
          asymmetricKeyType = "ed25519";
          break;
        }
        if (key.crv === "Ed448") {
          asymmetricKeyType = "ed448";
          break;
        }
        throw new TypeError("Invalid key for this operation, its crv must be Ed25519 or Ed448");
      }
      default:
        throw new TypeError("Invalid key for this operation, its kty must be RSA, OKP, or EC");
    }
  }
  let options;
  switch (alg) {
    case "Ed25519":
      if (asymmetricKeyType !== "ed25519") {
        throw new TypeError(`Invalid key for this operation, its asymmetricKeyType must be ed25519`);
      }
      break;
    case "EdDSA":
      if (!["ed25519", "ed448"].includes(asymmetricKeyType)) {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be ed25519 or ed448");
      }
      break;
    case "RS256":
    case "RS384":
    case "RS512":
      if (asymmetricKeyType !== "rsa") {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be rsa");
      }
      check_key_length_default(key, alg);
      break;
    case "PS256":
    case "PS384":
    case "PS512":
      if (asymmetricKeyType === "rsa-pss") {
        const { hashAlgorithm, mgf1HashAlgorithm, saltLength } = asymmetricKeyDetails;
        const length = parseInt(alg.slice(-3), 10);
        if (hashAlgorithm !== void 0 && (hashAlgorithm !== `sha${length}` || mgf1HashAlgorithm !== hashAlgorithm)) {
          throw new TypeError(`Invalid key for this operation, its RSA-PSS parameters do not meet the requirements of "alg" ${alg}`);
        }
        if (saltLength !== void 0 && saltLength > length >> 3) {
          throw new TypeError(`Invalid key for this operation, its RSA-PSS parameter saltLength does not meet the requirements of "alg" ${alg}`);
        }
      } else if (asymmetricKeyType !== "rsa") {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be rsa or rsa-pss");
      }
      check_key_length_default(key, alg);
      options = {
        padding: constants.RSA_PKCS1_PSS_PADDING,
        saltLength: constants.RSA_PSS_SALTLEN_DIGEST
      };
      break;
    case "ES256":
    case "ES256K":
    case "ES384":
    case "ES512": {
      if (asymmetricKeyType !== "ec") {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be ec");
      }
      const actual = get_named_curve_default(key);
      const expected = ecCurveAlgMap.get(alg);
      if (actual !== expected) {
        throw new TypeError(`Invalid key curve for the algorithm, its curve must be ${expected}, got ${actual}`);
      }
      options = { dsaEncoding: "ieee-p1363" };
      break;
    }
    default:
      throw new JOSENotSupported(`alg ${alg} is not supported either by JOSE or your javascript runtime`);
  }
  if (isJWK2) {
    return { format: "jwk", key, ...options };
  }
  return options ? { ...options, key } : key;
}

// node_modules/jose/dist/node/esm/runtime/sign.js
import * as crypto2 from "node:crypto";
import { promisify } from "node:util";

// node_modules/jose/dist/node/esm/runtime/hmac_digest.js
function hmacDigest(alg) {
  switch (alg) {
    case "HS256":
      return "sha256";
    case "HS384":
      return "sha384";
    case "HS512":
      return "sha512";
    default:
      throw new JOSENotSupported(`alg ${alg} is not supported either by JOSE or your javascript runtime`);
  }
}

// node_modules/jose/dist/node/esm/runtime/get_sign_verify_key.js
import { KeyObject as KeyObject5, createSecretKey } from "node:crypto";
function getSignVerifyKey(alg, key, usage) {
  if (key instanceof Uint8Array) {
    if (!alg.startsWith("HS")) {
      throw new TypeError(invalid_key_input_default(key, ...types3));
    }
    return createSecretKey(key);
  }
  if (key instanceof KeyObject5) {
    return key;
  }
  if (isCryptoKey(key)) {
    checkSigCryptoKey(key, alg, usage);
    return KeyObject5.from(key);
  }
  if (isJWK(key)) {
    if (alg.startsWith("HS")) {
      return createSecretKey(Buffer.from(key.k, "base64url"));
    }
    return key;
  }
  throw new TypeError(invalid_key_input_default(key, ...types3, "Uint8Array", "JSON Web Key"));
}

// node_modules/jose/dist/node/esm/runtime/sign.js
var oneShotSign = promisify(crypto2.sign);
var sign2 = async (alg, key, data) => {
  const k = getSignVerifyKey(alg, key, "sign");
  if (alg.startsWith("HS")) {
    const hmac = crypto2.createHmac(hmacDigest(alg), k);
    hmac.update(data);
    return hmac.digest();
  }
  return oneShotSign(dsaDigest(alg), data, keyForCrypto(alg, k));
};
var sign_default = sign2;

// node_modules/jose/dist/node/esm/runtime/verify.js
var oneShotVerify = promisify2(crypto3.verify);
var verify2 = async (alg, key, signature, data) => {
  const k = getSignVerifyKey(alg, key, "verify");
  if (alg.startsWith("HS")) {
    const expected = await sign_default(alg, k, data);
    const actual = signature;
    try {
      return crypto3.timingSafeEqual(actual, expected);
    } catch {
      return false;
    }
  }
  const algorithm = dsaDigest(alg);
  const keyInput = keyForCrypto(alg, k);
  try {
    return await oneShotVerify(algorithm, data, keyInput, signature);
  } catch {
    return false;
  }
};
var verify_default = verify2;

// node_modules/jose/dist/node/esm/jws/flattened/verify.js
async function flattenedVerify(jws, key, options) {
  if (!isObject(jws)) {
    throw new JWSInvalid("Flattened JWS must be an object");
  }
  if (jws.protected === void 0 && jws.header === void 0) {
    throw new JWSInvalid('Flattened JWS must have either of the "protected" or "header" members');
  }
  if (jws.protected !== void 0 && typeof jws.protected !== "string") {
    throw new JWSInvalid("JWS Protected Header incorrect type");
  }
  if (jws.payload === void 0) {
    throw new JWSInvalid("JWS Payload missing");
  }
  if (typeof jws.signature !== "string") {
    throw new JWSInvalid("JWS Signature missing or incorrect type");
  }
  if (jws.header !== void 0 && !isObject(jws.header)) {
    throw new JWSInvalid("JWS Unprotected Header incorrect type");
  }
  let parsedProt = {};
  if (jws.protected) {
    try {
      const protectedHeader = decode(jws.protected);
      parsedProt = JSON.parse(decoder.decode(protectedHeader));
    } catch {
      throw new JWSInvalid("JWS Protected Header is invalid");
    }
  }
  if (!is_disjoint_default(parsedProt, jws.header)) {
    throw new JWSInvalid("JWS Protected and JWS Unprotected Header Parameter names must be disjoint");
  }
  const joseHeader = {
    ...parsedProt,
    ...jws.header
  };
  const extensions = validate_crit_default(JWSInvalid, /* @__PURE__ */ new Map([["b64", true]]), options?.crit, parsedProt, joseHeader);
  let b64 = true;
  if (extensions.has("b64")) {
    b64 = parsedProt.b64;
    if (typeof b64 !== "boolean") {
      throw new JWSInvalid('The "b64" (base64url-encode payload) Header Parameter must be a boolean');
    }
  }
  const { alg } = joseHeader;
  if (typeof alg !== "string" || !alg) {
    throw new JWSInvalid('JWS "alg" (Algorithm) Header Parameter missing or invalid');
  }
  const algorithms = options && validate_algorithms_default("algorithms", options.algorithms);
  if (algorithms && !algorithms.has(alg)) {
    throw new JOSEAlgNotAllowed('"alg" (Algorithm) Header Parameter value not allowed');
  }
  if (b64) {
    if (typeof jws.payload !== "string") {
      throw new JWSInvalid("JWS Payload must be a string");
    }
  } else if (typeof jws.payload !== "string" && !(jws.payload instanceof Uint8Array)) {
    throw new JWSInvalid("JWS Payload must be a string or an Uint8Array instance");
  }
  let resolvedKey = false;
  if (typeof key === "function") {
    key = await key(parsedProt, jws);
    resolvedKey = true;
    checkKeyTypeWithJwk(alg, key, "verify");
    if (isJWK(key)) {
      key = await importJWK(key, alg);
    }
  } else {
    checkKeyTypeWithJwk(alg, key, "verify");
  }
  const data = concat(encoder.encode(jws.protected ?? ""), encoder.encode("."), typeof jws.payload === "string" ? encoder.encode(jws.payload) : jws.payload);
  let signature;
  try {
    signature = decode(jws.signature);
  } catch {
    throw new JWSInvalid("Failed to base64url decode the signature");
  }
  const verified = await verify_default(alg, key, signature, data);
  if (!verified) {
    throw new JWSSignatureVerificationFailed();
  }
  let payload;
  if (b64) {
    try {
      payload = decode(jws.payload);
    } catch {
      throw new JWSInvalid("Failed to base64url decode the payload");
    }
  } else if (typeof jws.payload === "string") {
    payload = encoder.encode(jws.payload);
  } else {
    payload = jws.payload;
  }
  const result = { payload };
  if (jws.protected !== void 0) {
    result.protectedHeader = parsedProt;
  }
  if (jws.header !== void 0) {
    result.unprotectedHeader = jws.header;
  }
  if (resolvedKey) {
    return { ...result, key };
  }
  return result;
}

// node_modules/jose/dist/node/esm/jws/compact/verify.js
async function compactVerify(jws, key, options) {
  if (jws instanceof Uint8Array) {
    jws = decoder.decode(jws);
  }
  if (typeof jws !== "string") {
    throw new JWSInvalid("Compact JWS must be a string or Uint8Array");
  }
  const { 0: protectedHeader, 1: payload, 2: signature, length } = jws.split(".");
  if (length !== 3) {
    throw new JWSInvalid("Invalid Compact JWS");
  }
  const verified = await flattenedVerify({ payload, protected: protectedHeader, signature }, key, options);
  const result = { payload: verified.payload, protectedHeader: verified.protectedHeader };
  if (typeof key === "function") {
    return { ...result, key: verified.key };
  }
  return result;
}

// node_modules/jose/dist/node/esm/lib/epoch.js
var epoch_default = (date) => Math.floor(date.getTime() / 1e3);

// node_modules/jose/dist/node/esm/lib/secs.js
var minute = 60;
var hour = minute * 60;
var day = hour * 24;
var week = day * 7;
var year = day * 365.25;
var REGEX = /^(\+|\-)? ?(\d+|\d+\.\d+) ?(seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d|weeks?|w|years?|yrs?|y)(?: (ago|from now))?$/i;
var secs_default = (str) => {
  const matched = REGEX.exec(str);
  if (!matched || matched[4] && matched[1]) {
    throw new TypeError("Invalid time period format");
  }
  const value = parseFloat(matched[2]);
  const unit = matched[3].toLowerCase();
  let numericDate;
  switch (unit) {
    case "sec":
    case "secs":
    case "second":
    case "seconds":
    case "s":
      numericDate = Math.round(value);
      break;
    case "minute":
    case "minutes":
    case "min":
    case "mins":
    case "m":
      numericDate = Math.round(value * minute);
      break;
    case "hour":
    case "hours":
    case "hr":
    case "hrs":
    case "h":
      numericDate = Math.round(value * hour);
      break;
    case "day":
    case "days":
    case "d":
      numericDate = Math.round(value * day);
      break;
    case "week":
    case "weeks":
    case "w":
      numericDate = Math.round(value * week);
      break;
    default:
      numericDate = Math.round(value * year);
      break;
  }
  if (matched[1] === "-" || matched[4] === "ago") {
    return -numericDate;
  }
  return numericDate;
};

// node_modules/jose/dist/node/esm/lib/jwt_claims_set.js
var normalizeTyp = (value) => value.toLowerCase().replace(/^application\//, "");
var checkAudiencePresence = (audPayload, audOption) => {
  if (typeof audPayload === "string") {
    return audOption.includes(audPayload);
  }
  if (Array.isArray(audPayload)) {
    return audOption.some(Set.prototype.has.bind(new Set(audPayload)));
  }
  return false;
};
var jwt_claims_set_default = (protectedHeader, encodedPayload, options = {}) => {
  let payload;
  try {
    payload = JSON.parse(decoder.decode(encodedPayload));
  } catch {
  }
  if (!isObject(payload)) {
    throw new JWTInvalid("JWT Claims Set must be a top-level JSON object");
  }
  const { typ } = options;
  if (typ && (typeof protectedHeader.typ !== "string" || normalizeTyp(protectedHeader.typ) !== normalizeTyp(typ))) {
    throw new JWTClaimValidationFailed('unexpected "typ" JWT header value', payload, "typ", "check_failed");
  }
  const { requiredClaims = [], issuer, subject, audience, maxTokenAge } = options;
  const presenceCheck = [...requiredClaims];
  if (maxTokenAge !== void 0)
    presenceCheck.push("iat");
  if (audience !== void 0)
    presenceCheck.push("aud");
  if (subject !== void 0)
    presenceCheck.push("sub");
  if (issuer !== void 0)
    presenceCheck.push("iss");
  for (const claim of new Set(presenceCheck.reverse())) {
    if (!(claim in payload)) {
      throw new JWTClaimValidationFailed(`missing required "${claim}" claim`, payload, claim, "missing");
    }
  }
  if (issuer && !(Array.isArray(issuer) ? issuer : [issuer]).includes(payload.iss)) {
    throw new JWTClaimValidationFailed('unexpected "iss" claim value', payload, "iss", "check_failed");
  }
  if (subject && payload.sub !== subject) {
    throw new JWTClaimValidationFailed('unexpected "sub" claim value', payload, "sub", "check_failed");
  }
  if (audience && !checkAudiencePresence(payload.aud, typeof audience === "string" ? [audience] : audience)) {
    throw new JWTClaimValidationFailed('unexpected "aud" claim value', payload, "aud", "check_failed");
  }
  let tolerance;
  switch (typeof options.clockTolerance) {
    case "string":
      tolerance = secs_default(options.clockTolerance);
      break;
    case "number":
      tolerance = options.clockTolerance;
      break;
    case "undefined":
      tolerance = 0;
      break;
    default:
      throw new TypeError("Invalid clockTolerance option type");
  }
  const { currentDate } = options;
  const now = epoch_default(currentDate || /* @__PURE__ */ new Date());
  if ((payload.iat !== void 0 || maxTokenAge) && typeof payload.iat !== "number") {
    throw new JWTClaimValidationFailed('"iat" claim must be a number', payload, "iat", "invalid");
  }
  if (payload.nbf !== void 0) {
    if (typeof payload.nbf !== "number") {
      throw new JWTClaimValidationFailed('"nbf" claim must be a number', payload, "nbf", "invalid");
    }
    if (payload.nbf > now + tolerance) {
      throw new JWTClaimValidationFailed('"nbf" claim timestamp check failed', payload, "nbf", "check_failed");
    }
  }
  if (payload.exp !== void 0) {
    if (typeof payload.exp !== "number") {
      throw new JWTClaimValidationFailed('"exp" claim must be a number', payload, "exp", "invalid");
    }
    if (payload.exp <= now - tolerance) {
      throw new JWTExpired('"exp" claim timestamp check failed', payload, "exp", "check_failed");
    }
  }
  if (maxTokenAge) {
    const age = now - payload.iat;
    const max = typeof maxTokenAge === "number" ? maxTokenAge : secs_default(maxTokenAge);
    if (age - tolerance > max) {
      throw new JWTExpired('"iat" claim timestamp check failed (too far in the past)', payload, "iat", "check_failed");
    }
    if (age < 0 - tolerance) {
      throw new JWTClaimValidationFailed('"iat" claim timestamp check failed (it should be in the past)', payload, "iat", "check_failed");
    }
  }
  return payload;
};

// node_modules/jose/dist/node/esm/jwt/verify.js
async function jwtVerify(jwt, key, options) {
  const verified = await compactVerify(jwt, key, options);
  if (verified.protectedHeader.crit?.includes("b64") && verified.protectedHeader.b64 === false) {
    throw new JWTInvalid("JWTs MUST NOT use unencoded payload");
  }
  const payload = jwt_claims_set_default(verified.protectedHeader, verified.payload, options);
  const result = { payload, protectedHeader: verified.protectedHeader };
  if (typeof key === "function") {
    return { ...result, key: verified.key };
  }
  return result;
}

// packages/server-core/src/jwt.ts
var ALG = "EdDSA";
var ISSUER = "shikhon-lms";
function pem(envVar) {
  const v = process.env[envVar];
  if (!v) throw new Error(`${envVar} env var is not set`);
  return v.includes("\\n") ? v.replace(/\\n/g, "\n") : v;
}
var _publicKey = null;
function publicKey() {
  if (!_publicKey) _publicKey = importSPKI(pem("JWT_PUBLIC_KEY"), ALG);
  return _publicKey;
}
async function verifyAccessToken(token) {
  const key = await publicKey();
  const { payload } = await jwtVerify(token, key, { issuer: ISSUER });
  if (!payload.sub || !payload.tid || !payload.role) {
    throw new Error("access token missing required claims");
  }
  return {
    sub: payload.sub,
    tid: payload.tid,
    role: payload.role,
    roles: payload.roles ?? [payload.role]
  };
}

// packages/server-core/src/auth.ts
async function authenticate(req) {
  const authHeader = header(req, "authorization");
  const token = authHeader.startsWith("Bearer ") ? authHeader.slice(7) : "";
  if (!token) throw new HttpError(401, "missing bearer token", "unauthorized");
  try {
    return await verifyAccessToken(token);
  } catch {
    throw new HttpError(401, "invalid or expired access token", "unauthorized");
  }
}
var STAFF_BLOCKLIST = /* @__PURE__ */ new Set(["student", "guardian"]);
function requireStaff(claims) {
  if (STAFF_BLOCKLIST.has(claims.role)) {
    throw new HttpError(403, "this endpoint is restricted to staff", "forbidden");
  }
}
function requireRole(claims, allowed) {
  if (!allowed.includes(claims.role)) {
    throw new HttpError(403, `this endpoint requires one of: ${allowed.join(", ")}`, "forbidden");
  }
}

// services/academics-svc/api/sections.ts
async function handler(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "GET") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const claims = await authenticate(req);
    requireStaff(claims);
    const db = await sharedDb();
    const sections = await db.withTenant(
      { tenantId: claims.tid, userId: claims.sub, role: claims.role },
      async (client) => {
        const r = await client.query(
          `SELECT s.id, s.name, s.shift, s.student_count,
                  c.name_bn AS class_name_bn, c.name_en AS class_name_en, c.level_no
             FROM sections s
             JOIN classes c ON c.id = s.class_id
            ORDER BY c.level_no, s.name`
        );
        return r.rows.map((row) => ({
          id: row.id,
          name: row.name,
          shift: row.shift,
          studentCount: row.student_count,
          className: { bn: row.class_name_bn, en: row.class_name_en },
          levelNo: row.level_no
        }));
      }
    );
    json(res, 200, { sections }, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error("[sections] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/academics-svc/api/roster.ts
var UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
async function handler2(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "GET") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const claims = await authenticate(req);
    requireStaff(claims);
    const sectionId = query(req).get("sectionId") ?? "";
    if (!UUID_RE.test(sectionId)) throw new HttpError(400, "sectionId must be a valid uuid", "invalid_section_id");
    const db = await sharedDb();
    const result = await db.withTenant({ tenantId: claims.tid, userId: claims.sub, role: claims.role }, async (client) => {
      const sectionRes = await client.query(
        `SELECT s.id, s.name, s.shift, s.capacity, s.student_count,
                c.name_bn AS class_name_bn, c.name_en AS class_name_en, c.level_no
           FROM sections s
           JOIN classes c ON c.id = s.class_id
          WHERE s.id = $1`,
        [sectionId]
      );
      const section = sectionRes.rows[0];
      if (!section) throw new HttpError(404, "section not found", "section_not_found");
      const rosterRes = await client.query(
        `SELECT e.roll_no, e.student_id, u.full_name_bn, u.full_name_en, u.phone_e164
           FROM enrolments e
           JOIN users u ON u.id = e.student_id
          WHERE e.section_id = $1 AND e.status = 'active'
          ORDER BY e.roll_no`,
        [sectionId]
      );
      return {
        section: {
          id: section.id,
          name: section.name,
          shift: section.shift,
          capacity: section.capacity,
          studentCount: section.student_count,
          className: { bn: section.class_name_bn, en: section.class_name_en },
          levelNo: section.level_no
        },
        roster: rosterRes.rows.map((r) => ({
          rollNo: r.roll_no,
          studentId: r.student_id,
          fullName: { bn: r.full_name_bn, en: r.full_name_en },
          phone: r.phone_e164
        }))
      };
    });
    json(res, 200, result, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error("[roster] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/academics-svc/api/exams.ts
var UUID_RE2 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
async function handler3(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "GET") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const claims = await authenticate(req);
    requireStaff(claims);
    const sectionId = query(req).get("sectionId") ?? "";
    if (!UUID_RE2.test(sectionId)) throw new HttpError(400, "sectionId must be a valid uuid", "invalid_section_id");
    const db = await sharedDb();
    const exams = await db.withTenant(
      { tenantId: claims.tid, userId: claims.sub, role: claims.role },
      async (client) => {
        const r = await client.query(
          `SELECT e.id AS exam_id, e.name_bn, e.name_en, e.exam_type, e.status,
                  e.starts_on, e.ends_on, e.academic_year_id,
                  es.id AS exam_subject_id, es.subject_id,
                  sub.name_bn AS subject_bn, sub.name_en AS subject_en,
                  es.exam_date, es.cq_max, es.mcq_max, es.practical_max, es.ca_max,
                  es.cq_pass, es.mcq_pass, es.marking_locked
             FROM exams e
             JOIN exam_subjects es ON es.exam_id = e.id
             JOIN subjects sub     ON sub.id = es.subject_id
            WHERE es.section_id = $1
            ORDER BY e.starts_on DESC NULLS LAST, e.created_at DESC, sub.name_bn`,
          [sectionId]
        );
        const byExam = /* @__PURE__ */ new Map();
        for (const row of r.rows) {
          let exam = byExam.get(row.exam_id);
          if (!exam) {
            exam = {
              id: row.exam_id,
              nameBn: row.name_bn,
              nameEn: row.name_en,
              examType: row.exam_type,
              status: row.status,
              startsOn: row.starts_on,
              endsOn: row.ends_on,
              academicYearId: row.academic_year_id,
              subjects: []
            };
            byExam.set(row.exam_id, exam);
          }
          exam.subjects.push({
            examSubjectId: row.exam_subject_id,
            subjectId: row.subject_id,
            subject: { bn: row.subject_bn, en: row.subject_en },
            examDate: row.exam_date,
            cqMax: Number(row.cq_max),
            mcqMax: Number(row.mcq_max),
            practicalMax: Number(row.practical_max),
            caMax: Number(row.ca_max),
            cqPass: Number(row.cq_pass),
            mcqPass: Number(row.mcq_pass),
            markingLocked: row.marking_locked
          });
        }
        return [...byExam.values()];
      }
    );
    json(res, 200, { exams }, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error("[exams] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/academics-svc/api/marks.ts
var UUID_RE3 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
async function handler4(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "GET") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const claims = await authenticate(req);
    requireStaff(claims);
    const examSubjectId = query(req).get("examSubjectId") ?? "";
    if (!UUID_RE3.test(examSubjectId)) {
      throw new HttpError(400, "examSubjectId must be a valid uuid", "invalid_exam_subject_id");
    }
    const db = await sharedDb();
    const result = await db.withTenant(
      { tenantId: claims.tid, userId: claims.sub, role: claims.role },
      async (client) => {
        const esRes = await client.query(
          `SELECT es.section_id, es.exam_id, e.academic_year_id, e.status AS exam_status,
                  es.marking_locked, es.cq_max, es.mcq_max, es.practical_max, es.ca_max
             FROM exam_subjects es JOIN exams e ON e.id = es.exam_id
            WHERE es.id = $1`,
          [examSubjectId]
        );
        const es = esRes.rows[0];
        if (!es) throw new HttpError(404, "exam subject not found", "exam_subject_not_found");
        const rows = await client.query(
          `SELECT en.roll_no, en.student_id, u.full_name_bn, u.full_name_en,
                  m.cq_marks, m.mcq_marks, m.practical_marks, m.ca_marks,
                  m.total_marks, m.is_absent, m.grade_letter, m.row_version
             FROM enrolments en
             JOIN users u ON u.id = en.student_id
             LEFT JOIN exam_marks m
               ON m.exam_subject_id = $1 AND m.student_id = en.student_id
            WHERE en.section_id = $2 AND en.status = 'active'
            ORDER BY en.roll_no`,
          [examSubjectId, es.section_id]
        );
        return {
          examSubjectId,
          examId: es.exam_id,
          sectionId: es.section_id,
          academicYearId: es.academic_year_id,
          examStatus: es.exam_status,
          markingLocked: es.marking_locked,
          maxima: {
            cq: Number(es.cq_max),
            mcq: Number(es.mcq_max),
            practical: Number(es.practical_max),
            ca: Number(es.ca_max)
          },
          marks: rows.rows.map((r) => ({
            rollNo: r.roll_no,
            studentId: r.student_id,
            fullName: { bn: r.full_name_bn, en: r.full_name_en },
            cqMarks: r.cq_marks === null ? null : Number(r.cq_marks),
            mcqMarks: r.mcq_marks === null ? null : Number(r.mcq_marks),
            practicalMarks: r.practical_marks === null ? null : Number(r.practical_marks),
            caMarks: r.ca_marks === null ? null : Number(r.ca_marks),
            totalMarks: r.total_marks === null ? null : Number(r.total_marks),
            isAbsent: r.is_absent ?? false,
            gradeLetter: r.grade_letter,
            rowVersion: r.row_version
          }))
        };
      }
    );
    json(res, 200, result, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error("[marks] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/academics-svc/api/publish.ts
var UUID_RE4 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var PUBLISH_ROLES = ["principal", "school_owner", "academic_coordinator"];
async function handler5(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "POST") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const claims = await authenticate(req);
    requireRole(claims, PUBLISH_ROLES);
    const body = await readJson(req);
    const examId = body.examId ?? "";
    if (!UUID_RE4.test(examId)) throw new HttpError(400, "examId must be a valid uuid", "invalid_exam_id");
    const db = await sharedDb();
    const result = await db.withTenant(
      { tenantId: claims.tid, userId: claims.sub, role: claims.role },
      async (client) => {
        const examRes = await client.query(
          `SELECT status, academic_year_id FROM exams WHERE id = $1`,
          [examId]
        );
        const exam = examRes.rows[0];
        if (!exam) throw new HttpError(404, "exam not found", "exam_not_found");
        if (exam.status === "published" || exam.status === "locked") {
          throw new HttpError(409, "exam is already published", "already_published");
        }
        const scaleRes = await client.query(
          `SELECT id FROM grading_scales
            WHERE is_default
              AND effective_from <= CURRENT_DATE
              AND (effective_to IS NULL OR effective_to >= CURRENT_DATE)
            ORDER BY effective_from DESC LIMIT 1`
        );
        const scaleId = scaleRes.rows[0]?.id;
        if (!scaleId) throw new HttpError(422, "no default grading scale configured", "no_grading_scale");
        const graded = await client.query(
          `UPDATE exam_marks m
              SET grade_letter = g.letter,
                  grade_point = g.grade_point,
                  component_failed = g.component_failed,
                  row_version = m.row_version + 1
             FROM exam_subjects es,
                  LATERAL app.compute_subject_grade(
                    app.current_tenant(),
                    m.cq_marks, es.cq_max, es.cq_pass,
                    m.mcq_marks, es.mcq_max, es.mcq_pass,
                    m.practical_marks, m.ca_marks,
                    es.cq_max + es.mcq_max + es.practical_max + es.ca_max,
                    m.is_absent, $2::uuid) g
            WHERE es.id = m.exam_subject_id
              AND es.exam_id = $1`,
          [examId, scaleId]
        );
        const results = await client.query(
          `INSERT INTO exam_results
             (tenant_id, exam_id, student_id, section_id, academic_year_id,
              total_marks, total_max, percentage, gpa, gpa_without_optional,
              letter_grade, subjects_failed, is_pass, computed_at, published_at)
           SELECT app.current_tenant(), $1, s.student_id, s.section_id, $2,
                  s.total_marks, s.total_max,
                  CASE WHEN s.total_max > 0 THEN round(s.total_marks / s.total_max * 100, 2) ELSE 0 END,
                  g.gpa, g.gpa_no_optional,
                  CASE
                    WHEN NOT g.is_pass THEN 'F'
                    WHEN g.gpa >= 5.00 THEN 'A+'
                    WHEN g.gpa >= 4.00 THEN 'A'
                    WHEN g.gpa >= 3.50 THEN 'A-'
                    WHEN g.gpa >= 3.00 THEN 'B'
                    WHEN g.gpa >= 2.00 THEN 'C'
                    WHEN g.gpa >= 1.00 THEN 'D'
                    ELSE 'F'
                  END,
                  g.failed_count, g.is_pass, now(), now()
             FROM (SELECT m.student_id,
                          MIN(es.section_id::text)::uuid AS section_id,
                          SUM(m.total_marks) AS total_marks,
                          SUM(es.cq_max + es.mcq_max + es.practical_max + es.ca_max) AS total_max
                     FROM exam_marks m
                     JOIN exam_subjects es ON es.id = m.exam_subject_id
                    WHERE es.exam_id = $1
                    GROUP BY m.student_id) s,
                  LATERAL app.compute_exam_gpa(app.current_tenant(), $1, s.student_id) g
           ON CONFLICT (tenant_id, exam_id, student_id) DO UPDATE
             SET total_marks = EXCLUDED.total_marks,
                 total_max = EXCLUDED.total_max,
                 percentage = EXCLUDED.percentage,
                 gpa = EXCLUDED.gpa,
                 gpa_without_optional = EXCLUDED.gpa_without_optional,
                 letter_grade = EXCLUDED.letter_grade,
                 subjects_failed = EXCLUDED.subjects_failed,
                 is_pass = EXCLUDED.is_pass,
                 computed_at = now(),
                 published_at = now()`,
          [examId, exam.academic_year_id]
        );
        await client.query(
          `UPDATE exam_results r
              SET rank_in_section = s.rk
             FROM (SELECT id,
                          DENSE_RANK() OVER (PARTITION BY section_id
                                             ORDER BY gpa DESC, total_marks DESC) AS rk
                     FROM exam_results
                    WHERE exam_id = $1) s
            WHERE r.id = s.id`,
          [examId]
        );
        await client.query(
          `UPDATE exam_subjects SET marking_locked = true WHERE exam_id = $1`,
          [examId]
        );
        await client.query(
          `UPDATE exams
              SET status = 'published', published_at = now(), published_by = $2
            WHERE id = $1`,
          [examId, claims.sub]
        );
        return { marksGraded: graded.rowCount ?? 0, resultsPublished: results.rowCount ?? 0 };
      }
    );
    json(res, 200, { ok: true, examId, ...result }, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error("[publish] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/academics-svc/api/scripts.ts
var UUID_RE5 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var HEX64_RE = /^[0-9a-f]{64}$/i;
var SCRIPT_STORAGE_ENABLED = false;
var MAX_PAGE_BYTES = 250 * 1024;
var MIN_PAGE_BYTES = 4 * 1024;
async function handler6(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "POST") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const claims = await authenticate(req);
    requireStaff(claims);
    const body = await readJson(req);
    const id = body.id ?? "";
    const examSubjectId = body.examSubjectId ?? "";
    const studentId = body.studentId ?? "";
    const pageNo = Number(body.pageNo ?? 1);
    const byteSize = Number(body.byteSize ?? 0);
    const sha256 = body.sha256 ?? "";
    const capturedAt = body.capturedAt ?? "";
    const contentType = body.contentType ?? "image/jpeg";
    if (!UUID_RE5.test(id)) throw new HttpError(400, "id must be a valid uuid", "invalid_id");
    if (!UUID_RE5.test(examSubjectId)) throw new HttpError(400, "examSubjectId must be a valid uuid", "invalid_exam_subject_id");
    if (!UUID_RE5.test(studentId)) throw new HttpError(400, "studentId must be a valid uuid", "invalid_student_id");
    if (!Number.isInteger(pageNo) || pageNo < 1 || pageNo > 20) throw new HttpError(400, "pageNo must be 1..20", "invalid_page_no");
    if (byteSize < MIN_PAGE_BYTES || byteSize > MAX_PAGE_BYTES) {
      throw new HttpError(413, `byteSize must be ${MIN_PAGE_BYTES}..${MAX_PAGE_BYTES}`, "page_too_large");
    }
    if (!HEX64_RE.test(sha256)) throw new HttpError(400, "sha256 must be a 64-char hex digest", "invalid_sha256");
    if (!Number.isFinite(Date.parse(capturedAt))) throw new HttpError(400, "capturedAt must be ISO 8601", "invalid_captured_at");
    if (contentType !== "image/jpeg" && contentType !== "image/webp") {
      throw new HttpError(415, "contentType must be image/jpeg or image/webp", "unsupported_content_type");
    }
    if (!SCRIPT_STORAGE_ENABLED) {
      json(res, 503, {
        error: "script_storage_unconfigured",
        message: "answer-script object storage is not yet enabled"
      }, cors);
      return;
    }
    const db = await sharedDb();
    const result = await db.withTenant(
      { tenantId: claims.tid, userId: claims.sub, role: claims.role },
      async (client) => {
        const yearRow = await client.query(
          `SELECT EXTRACT(year FROM COALESCE(e.starts_on, CURRENT_DATE))::int AS y
             FROM exam_subjects es JOIN exams e ON e.id = es.exam_id
            WHERE es.id = $1`,
          [examSubjectId]
        );
        const year2 = yearRow.rows[0]?.y ?? new Date(capturedAt).getUTCFullYear();
        const objectKey = `scripts/${claims.tid}/${year2}/${examSubjectId}/${studentId}/${pageNo}.jpg`;
        const row = await client.query(
          `INSERT INTO answer_scripts
             (id, tenant_id, exam_subject_id, student_id, page_no,
              object_key, content_type, byte_size, sha256, original_bytes,
              captured_at, captured_by, upload_state)
           VALUES ($1, app.current_tenant(), $2, $3, $4, $5, $6, $7,
                   decode($8, 'hex'), $9, $10, $11, 'pending')
           ON CONFLICT (tenant_id, exam_subject_id, student_id, page_no) DO UPDATE
             SET byte_size = EXCLUDED.byte_size,
                 sha256 = EXCLUDED.sha256,
                 original_bytes = EXCLUDED.original_bytes,
                 captured_at = EXCLUDED.captured_at,
                 upload_state = CASE
                   WHEN answer_scripts.upload_state = 'complete' THEN 'complete'
                   ELSE 'pending'
                 END
           RETURNING id, upload_state`,
          [
            id,
            examSubjectId,
            studentId,
            pageNo,
            objectKey,
            contentType,
            byteSize,
            sha256,
            body.originalBytes ?? null,
            capturedAt,
            claims.sub
          ]
        );
        return { scriptId: row.rows[0].id, objectKey, uploadState: row.rows[0].upload_state };
      }
    );
    json(res, 200, { ok: true, ...result }, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error("[scripts] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/academics-svc/api/chapters.ts
var UUID_RE6 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
async function handler7(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "GET") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const claims = await authenticate(req);
    const q = query(req);
    const classId = q.get("classId") ?? "";
    const subjectId = q.get("subjectId") ?? "";
    if (!UUID_RE6.test(classId)) {
      throw new HttpError(400, "classId must be a valid uuid", "invalid_class_id");
    }
    if (subjectId && !UUID_RE6.test(subjectId)) {
      throw new HttpError(400, "subjectId must be a valid uuid", "invalid_subject_id");
    }
    const db = await sharedDb();
    const chapters = await db.withTenant(
      { tenantId: claims.tid, userId: claims.sub, role: claims.role },
      async (client) => {
        const r = await client.query(
          `SELECT ch.id, ch.chapter_no, ch.name_bn, ch.name_en, ch.summary_bn,
                  ch.est_minutes, ch.is_published,
                  ch.subject_id, s.name_bn AS subject_bn, s.name_en AS subject_en,
                  ch.prerequisite_chapter_id,
                  pre.name_bn AS prerequisite_name_bn,
                  (SELECT count(*)::int FROM lessons l
                    WHERE l.chapter_id = ch.id AND l.is_published) AS lesson_count,
                  (SELECT count(*)::int FROM lessons l
                     JOIN lesson_progress lp
                       ON lp.lesson_id = l.id
                      AND lp.student_id = $3
                      AND lp.state = 'completed'
                    WHERE l.chapter_id = ch.id AND l.is_published) AS completed_count
             FROM chapters ch
             JOIN subjects s ON s.id = ch.subject_id
             LEFT JOIN chapters pre ON pre.id = ch.prerequisite_chapter_id
            WHERE ch.class_id = $1
              AND ($2::uuid IS NULL OR ch.subject_id = $2)
            ORDER BY s.name_bn, ch.display_order, ch.chapter_no`,
          [classId, subjectId || null, claims.sub]
        );
        return r.rows;
      }
    );
    json(res, 200, {
      chapters: chapters.map((c) => ({
        id: c.id,
        chapterNo: c.chapter_no,
        name: { bn: c.name_bn, en: c.name_en },
        summaryBn: c.summary_bn,
        estMinutes: c.est_minutes,
        isPublished: c.is_published,
        subject: { id: c.subject_id, bn: c.subject_bn, en: c.subject_en },
        prerequisite: c.prerequisite_chapter_id ? { id: c.prerequisite_chapter_id, nameBn: c.prerequisite_name_bn } : null,
        lessonCount: c.lesson_count,
        completedCount: c.completed_count
      }))
    }, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error("[chapters] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/academics-svc/api/lessons.ts
var UUID_RE7 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
async function handler8(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "GET") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const claims = await authenticate(req);
    const q = query(req);
    const chapterId = q.get("chapterId") ?? "";
    const lessonId = q.get("lessonId") ?? "";
    if (!chapterId && !lessonId) {
      throw new HttpError(400, "chapterId or lessonId is required", "missing_parameter");
    }
    if (chapterId && !UUID_RE7.test(chapterId)) {
      throw new HttpError(400, "chapterId must be a valid uuid", "invalid_chapter_id");
    }
    if (lessonId && !UUID_RE7.test(lessonId)) {
      throw new HttpError(400, "lessonId must be a valid uuid", "invalid_lesson_id");
    }
    const db = await sharedDb();
    const ctx = { tenantId: claims.tid, userId: claims.sub, role: claims.role };
    if (lessonId) {
      const result = await db.withTenant(ctx, async (client) => {
        const lessonRes = await client.query(
          `SELECT l.id, l.lesson_no, l.title_bn, l.title_en, l.est_minutes,
                  l.chapter_id, ch.name_bn AS chapter_name_bn,
                  lp.state, lp.seconds_spent, lp.last_block_no
             FROM lessons l
             JOIN chapters ch ON ch.id = l.chapter_id
             LEFT JOIN lesson_progress lp
               ON lp.lesson_id = l.id AND lp.student_id = $2
            WHERE l.id = $1`,
          [lessonId, claims.sub]
        );
        const lesson = lessonRes.rows[0];
        if (!lesson) throw new HttpError(404, "lesson not found", "lesson_not_found");
        const blocksRes = await client.query(
          `SELECT id, block_no, kind::text, body_bn, media_key, alt_text_bn, caption_bn
             FROM lesson_blocks
            WHERE lesson_id = $1
            ORDER BY block_no`,
          [lessonId]
        );
        return {
          lesson: {
            id: lesson.id,
            lessonNo: lesson.lesson_no,
            title: { bn: lesson.title_bn, en: lesson.title_en },
            estMinutes: lesson.est_minutes,
            chapter: { id: lesson.chapter_id, nameBn: lesson.chapter_name_bn },
            progress: lesson.state ? {
              state: lesson.state,
              secondsSpent: lesson.seconds_spent ?? 0,
              lastBlockNo: lesson.last_block_no
            } : null
          },
          blocks: blocksRes.rows.map((b) => ({
            id: b.id,
            blockNo: b.block_no,
            kind: b.kind,
            bodyBn: b.body_bn,
            mediaKey: b.media_key,
            altTextBn: b.alt_text_bn,
            captionBn: b.caption_bn
          }))
        };
      });
      json(res, 200, result, cors);
      return;
    }
    const lessons = await db.withTenant(ctx, async (client) => {
      const r = await client.query(
        `SELECT l.id, l.lesson_no, l.title_bn, l.title_en, l.est_minutes, l.is_published,
                lp.state, lp.seconds_spent
           FROM lessons l
           LEFT JOIN lesson_progress lp
             ON lp.lesson_id = l.id AND lp.student_id = $2
          WHERE l.chapter_id = $1
          ORDER BY l.display_order, l.lesson_no`,
        [chapterId, claims.sub]
      );
      return r.rows;
    });
    json(res, 200, {
      chapterId,
      lessons: lessons.map((l) => ({
        id: l.id,
        lessonNo: l.lesson_no,
        title: { bn: l.title_bn, en: l.title_en },
        estMinutes: l.est_minutes,
        isPublished: l.is_published,
        progress: l.state ? { state: l.state, secondsSpent: l.seconds_spent ?? 0 } : null
      }))
    }, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error("[lessons] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/academics-svc/api/results.ts
var UUID_RE8 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
async function handler9(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "GET") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const claims = await authenticate(req);
    const requested = query(req).get("studentId") ?? "";
    if (requested && !UUID_RE8.test(requested)) {
      throw new HttpError(400, "studentId must be a valid uuid", "invalid_student_id");
    }
    const studentId = requested || claims.sub;
    const db = await sharedDb();
    const rows = await db.withTenant(
      { tenantId: claims.tid, userId: claims.sub, role: claims.role },
      async (client) => {
        const r = await client.query(
          `SELECT r.exam_id, e.name_bn AS exam_name_bn, e.exam_type::text,
                  r.total_marks::text, r.total_max::text, r.percentage::text,
                  r.gpa::text, r.letter_grade, r.subjects_failed, r.is_pass,
                  r.rank_in_section, r.published_at::text,
                  COALESCE((
                    SELECT jsonb_agg(jsonb_build_object(
                             'subjectBn', sub.name_bn,
                             'totalMarks', m.total_marks::text,
                             'gradeLetter', m.grade_letter,
                             'gradePoint', m.grade_point::text,
                             'isAbsent', m.is_absent)
                           ORDER BY sub.name_bn)
                      FROM exam_marks m
                      JOIN exam_subjects es ON es.id = m.exam_subject_id
                      JOIN subjects sub ON sub.id = es.subject_id
                     WHERE es.exam_id = r.exam_id AND m.student_id = r.student_id
                  ), '[]'::jsonb) AS subjects
             FROM exam_results r
             JOIN exams e ON e.id = r.exam_id
            WHERE r.student_id = $1
            ORDER BY r.published_at DESC NULLS LAST, e.starts_on DESC`,
          [studentId]
        );
        return r.rows;
      }
    );
    json(res, 200, {
      studentId,
      results: rows.map((r) => ({
        examId: r.exam_id,
        examNameBn: r.exam_name_bn,
        examType: r.exam_type,
        totalMarks: r.total_marks,
        totalMax: r.total_max,
        percentage: r.percentage,
        gpa: r.gpa,
        letterGrade: r.letter_grade,
        subjectsFailed: r.subjects_failed,
        isPass: r.is_pass,
        rankInSection: r.rank_in_section,
        publishedAt: r.published_at,
        subjects: r.subjects
      }))
    }, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error("[results] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/academics-svc/api/assignments.ts
var UUID_RE9 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var GradeConflict = class extends Error {
  detail;
  constructor(detail) {
    super("this submission was graded by someone else while you were working");
    this.detail = detail;
  }
};
async function handler10(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  try {
    const claims = await authenticate(req);
    const db = await sharedDb();
    const ctx = { tenantId: claims.tid, userId: claims.sub, role: claims.role };
    if (req.method === "POST") {
      requireStaff(claims);
      const body = await readJson(req);
      if (body.submissionId) {
        if (!UUID_RE9.test(body.submissionId)) {
          throw new HttpError(400, "submissionId must be a valid uuid", "invalid_submission_id");
        }
        const marks = Number(body.marksAwarded);
        if (!Number.isFinite(marks) || marks < 0) {
          throw new HttpError(400, "marksAwarded must be a non-negative number", "invalid_marks");
        }
        const rowVersion = Number(body.rowVersion);
        if (!Number.isInteger(rowVersion) || rowVersion < 1) {
          throw new HttpError(
            400,
            "rowVersion is required \u2014 re-read the submission and send the version you graded",
            "row_version_required"
          );
        }
        const graded = await db.withTenant(ctx, async (client) => {
          const r = await client.query(
            `UPDATE assignment_submissions s
                SET marks_awarded = $2, feedback_bn = $3,
                    graded_by = $4, graded_at = now(),
                    row_version = s.row_version + 1
              FROM assignments a
             WHERE s.id = $1
               AND a.id = s.assignment_id
               AND s.row_version = $5
               AND ($2::numeric <= COALESCE(a.max_marks, $2::numeric))
             RETURNING s.id, s.row_version`,
            [body.submissionId, marks, body.feedbackBn ?? null, claims.sub, rowVersion]
          );
          if (r.rowCount === 0) {
            const cur = await client.query(
              `SELECT s.row_version, s.marks_awarded::text, s.feedback_bn,
                      s.graded_at::text, g.full_name_bn AS grader_name,
                      a.max_marks::text
                 FROM assignment_submissions s
                 JOIN assignments a ON a.id = s.assignment_id
                 LEFT JOIN users g ON g.id = s.graded_by
                WHERE s.id = $1`,
              [body.submissionId]
            );
            const row = cur.rows[0];
            if (!row) {
              throw new HttpError(404, "submission not found", "submission_not_found");
            }
            if (row.max_marks !== null && marks > Number(row.max_marks)) {
              throw new HttpError(
                422,
                `marksAwarded exceeds the assignment maximum of ${row.max_marks}`,
                "marks_exceed_max"
              );
            }
            throw new GradeConflict({
              submissionId: body.submissionId,
              expectedRowVersion: rowVersion,
              currentRowVersion: row.row_version,
              yours: { marksAwarded: marks, feedbackBn: body.feedbackBn ?? null },
              theirs: {
                marksAwarded: row.marks_awarded,
                feedbackBn: row.feedback_bn,
                gradedAt: row.graded_at,
                gradedByName: row.grader_name
              }
            });
          }
          return r.rows[0];
        });
        json(res, 200, {
          ok: true,
          submissionId: graded.id,
          // Echoed so a grader can correct a mark twice in a row without
          // re-reading the list in between.
          rowVersion: graded.row_version
        }, cors);
        return;
      }
      const sectionId2 = body.sectionId ?? "";
      const subjectId = body.subjectId ?? "";
      const academicYearId = body.academicYearId ?? "";
      const titleBn = (body.titleBn ?? "").trim();
      const dueAt = body.dueAt ?? "";
      if (!UUID_RE9.test(sectionId2)) throw new HttpError(400, "sectionId must be a valid uuid", "invalid_section_id");
      if (!UUID_RE9.test(subjectId)) throw new HttpError(400, "subjectId must be a valid uuid", "invalid_subject_id");
      if (!UUID_RE9.test(academicYearId)) throw new HttpError(400, "academicYearId must be a valid uuid", "invalid_year_id");
      if (!titleBn) throw new HttpError(400, "titleBn is required", "title_required");
      if (!Number.isFinite(Date.parse(dueAt))) throw new HttpError(400, "dueAt must be ISO 8601", "invalid_due_at");
      if (Date.parse(dueAt) <= Date.now()) {
        throw new HttpError(400, "dueAt must be in the future", "due_in_past");
      }
      const created = await db.withTenant(ctx, async (client) => {
        const r = await client.query(
          `INSERT INTO assignments
             (tenant_id, section_id, subject_id, academic_year_id, lesson_id,
              title_bn, instructions_bn, max_marks, due_at, allows_late,
              created_by, status)
           VALUES (app.current_tenant(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
           RETURNING id`,
          [
            sectionId2,
            subjectId,
            academicYearId,
            body.lessonId && UUID_RE9.test(body.lessonId) ? body.lessonId : null,
            titleBn,
            body.instructionsBn ?? null,
            body.maxMarks ?? null,
            dueAt,
            body.allowsLate ?? true,
            claims.sub,
            body.status === "draft" ? "draft" : "open"
          ]
        );
        return r.rows[0].id;
      });
      json(res, 200, { ok: true, assignmentId: created }, cors);
      return;
    }
    if (req.method !== "GET") {
      json(res, 405, { error: "method_not_allowed" }, cors);
      return;
    }
    const assignmentId = query(req).get("assignmentId") ?? "";
    if (assignmentId) {
      if (!UUID_RE9.test(assignmentId)) {
        throw new HttpError(400, "assignmentId must be a valid uuid", "invalid_assignment_id");
      }
      const detail = await db.withTenant(ctx, async (client) => {
        const a = await client.query(
          `SELECT a.id, a.title_bn, a.instructions_bn, a.max_marks::text,
                  a.due_at::text, a.allows_late, a.status,
                  sub.name_bn AS subject_bn, sec.name AS section_name
             FROM assignments a
             JOIN subjects sub ON sub.id = a.subject_id
             JOIN sections sec ON sec.id = a.section_id
            WHERE a.id = $1`,
          [assignmentId]
        );
        if (a.rowCount === 0) throw new HttpError(404, "assignment not found", "assignment_not_found");
        const subs = await client.query(
          `SELECT s.id, s.student_id, u.full_name_bn, e.roll_no,
                  s.body_bn, s.submitted_at::text, s.is_late,
                  s.marks_awarded::text, s.feedback_bn, s.graded_at::text,
                  s.row_version, g.full_name_bn AS grader_name
             FROM assignment_submissions s
             JOIN users u ON u.id = s.student_id
             LEFT JOIN users g ON g.id = s.graded_by
             LEFT JOIN enrolments e
               ON e.student_id = s.student_id AND e.status = 'active'
            WHERE s.assignment_id = $1
            ORDER BY e.roll_no NULLS LAST, s.submitted_at`,
          [assignmentId]
        );
        const row = a.rows[0];
        return {
          assignment: {
            id: row.id,
            titleBn: row.title_bn,
            instructionsBn: row.instructions_bn,
            maxMarks: row.max_marks,
            dueAt: row.due_at,
            allowsLate: row.allows_late,
            status: row.status,
            subjectBn: row.subject_bn,
            sectionName: row.section_name
          },
          submissions: subs.rows.map((s) => ({
            id: s.id,
            studentId: s.student_id,
            fullNameBn: s.full_name_bn,
            rollNo: s.roll_no,
            bodyBn: s.body_bn,
            submittedAt: s.submitted_at,
            isLate: s.is_late,
            marksAwarded: s.marks_awarded,
            feedbackBn: s.feedback_bn,
            gradedAt: s.graded_at,
            gradedByName: s.grader_name,
            // F-103. The grading screen must send this back with the mark;
            // a client that never received it cannot grade at all, which is
            // the intended coupling.
            rowVersion: s.row_version
          }))
        };
      });
      json(res, 200, detail, cors);
      return;
    }
    const sectionId = query(req).get("sectionId") ?? "";
    if (sectionId && !UUID_RE9.test(sectionId)) {
      throw new HttpError(400, "sectionId must be a valid uuid", "invalid_section_id");
    }
    const list = await db.withTenant(ctx, async (client) => {
      const r = await client.query(
        `SELECT a.id, a.title_bn, a.due_at::text, a.status, a.max_marks::text,
                sub.name_bn AS subject_bn, sec.name AS section_name,
                (SELECT count(*)::int FROM assignment_submissions s
                  WHERE s.assignment_id = a.id) AS submission_count,
                (SELECT count(*)::int FROM assignment_submissions s
                  WHERE s.assignment_id = a.id AND s.graded_at IS NULL) AS ungraded_count,
                mine.submitted_at::text AS my_submitted_at,
                mine.marks_awarded::text AS my_marks,
                mine.graded_at::text AS my_graded_at
           FROM assignments a
           JOIN subjects sub ON sub.id = a.subject_id
           JOIN sections sec ON sec.id = a.section_id
           LEFT JOIN assignment_submissions mine
             ON mine.assignment_id = a.id AND mine.student_id = $2
          WHERE ($1::uuid IS NULL OR a.section_id = $1)
          ORDER BY a.due_at DESC
          LIMIT 100`,
        [sectionId || null, claims.sub]
      );
      return r.rows;
    });
    json(res, 200, {
      assignments: list.map((a) => ({
        id: a.id,
        titleBn: a.title_bn,
        dueAt: a.due_at,
        status: a.status,
        maxMarks: a.max_marks,
        subjectBn: a.subject_bn,
        sectionName: a.section_name,
        submissionCount: a.submission_count,
        ungradedCount: a.ungraded_count,
        mySubmission: a.my_submitted_at ? { submittedAt: a.my_submitted_at, marksAwarded: a.my_marks, gradedAt: a.my_graded_at } : null
      }))
    }, cors);
  } catch (err) {
    if (err instanceof GradeConflict) {
      json(res, 409, { error: "grade_conflict", message: err.message, conflict: err.detail }, cors);
      return;
    }
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error("[assignments] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/academics-svc/api/practice.ts
var UUID_RE10 = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
async function handler11(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "GET") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const claims = await authenticate(req);
    const lessonId = query(req).get("lessonId") ?? "";
    if (!UUID_RE10.test(lessonId)) {
      throw new HttpError(400, "lessonId must be a valid uuid", "invalid_lesson_id");
    }
    const db = await sharedDb();
    const result = await db.withTenant(
      { tenantId: claims.tid, userId: claims.sub, role: claims.role },
      async (client) => {
        const qs = await client.query(
          `SELECT q.id, q.question_no, q.kind::text, q.stem_bn, q.explanation_bn,
                  q.difficulty, q.numeric_answer::text, q.numeric_tolerance::text,
                  COALESCE((
                    SELECT jsonb_agg(jsonb_build_object(
                             'id', o.id, 'optionNo', o.option_no,
                             'textBn', o.text_bn, 'isCorrect', o.is_correct)
                           ORDER BY o.option_no)
                      FROM practice_options o WHERE o.question_id = q.id
                  ), '[]'::jsonb) AS options,
                  (SELECT count(*)::int FROM practice_attempts a
                    WHERE a.question_id = q.id AND a.student_id = $2) AS attempts,
                  (SELECT bool_or(a.is_correct) FROM practice_attempts a
                    WHERE a.question_id = q.id AND a.student_id = $2) AS best_correct,
                  (SELECT a.response_ms FROM practice_attempts a
                    WHERE a.question_id = q.id AND a.student_id = $2
                    ORDER BY a.attempt_no DESC LIMIT 1) AS last_response_ms
             FROM practice_questions q
            WHERE q.lesson_id = $1 AND q.is_published
            ORDER BY q.question_no`,
          [lessonId, claims.sub]
        );
        return qs.rows;
      }
    );
    json(res, 200, {
      lessonId,
      questions: result.map((q) => ({
        id: q.id,
        questionNo: q.question_no,
        kind: q.kind,
        stemBn: q.stem_bn,
        explanationBn: q.explanation_bn,
        difficulty: q.difficulty,
        numericAnswer: q.numeric_answer,
        numericTolerance: q.numeric_tolerance,
        options: q.options,
        myProgress: {
          attempts: q.attempts,
          solved: q.best_correct ?? false,
          lastResponseMs: q.last_response_ms
        }
      }))
    }, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error("[practice] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/academics-svc/api/next.ts
var MAX_SUGGESTIONS = 3;
async function handler12(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "GET") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  try {
    const claims = await authenticate(req);
    const db = await sharedDb();
    const suggestions = await db.withTenant(
      { tenantId: claims.tid, userId: claims.sub, role: claims.role },
      async (client) => {
        const out = [];
        const due = await client.query(
          `SELECT a.id, a.title_bn,
                  GREATEST(0, EXTRACT(day FROM a.due_at - now())::int) AS days
             FROM assignments a
            WHERE a.status = 'open'
              AND a.due_at > now()
              AND a.due_at < now() + interval '3 days'
              AND NOT EXISTS (
                    SELECT 1 FROM assignment_submissions s
                     WHERE s.assignment_id = a.id AND s.student_id = $1)
            ORDER BY a.due_at
            LIMIT 2`,
          [claims.sub]
        );
        for (const a of due.rows) {
          out.push({
            kind: "assignment",
            titleBn: a.title_bn,
            whyBn: a.days <= 0 ? "\u0986\u099C\u0987 \u099C\u09AE\u09BE \u09A6\u09BF\u09A4\u09C7 \u09B9\u09AC\u09C7" : `${a.days} \u09A6\u09BF\u09A8\u09C7\u09B0 \u09AE\u09A7\u09CD\u09AF\u09C7 \u099C\u09AE\u09BE \u09A6\u09BF\u09A4\u09C7 \u09B9\u09AC\u09C7`,
            route: "assignments",
            refId: a.id,
            urgency: "high"
          });
        }
        if (out.length < MAX_SUGGESTIONS) {
          const wrong = await client.query(
            `WITH latest AS (
               SELECT DISTINCT ON (a.question_id)
                      a.question_id, a.lesson_id, a.is_correct
                 FROM practice_attempts a
                WHERE a.student_id = $1
                ORDER BY a.question_id, a.attempt_no DESC
             )
             SELECT l.lesson_id, ls.title_bn, count(*)::int AS n
               FROM latest l
               JOIN lessons ls ON ls.id = l.lesson_id
              WHERE NOT l.is_correct
              GROUP BY l.lesson_id, ls.title_bn
              ORDER BY n DESC
              LIMIT 1`,
            [claims.sub]
          );
          for (const w of wrong.rows) {
            out.push({
              kind: "redo_practice",
              titleBn: w.title_bn,
              whyBn: `${w.n}\u099F\u09BF \u09AA\u09CD\u09B0\u09B6\u09CD\u09A8 \u098F\u0996\u09A8\u09CB \u09AD\u09C1\u09B2 \u0986\u099B\u09C7 \u2014 \u0986\u09AC\u09BE\u09B0 \u099A\u09C7\u09B7\u09CD\u099F\u09BE \u0995\u09B0\u09CB`,
              route: "learn",
              refId: w.lesson_id,
              urgency: "medium"
            });
          }
        }
        if (out.length < MAX_SUGGESTIONS) {
          const cont = await client.query(
            `SELECT l.id AS lesson_id, l.title_bn, c.name_bn AS chapter_bn
               FROM lessons l
               JOIN chapters c ON c.id = l.chapter_id
              WHERE l.is_published
                -- chapter has at least one completed lesson (already begun)
                AND EXISTS (
                      SELECT 1 FROM lesson_progress p
                       JOIN lessons l2 ON l2.id = p.lesson_id
                      WHERE l2.chapter_id = c.id
                        AND p.student_id = $1 AND p.state = 'completed')
                -- but THIS lesson isn't done
                AND NOT EXISTS (
                      SELECT 1 FROM lesson_progress p2
                       WHERE p2.lesson_id = l.id
                         AND p2.student_id = $1 AND p2.state = 'completed')
              ORDER BY c.chapter_no, l.lesson_no
              LIMIT 1`,
            [claims.sub]
          );
          for (const c of cont.rows) {
            out.push({
              kind: "continue_lesson",
              titleBn: c.title_bn,
              whyBn: `${c.chapter_bn} \u0985\u09A7\u09CD\u09AF\u09BE\u09AF\u09BC\u099F\u09BF \u09B6\u09C7\u09B7 \u0995\u09B0\u09CB`,
              route: "learn",
              refId: c.lesson_id,
              urgency: "medium"
            });
          }
        }
        if (out.length < MAX_SUGGESTIONS) {
          const fresh = await client.query(
            `SELECT c.id, c.name_bn, s.name_bn AS subject_bn
               FROM chapters c
               JOIN subjects s ON s.id = c.subject_id
              WHERE c.is_published
                -- untouched
                AND NOT EXISTS (
                      SELECT 1 FROM lesson_progress p
                       JOIN lessons l ON l.id = p.lesson_id
                      WHERE l.chapter_id = c.id AND p.student_id = $1)
                -- prerequisite satisfied (or none)
                AND (c.prerequisite_chapter_id IS NULL OR EXISTS (
                      SELECT 1 FROM lesson_progress p2
                       JOIN lessons l2 ON l2.id = p2.lesson_id
                      WHERE l2.chapter_id = c.prerequisite_chapter_id
                        AND p2.student_id = $1 AND p2.state = 'completed'))
              ORDER BY c.chapter_no
              LIMIT 1`,
            [claims.sub]
          );
          for (const f of fresh.rows) {
            out.push({
              kind: "new_chapter",
              titleBn: f.name_bn,
              whyBn: `${f.subject_bn} \u2014 \u09A8\u09A4\u09C1\u09A8 \u0985\u09A7\u09CD\u09AF\u09BE\u09AF\u09BC \u09B6\u09C1\u09B0\u09C1 \u0995\u09B0\u09BE\u09B0 \u099C\u09A8\u09CD\u09AF \u09AA\u09CD\u09B0\u09B8\u09CD\u09A4\u09C1\u09A4`,
              route: "learn",
              refId: f.id,
              urgency: "low"
            });
          }
        }
        return out.slice(0, MAX_SUGGESTIONS);
      }
    );
    json(res, 200, { suggestions }, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error("[next] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}

// services/academics-svc/api/index.ts
var ROUTES = {
  sections: handler,
  roster: handler2,
  exams: handler3,
  marks: handler4,
  publish: handler5,
  scripts: handler6,
  chapters: handler7,
  lessons: handler8,
  results: handler9,
  assignments: handler10,
  practice: handler11,
  next: handler12
};
async function handler13(req, res) {
  const path = new URL(req.url ?? "/", "http://internal").pathname;
  const sub = path.split("/").filter(Boolean).pop() ?? "";
  const route = ROUTES[sub];
  if (!route) {
    json(res, 404, { error: "not_found" }, corsHeaders());
    return;
  }
  if (req.method !== "OPTIONS") {
    const cls = req.method === "GET" ? "read" : "mutation";
    if (!await enforceRateLimit(req, res, corsHeaders(), cls)) return;
  }
  return route(req, res);
}
export {
  handler13 as default
};
