// GENERATED by scripts/build.mjs from services/sync-svc/api/index.ts — do not edit directly.

// packages/server-core/src/http.ts
function allowedOrigins(env = process.env) {
  return (env.ALLOWED_ORIGINS ?? "").split(",").map((o) => o.trim()).filter((o) => o.length > 0);
}
function corsOriginFor(requestOrigin, env = process.env) {
  const allow = allowedOrigins(env);
  if (allow.length === 0) return { origin: "*", vary: false };
  if (requestOrigin && allow.includes(requestOrigin)) {
    return { origin: requestOrigin, vary: true };
  }
  return { origin: allow[0], vary: true };
}
function corsHeaders(extraHeaders = [], methods = "GET, POST, OPTIONS", requestOrigin) {
  const { origin, vary } = corsOriginFor(requestOrigin);
  return {
    ...vary ? { Vary: "Origin" } : {},
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": methods,
    "Access-Control-Allow-Headers": [
      "Content-Type",
      "Authorization",
      "X-Tenant-ID",
      "X-User-ID",
      "X-Role",
      ...extraHeaders
    ].join(", ")
  };
}
function json(res, code, body, cors) {
  const payload = JSON.stringify(body);
  res.writeHead(code, { ...cors, "Content-Type": "application/json" });
  res.end(payload);
}

// packages/server-core/src/db.ts
import pg from "pg";
function createDb(connectionString, opts = {}) {
  const pool = new pg.Pool({
    connectionString,
    max: 10,
    idleTimeoutMillis: 3e4,
    statement_timeout: 15e3,
    ...opts
  });
  async function inTx(setup, fn) {
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      await setup(client);
      const out = await fn(client);
      await client.query("COMMIT");
      return out;
    } catch (err) {
      try {
        await client.query("ROLLBACK");
      } catch {
      }
      throw err;
    } finally {
      client.release();
    }
  }
  return {
    pool,
    withTenant(ctx, fn) {
      if (!ctx.tenantId) throw new Error("tenant context required");
      return inTx(async (c) => {
        await c.query(
          `SELECT set_config('app.tenant_id', $1, true),
                  set_config('app.user_id',   $2, true),
                  set_config('app.role',      $3, true)`,
          [ctx.tenantId, ctx.userId, ctx.role]
        );
      }, fn);
    },
    withSystemRole(role, fn) {
      return inTx(async (c) => {
        await c.query(`SELECT set_config('app.role', $1, true)`, [role]);
      }, fn);
    },
    end: () => pool.end()
  };
}
async function assertRlsEnforced(db) {
  const { rows } = await db.pool.query(
    `SELECT rolname, rolbypassrls, rolsuper FROM pg_roles WHERE rolname = current_user`
  );
  const me = rows[0];
  if (!me) throw new Error("cannot resolve current_user");
  if (me.rolbypassrls || me.rolsuper) {
    throw new Error(
      `refusing to start: connected as "${me.rolname}" which has ${me.rolsuper ? "SUPERUSER" : "BYPASSRLS"} \u2014 RLS would not be enforced. Connect as the non-privileged runtime role instead.`
    );
  }
}
var _db = null;
async function sharedDb() {
  if (_db) return _db;
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL env var is not set");
  const db = createDb(url, { max: 5 });
  await assertRlsEnforced(db);
  _db = db;
  return db;
}

// packages/server-core/src/rate-limit.ts
var perHour = (n) => n / 3600;
var RATE_LIMITS = {
  // Hammering one phone with OTPs is the attack; 3/hour per phone stops it
  // dead. The IP allowance has to clear a whole school activating at once.
  otp_request: { ip: { capacity: 240, refill: perHour(240) }, identity: { capacity: 3, refill: perHour(3) } },
  // Verification is a guessing attack against a 6-digit code. identity-svc
  // already caps attempts per challenge; this bounds the outer loop of
  // requesting a fresh challenge and guessing again.
  otp_verify: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 10, refill: perHour(10) } },
  // Refresh and logout — authenticated, cheap, but part of the auth surface.
  auth: { ip: { capacity: 600, refill: perHour(600) } },
  // The only endpoint class with real per-request cost. Per-identity is the
  // spend control until F-1310's proper token metering lands.
  ai: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 30, refill: perHour(30) } },
  // Ordinary authenticated traffic. Sized for a school, not a person: a
  // sync/push after a day offline is one request, not many.
  mutation: { ip: { capacity: 900, refill: 15 } },
  read: { ip: { capacity: 1800, refill: 30 } },
  // Machine-to-machine: MFS webhooks, cron workers, ANS dispatch. Already
  // gated by signature or service key; this is a backstop against a loop.
  service: { ip: { capacity: 3e3, refill: 50 } }
};
function clientIp(req) {
  const xff = req.headers["x-forwarded-for"];
  const first = Array.isArray(xff) ? xff[0] : xff;
  const ip = first?.split(",")[0]?.trim() || req.headers["x-real-ip"]?.trim() || req.socket?.remoteAddress || "unknown";
  return ip.slice(0, 64);
}
function buildBuckets(cls, ip, identity) {
  const policy = RATE_LIMITS[cls];
  const buckets = [];
  if (ip) {
    buckets.push({ key: `${cls}:ip:${ip}`, capacity: policy.ip.capacity, refill: policy.ip.refill });
  }
  if (policy.identity && identity) {
    buckets.push({
      key: `${cls}:id:${identity}`,
      capacity: policy.identity.capacity,
      refill: policy.identity.refill
    });
  }
  return buckets;
}
async function consumeRateLimit(cls, ip, identity) {
  const buckets = buildBuckets(cls, ip, identity);
  if (buckets.length === 0) return { allowed: true, retryAfterSec: 0 };
  try {
    const db = await sharedDb();
    const { rows } = await db.pool.query("SELECT * FROM app.rate_limit_consume($1::jsonb)", [JSON.stringify(buckets)]);
    const row = rows[0];
    if (!row) return { allowed: true, retryAfterSec: 0 };
    if (!row.allowed) {
      console.warn(`[rate-limit] refused ${cls}, bucket=${row.blocked_key}, retry=${row.retry_after_sec}s`);
    }
    return { allowed: row.allowed, retryAfterSec: row.retry_after_sec };
  } catch (err) {
    console.error("[rate-limit] check failed, allowing request:", err);
    return { allowed: true, retryAfterSec: 0 };
  }
}
async function enforceRateLimit(req, res, cors, cls, identity) {
  const verdict = await consumeRateLimit(cls, clientIp(req), identity);
  return sendIfRefused(res, cors, verdict);
}
function sendIfRefused(res, cors, verdict) {
  if (verdict.allowed) return true;
  json(
    res,
    429,
    {
      error: "rate_limited",
      message: "too many requests \u2014 please wait before trying again",
      retryAfterSec: verdict.retryAfterSec
    },
    { ...cors, "Retry-After": String(verdict.retryAfterSec) }
  );
  return false;
}

// services/sync-svc/src/db.ts
import pg2 from "pg";
function createDb2(connectionString, opts = {}) {
  const pool = new pg2.Pool({
    connectionString,
    max: 10,
    idleTimeoutMillis: 3e4,
    // A 2G client can hang a request; do not let it hold a pooled connection.
    statement_timeout: 15e3,
    ...opts
  });
  async function inTx(setup, fn) {
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      await setup(client);
      const out = await fn(client);
      await client.query("COMMIT");
      return out;
    } catch (err) {
      try {
        await client.query("ROLLBACK");
      } catch {
      }
      throw err;
    } finally {
      client.release();
    }
  }
  return {
    pool,
    withTenant(ctx, fn) {
      if (!ctx.tenantId) throw new Error("tenant context required");
      return inTx(async (c) => {
        await c.query(
          `SELECT set_config('app.tenant_id', $1, true),
                  set_config('app.user_id',   $2, true),
                  set_config('app.role',      $3, true)`,
          [ctx.tenantId, ctx.userId, ctx.role]
        );
      }, fn);
    },
    withSystemRole(role, fn) {
      return inTx(async (c) => {
        await c.query(`SELECT set_config('app.role', $1, true)`, [role]);
      }, fn);
    },
    end: () => pool.end()
  };
}
async function assertRlsEnforced2(db) {
  const { rows } = await db.pool.query(
    `SELECT rolname, rolbypassrls, rolsuper FROM pg_roles WHERE rolname = current_user`
  );
  const me = rows[0];
  if (!me) throw new Error("cannot resolve current_user");
  if (me.rolbypassrls || me.rolsuper) {
    throw new Error(
      `refusing to start: connected as "${me.rolname}" which has ${me.rolsuper ? "SUPERUSER" : "BYPASSRLS"} \u2014 RLS would not be enforced. Connect as the non-privileged runtime role instead.`
    );
  }
}

// services/sync-svc/src/appliers.ts
var applied = (opId, rowVersion, sideEffects) => ({
  opId,
  status: "applied",
  rowVersion,
  ...sideEffects ? { sideEffects } : {}
});
var conflict = (opId, reason, serverValue, clientValue) => ({
  opId,
  status: "conflict",
  conflict: { reason, serverValue, clientValue }
});
var rejected = (opId, code, retryable = false, message2) => ({
  opId,
  status: "rejected",
  error: { code, retryable, message: message2 }
});
var applyAttendanceSession = async (c, op) => {
  const p = op.payload;
  if (!p?.sessionId || !p.sectionId || !p.takenOn || !Array.isArray(p.records)) {
    return rejected(op.opId, "MALFORMED_PAYLOAD");
  }
  const sec = await c.query(`SELECT id FROM sections WHERE id = $1`, [p.sectionId]);
  if (sec.rowCount === 0) return rejected(op.opId, "SECTION_NOT_ASSIGNED");
  const mode = p.mode ?? "section_daily";
  const session = await c.query(
    `INSERT INTO attendance_sessions
       (id, tenant_id, section_id, academic_year_id, routine_slot_id, subject_id,
        taken_on, period_no, mode, taken_by, taken_at, device_id)
     VALUES ($1, app.current_tenant(), $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
     ON CONFLICT (tenant_id, section_id, taken_on, period_no, mode) DO UPDATE
       SET taken_by = EXCLUDED.taken_by,
           taken_at = EXCLUDED.taken_at,
           row_version = attendance_sessions.row_version + 1
     RETURNING id, is_locked, row_version`,
    [
      p.sessionId,
      p.sectionId,
      p.academicYearId,
      p.routineSlotId ?? null,
      p.subjectId ?? null,
      p.takenOn,
      p.periodNo ?? null,
      mode,
      op.actorId,
      op.occurredAt,
      op.deviceId
    ]
  );
  const s = session.rows[0];
  if (s.is_locked) {
    return conflict(op.opId, "session_locked", { sessionId: s.id, isLocked: true }, p);
  }
  let present = 0;
  let absent = 0;
  let late = 0;
  for (const r of p.records) {
    if (r.status === "present") present++;
    else if (r.status === "absent") absent++;
    else if (r.status === "late") late++;
    await c.query(
      `INSERT INTO attendance_records
         (tenant_id, session_id, student_id, section_id, taken_on, status,
          minutes_late, remark, marked_by, marked_at, op_id, device_id, sms_state)
       VALUES (app.current_tenant(), $1, $2, $3, $4, $5::attendance_status, $6, $7, $8, $9, $10, $11,
               -- $5 is referenced twice: once as the enum column and once in a
               -- text CASE. Without the casts Postgres deduces two different
               -- types for the same parameter and fails with 42P08.
               CASE WHEN $5::attendance_status IN ('absent','late')
                    THEN 'queued' ELSE 'not_applicable' END)
       ON CONFLICT (tenant_id, taken_on, session_id, student_id) DO UPDATE
         SET status = EXCLUDED.status,
             minutes_late = EXCLUDED.minutes_late,
             remark = EXCLUDED.remark,
             marked_at = EXCLUDED.marked_at,
             row_version = attendance_records.row_version + 1`,
      [
        s.id,
        r.studentId,
        p.sectionId,
        p.takenOn,
        r.status,
        r.minutesLate ?? null,
        r.remark ?? null,
        op.actorId,
        op.occurredAt,
        op.opId,
        op.deviceId
      ]
    );
  }
  await c.query(
    `UPDATE attendance_sessions
        SET present_count = $2, absent_count = $3, late_count = $4
      WHERE id = $1`,
    [s.id, present, absent, late]
  );
  return applied(op.opId, s.row_version, { records: p.records.length, smsQueued: absent + late });
};
var applyExamMark = async (c, op) => {
  const p = op.payload;
  if (!p?.examSubjectId || !p.studentId) return rejected(op.opId, "MALFORMED_PAYLOAD");
  const es = await c.query(
    `SELECT es.id, es.marking_locked, e.status AS exam_status
       FROM exam_subjects es JOIN exams e ON e.id = es.exam_id
      WHERE es.id = $1`,
    [p.examSubjectId]
  );
  if (es.rowCount === 0) return rejected(op.opId, "EXAM_SUBJECT_NOT_FOUND");
  const row = es.rows[0];
  if (row.exam_status === "published" || row.exam_status === "locked" || row.marking_locked) {
    const cur = await c.query(
      `SELECT cq_marks, mcq_marks, practical_marks, ca_marks, total_marks, grade_letter
         FROM exam_marks WHERE exam_subject_id = $1 AND student_id = $2`,
      [p.examSubjectId, p.studentId]
    );
    return conflict(op.opId, "published_marks_immutable", cur.rows[0] ?? null, p);
  }
  if (typeof op.baseVersion === "number") {
    const cur = await c.query(
      `SELECT row_version FROM exam_marks WHERE exam_subject_id = $1 AND student_id = $2`,
      [p.examSubjectId, p.studentId]
    );
    if (cur.rowCount && cur.rows[0].row_version !== op.baseVersion) {
      const full = await c.query(
        `SELECT cq_marks, mcq_marks, practical_marks, ca_marks, row_version
           FROM exam_marks WHERE exam_subject_id = $1 AND student_id = $2`,
        [p.examSubjectId, p.studentId]
      );
      return conflict(op.opId, "version_conflict", full.rows[0], p);
    }
  }
  const res = await c.query(
    `INSERT INTO exam_marks
       (tenant_id, exam_subject_id, student_id, academic_year_id,
        cq_marks, mcq_marks, practical_marks, ca_marks, is_absent, entered_by, op_id)
     VALUES (app.current_tenant(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
     ON CONFLICT (tenant_id, exam_subject_id, student_id) DO UPDATE
       SET cq_marks = EXCLUDED.cq_marks,
           mcq_marks = EXCLUDED.mcq_marks,
           practical_marks = EXCLUDED.practical_marks,
           ca_marks = EXCLUDED.ca_marks,
           is_absent = EXCLUDED.is_absent,
           entered_at = now(),
           row_version = exam_marks.row_version + 1
     RETURNING row_version`,
    [
      p.examSubjectId,
      p.studentId,
      p.academicYearId,
      p.cqMarks ?? null,
      p.mcqMarks ?? null,
      p.practicalMarks ?? null,
      p.caMarks ?? null,
      p.isAbsent ?? false,
      op.actorId,
      op.opId
    ]
  );
  return applied(op.opId, res.rows[0].row_version);
};
var applyClassDeliveryLog = async (c, op) => {
  const p = op.payload;
  if (!p?.slotId || !p.deliveredOn) return rejected(op.opId, "MALFORMED_PAYLOAD");
  const slot = await c.query(`SELECT id FROM routine_slots WHERE id = $1`, [p.slotId]);
  if (slot.rowCount === 0) return rejected(op.opId, "ROUTINE_SLOT_NOT_FOUND");
  await c.query(
    `INSERT INTO class_delivery_log
       (id, tenant_id, slot_id, delivered_on, teacher_id, was_held, not_held_reason,
        chapter_no, topic_covered, homework_bn, logged_at, op_id)
     VALUES ($1, app.current_tenant(), $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
     ON CONFLICT (tenant_id, slot_id, delivered_on) DO UPDATE
       SET was_held = EXCLUDED.was_held,
           not_held_reason = EXCLUDED.not_held_reason,
           chapter_no = EXCLUDED.chapter_no,
           topic_covered = EXCLUDED.topic_covered,
           homework_bn = EXCLUDED.homework_bn,
           logged_at = EXCLUDED.logged_at`,
    [
      op.opId,
      p.slotId,
      p.deliveredOn,
      op.actorId,
      p.wasHeld,
      p.notHeldReason ?? null,
      p.chapterNo ?? null,
      p.topicCovered ?? null,
      p.homeworkBn ?? null,
      op.occurredAt,
      op.opId
    ]
  );
  return applied(op.opId);
};
var MAX_SECONDS = 14400;
var applyTopicProgress = async (c, op) => {
  const p = op.payload;
  const topicId = p?.topicId ?? p?.lessonId;
  if (!topicId) return rejected(op.opId, "MALFORMED_PAYLOAD");
  const topic = await c.query(`SELECT id FROM topics WHERE id = $1`, [topicId]);
  if (topic.rowCount === 0) return rejected(op.opId, "TOPIC_NOT_FOUND");
  const state = p.state === "completed" ? "completed" : "started";
  const seconds = Math.min(Math.max(Math.round(p.secondsSpent ?? 0), 0), MAX_SECONDS);
  await c.query(
    `INSERT INTO topic_progress
       (id, tenant_id, topic_id, student_id, state, seconds_spent, last_block_no,
        started_at, completed_at)
     VALUES ($1, app.current_tenant(), $2, $3, $4, $5, $6, now(),
             CASE WHEN $4 = 'completed' THEN now() ELSE NULL END)
     ON CONFLICT (tenant_id, topic_id, student_id) DO UPDATE
       SET state = CASE
             WHEN topic_progress.state = 'completed' THEN 'completed'
             ELSE EXCLUDED.state
           END,
           seconds_spent = LEAST(topic_progress.seconds_spent + EXCLUDED.seconds_spent, $7),
           last_block_no = GREATEST(
             COALESCE(topic_progress.last_block_no, 0),
             COALESCE(EXCLUDED.last_block_no, 0)
           ),
           completed_at = COALESCE(
             topic_progress.completed_at,
             CASE WHEN EXCLUDED.state = 'completed' THEN now() ELSE NULL END
           )`,
    [op.opId, p.topicId, op.actorId, state, seconds, p.lastBlockNo ?? null, MAX_SECONDS]
  );
  return applied(op.opId);
};
var SUBMISSION_MEDIA_ENABLED = false;
var MEDIA_KINDS = /* @__PURE__ */ new Set(["photo", "voice"]);
var MAX_MEDIA_BYTES = 262144;
var MAX_VOICE_MS = 9e4;
var HEX64 = /^[0-9a-f]{64}$/i;
var applyAssignmentSubmission = async (c, op) => {
  const p = op.payload;
  if (!p?.assignmentId) return rejected(op.opId, "MALFORMED_PAYLOAD");
  if (!p.bodyBn && !p.mediaKey) return rejected(op.opId, "EMPTY_SUBMISSION");
  if (p.mediaKey || p.mediaKind) {
    if (!SUBMISSION_MEDIA_ENABLED) {
      return rejected(
        op.opId,
        "MEDIA_STORAGE_UNCONFIGURED",
        false,
        "photo and voice submission is not enabled for this school yet"
      );
    }
    if (!p.mediaKey || !p.mediaKind) return rejected(op.opId, "MEDIA_INCOMPLETE");
    if (!MEDIA_KINDS.has(p.mediaKind)) return rejected(op.opId, "MEDIA_KIND_UNKNOWN");
    const bytes = Number(p.mediaBytes);
    if (!Number.isInteger(bytes) || bytes <= 0 || bytes > MAX_MEDIA_BYTES) {
      return rejected(
        op.opId,
        "MEDIA_TOO_LARGE",
        false,
        "compress before uploading \u2014 the ceiling is 250 KB"
      );
    }
    if (p.mediaSha256 && !HEX64.test(p.mediaSha256)) return rejected(op.opId, "MEDIA_HASH_INVALID");
    if (p.mediaKind === "photo" && p.mediaDurationMs != null) {
      return rejected(op.opId, "MEDIA_KIND_MISMATCH");
    }
    if (p.mediaKind === "voice") {
      const ms = Number(p.mediaDurationMs);
      if (!Number.isInteger(ms) || ms <= 0 || ms > MAX_VOICE_MS) {
        return rejected(op.opId, "MEDIA_TOO_LONG", false, "a spoken answer may run up to 90 seconds");
      }
    }
  }
  const a = await c.query(
    `SELECT status, due_at::text, allows_late FROM assignments WHERE id = $1`,
    [p.assignmentId]
  );
  if (a.rowCount === 0) return rejected(op.opId, "ASSIGNMENT_NOT_FOUND");
  if (a.rows[0].status === "draft") return rejected(op.opId, "ASSIGNMENT_NOT_OPEN");
  const existing = await c.query(
    `SELECT graded_at::text, body_bn FROM assignment_submissions
      WHERE assignment_id = $1 AND student_id = $2`,
    [p.assignmentId, op.actorId]
  );
  if (existing.rows[0]?.graded_at) {
    return conflict(op.opId, "already_graded", existing.rows[0], p);
  }
  try {
    const res = await c.query(
      `INSERT INTO assignment_submissions
         (id, tenant_id, assignment_id, student_id, body_bn,
          media_key, media_kind, media_bytes, media_duration_ms, media_sha256, submitted_at)
       VALUES ($1, app.current_tenant(), $2, $3, $4, $5, $6, $7, $8, decode($9, 'hex'), now())
       ON CONFLICT (tenant_id, assignment_id, student_id) DO UPDATE
         SET body_bn = EXCLUDED.body_bn,
             -- Media is kept when a resubmission carries none: a student
             -- fixing a typo in their written answer has not withdrawn the
             -- photo they attached. All five media columns move together,
             -- or the row would claim a kind for a key it no longer has.
             media_key         = COALESCE(EXCLUDED.media_key, assignment_submissions.media_key),
             media_kind        = COALESCE(EXCLUDED.media_kind, assignment_submissions.media_kind),
             media_bytes       = COALESCE(EXCLUDED.media_bytes, assignment_submissions.media_bytes),
             media_duration_ms = COALESCE(EXCLUDED.media_duration_ms, assignment_submissions.media_duration_ms),
             media_sha256      = COALESCE(EXCLUDED.media_sha256, assignment_submissions.media_sha256),
             submitted_at = now(),
             row_version = assignment_submissions.row_version + 1
       RETURNING is_late, row_version`,
      [
        op.opId,
        p.assignmentId,
        op.actorId,
        p.bodyBn ?? null,
        p.mediaKey ?? null,
        p.mediaKind ?? null,
        p.mediaBytes ?? null,
        p.mediaDurationMs ?? null,
        p.mediaSha256 ?? null
      ]
    );
    return applied(op.opId, res.rows[0].row_version);
  } catch (err) {
    if (err.code === "23514") {
      return rejected(op.opId, "PAST_DUE", false, "this assignment no longer accepts submissions");
    }
    throw err;
  }
};
var MAX_RESPONSE_MS = 6e5;
var applyPracticeAttempt = async (c, op) => {
  const p = op.payload;
  if (!p?.questionId) return rejected(op.opId, "MALFORMED_PAYLOAD");
  const q = await c.query(
    `SELECT topic_id, kind::text, numeric_answer::text, numeric_tolerance::text, text_answer_bn
       FROM practice_questions WHERE id = $1`,
    [p.questionId]
  );
  if (q.rowCount === 0) return rejected(op.opId, "QUESTION_NOT_FOUND");
  const question = q.rows[0];
  let isCorrect = false;
  switch (question.kind) {
    case "mcq":
    case "true_false": {
      if (!p.selectedOptionId) return rejected(op.opId, "NO_OPTION_SELECTED");
      const opt = await c.query(
        `SELECT is_correct FROM practice_options WHERE id = $1 AND question_id = $2`,
        [p.selectedOptionId, p.questionId]
      );
      if (opt.rowCount === 0) return rejected(op.opId, "OPTION_NOT_FOUND");
      isCorrect = opt.rows[0].is_correct;
      break;
    }
    case "numeric": {
      const given = Number(p.answerNumeric);
      if (!Number.isFinite(given)) return rejected(op.opId, "NO_NUMERIC_ANSWER");
      const expected = Number(question.numeric_answer);
      const tolerance = Number(question.numeric_tolerance ?? 0);
      isCorrect = Math.abs(given - expected) <= tolerance;
      break;
    }
    default: {
      const given = (p.answerText ?? "").trim().toLowerCase();
      if (!given) return rejected(op.opId, "NO_ANSWER_TEXT");
      isCorrect = given === (question.text_answer_bn ?? "").trim().toLowerCase();
      break;
    }
  }
  const responseMs = Math.min(Math.max(Math.round(p.responseMs ?? 0), 0), MAX_RESPONSE_MS);
  const attemptNo = Math.max(1, Math.round(p.attemptNo ?? 1));
  await c.query(
    `INSERT INTO practice_attempts
       (id, tenant_id, question_id, student_id, topic_id, attempt_no,
        selected_option_id, answer_text, answer_numeric, is_correct, response_ms)
     VALUES ($1, app.current_tenant(), $2, $3, $4, $5, $6, $7, $8, $9, $10)
     ON CONFLICT (tenant_id, question_id, student_id, attempt_no) DO NOTHING`,
    [
      op.opId,
      p.questionId,
      op.actorId,
      question.topic_id,
      attemptNo,
      p.selectedOptionId ?? null,
      p.answerText ?? null,
      p.answerNumeric ?? null,
      isCorrect,
      responseMs
    ]
  );
  return applied(op.opId, void 0, { correct: isCorrect ? 1 : 0 });
};
var APPLIERS = {
  attendance_session: applyAttendanceSession,
  exam_mark: applyExamMark,
  class_delivery_log: applyClassDeliveryLog,
  topic_progress: applyTopicProgress,
  lesson_progress: applyTopicProgress,
  // pre-M6 alias — see the note above
  assignment_submission: applyAssignmentSubmission,
  practice_attempt: applyPracticeAttempt
};

// services/sync-svc/src/push.ts
var SyncPushHandler = class {
  db;
  maxOps;
  now;
  constructor(db, opts = {}) {
    this.db = db;
    this.maxOps = opts.maxOps ?? 100;
    this.now = opts.now ?? Date.now;
  }
  async handle(req, ctx) {
    const serverNow = this.now();
    const results = [];
    const ops = (req.ops ?? []).slice(0, this.maxOps);
    ops.sort((a, b) => a.seq - b.seq);
    for (const op of ops) {
      results.push(await this.applyOne(op, ctx, req.deviceId));
    }
    return {
      serverTime: new Date(serverNow).toISOString(),
      clockSkewMs: this.estimateSkew(req.clientTime, serverNow),
      results
    };
  }
  /**
   * Client clock minus server clock. Cheap Android devices drift by minutes and
   * attendance conflict resolution compares client timestamps, so the client
   * re-stamps subsequent ops using this offset.
   */
  estimateSkew(clientTime, serverNow) {
    if (!clientTime) return void 0;
    const t = Date.parse(clientTime);
    return Number.isFinite(t) ? t - serverNow : void 0;
  }
  async applyOne(op, ctx, deviceId) {
    if (op.tenantId && op.tenantId !== ctx.tenantId) {
      return {
        opId: op.opId,
        status: "rejected",
        error: { code: "TENANT_MISMATCH", retryable: false }
      };
    }
    const applier = APPLIERS[op.entity];
    if (!applier) {
      return {
        opId: op.opId,
        status: "rejected",
        error: { code: "UNSUPPORTED_ENTITY", retryable: false, message: op.entity }
      };
    }
    try {
      return await this.db.withTenant(ctx, async (c) => {
        const claim = await c.query(
          `INSERT INTO sync_operations
             (op_id, tenant_id, device_id, actor_id, device_seq, entity, operation,
              occurred_at, result)
           VALUES ($1, app.current_tenant(), $2, $3, $4, $5, $6, $7, 'applied')
           ON CONFLICT (op_id) DO NOTHING
           RETURNING op_id`,
          [op.opId, deviceId, ctx.userId, op.seq, op.entity, op.operation, op.occurredAt]
        );
        if (claim.rowCount === 0) {
          const prior = await c.query(
            `SELECT result, conflict_detail FROM sync_operations WHERE op_id = $1`,
            [op.opId]
          );
          const r = prior.rows[0];
          if (r?.result === "conflict") {
            return {
              opId: op.opId,
              status: "conflict",
              conflict: r.conflict_detail ?? {
                reason: "previously_conflicted",
                serverValue: null,
                clientValue: op.payload
              }
            };
          }
          return { opId: op.opId, status: "duplicate" };
        }
        const result = await applier(c, op);
        await c.query(
          `UPDATE sync_operations
              SET result = $2, conflict_detail = $3
            WHERE op_id = $1`,
          [
            op.opId,
            result.status === "applied" ? "applied" : result.status === "conflict" ? "conflict" : "rejected",
            result.conflict ? JSON.stringify(result.conflict) : null
          ]
        );
        return result;
      });
    } catch (err) {
      const e = err;
      if (e.code === "23P01" || e.code === "23505") {
        return {
          opId: op.opId,
          status: "conflict",
          conflict: { reason: e.code === "23P01" ? "clash" : "duplicate_key", serverValue: null, clientValue: op.payload }
        };
      }
      if (e.code === "23503" || e.code === "23514" || e.code === "22P02") {
        return {
          opId: op.opId,
          status: "rejected",
          error: { code: "INVALID_REFERENCE", retryable: false, message: e.message }
        };
      }
      if (e.code === "42501") {
        return {
          opId: op.opId,
          status: "rejected",
          error: { code: "FORBIDDEN", retryable: false, message: e.message }
        };
      }
      return {
        opId: op.opId,
        status: "rejected",
        error: { code: e.code ?? "INTERNAL", retryable: true, message: e.message }
      };
    }
  }
};

// node_modules/jose/dist/node/esm/runtime/base64url.js
import { Buffer as Buffer2 } from "node:buffer";

// node_modules/jose/dist/node/esm/lib/buffer_utils.js
var encoder = new TextEncoder();
var decoder = new TextDecoder();
var MAX_INT32 = 2 ** 32;
function concat(...buffers) {
  const size = buffers.reduce((acc, { length }) => acc + length, 0);
  const buf = new Uint8Array(size);
  let i = 0;
  for (const buffer of buffers) {
    buf.set(buffer, i);
    i += buffer.length;
  }
  return buf;
}

// node_modules/jose/dist/node/esm/runtime/base64url.js
function normalize(input) {
  let encoded = input;
  if (encoded instanceof Uint8Array) {
    encoded = decoder.decode(encoded);
  }
  return encoded;
}
var decode = (input) => new Uint8Array(Buffer2.from(normalize(input), "base64url"));

// node_modules/jose/dist/node/esm/util/errors.js
var JOSEError = class extends Error {
  static code = "ERR_JOSE_GENERIC";
  code = "ERR_JOSE_GENERIC";
  constructor(message2, options) {
    super(message2, options);
    this.name = this.constructor.name;
    Error.captureStackTrace?.(this, this.constructor);
  }
};
var JWTClaimValidationFailed = class extends JOSEError {
  static code = "ERR_JWT_CLAIM_VALIDATION_FAILED";
  code = "ERR_JWT_CLAIM_VALIDATION_FAILED";
  claim;
  reason;
  payload;
  constructor(message2, payload, claim = "unspecified", reason = "unspecified") {
    super(message2, { cause: { claim, reason, payload } });
    this.claim = claim;
    this.reason = reason;
    this.payload = payload;
  }
};
var JWTExpired = class extends JOSEError {
  static code = "ERR_JWT_EXPIRED";
  code = "ERR_JWT_EXPIRED";
  claim;
  reason;
  payload;
  constructor(message2, payload, claim = "unspecified", reason = "unspecified") {
    super(message2, { cause: { claim, reason, payload } });
    this.claim = claim;
    this.reason = reason;
    this.payload = payload;
  }
};
var JOSEAlgNotAllowed = class extends JOSEError {
  static code = "ERR_JOSE_ALG_NOT_ALLOWED";
  code = "ERR_JOSE_ALG_NOT_ALLOWED";
};
var JOSENotSupported = class extends JOSEError {
  static code = "ERR_JOSE_NOT_SUPPORTED";
  code = "ERR_JOSE_NOT_SUPPORTED";
};
var JWSInvalid = class extends JOSEError {
  static code = "ERR_JWS_INVALID";
  code = "ERR_JWS_INVALID";
};
var JWTInvalid = class extends JOSEError {
  static code = "ERR_JWT_INVALID";
  code = "ERR_JWT_INVALID";
};
var JWSSignatureVerificationFailed = class extends JOSEError {
  static code = "ERR_JWS_SIGNATURE_VERIFICATION_FAILED";
  code = "ERR_JWS_SIGNATURE_VERIFICATION_FAILED";
  constructor(message2 = "signature verification failed", options) {
    super(message2, options);
  }
};

// node_modules/jose/dist/node/esm/runtime/is_key_object.js
import * as util from "node:util";
var is_key_object_default = (obj) => util.types.isKeyObject(obj);

// node_modules/jose/dist/node/esm/runtime/webcrypto.js
import * as crypto from "node:crypto";
import * as util2 from "node:util";
var webcrypto2 = crypto.webcrypto;
var webcrypto_default = webcrypto2;
var isCryptoKey = (key) => util2.types.isCryptoKey(key);

// node_modules/jose/dist/node/esm/lib/crypto_key.js
function unusable(name, prop = "algorithm.name") {
  return new TypeError(`CryptoKey does not support this operation, its ${prop} must be ${name}`);
}
function isAlgorithm(algorithm, name) {
  return algorithm.name === name;
}
function getHashLength(hash) {
  return parseInt(hash.name.slice(4), 10);
}
function getNamedCurve(alg) {
  switch (alg) {
    case "ES256":
      return "P-256";
    case "ES384":
      return "P-384";
    case "ES512":
      return "P-521";
    default:
      throw new Error("unreachable");
  }
}
function checkUsage(key, usages) {
  if (usages.length && !usages.some((expected) => key.usages.includes(expected))) {
    let msg = "CryptoKey does not support this operation, its usages must include ";
    if (usages.length > 2) {
      const last = usages.pop();
      msg += `one of ${usages.join(", ")}, or ${last}.`;
    } else if (usages.length === 2) {
      msg += `one of ${usages[0]} or ${usages[1]}.`;
    } else {
      msg += `${usages[0]}.`;
    }
    throw new TypeError(msg);
  }
}
function checkSigCryptoKey(key, alg, ...usages) {
  switch (alg) {
    case "HS256":
    case "HS384":
    case "HS512": {
      if (!isAlgorithm(key.algorithm, "HMAC"))
        throw unusable("HMAC");
      const expected = parseInt(alg.slice(2), 10);
      const actual = getHashLength(key.algorithm.hash);
      if (actual !== expected)
        throw unusable(`SHA-${expected}`, "algorithm.hash");
      break;
    }
    case "RS256":
    case "RS384":
    case "RS512": {
      if (!isAlgorithm(key.algorithm, "RSASSA-PKCS1-v1_5"))
        throw unusable("RSASSA-PKCS1-v1_5");
      const expected = parseInt(alg.slice(2), 10);
      const actual = getHashLength(key.algorithm.hash);
      if (actual !== expected)
        throw unusable(`SHA-${expected}`, "algorithm.hash");
      break;
    }
    case "PS256":
    case "PS384":
    case "PS512": {
      if (!isAlgorithm(key.algorithm, "RSA-PSS"))
        throw unusable("RSA-PSS");
      const expected = parseInt(alg.slice(2), 10);
      const actual = getHashLength(key.algorithm.hash);
      if (actual !== expected)
        throw unusable(`SHA-${expected}`, "algorithm.hash");
      break;
    }
    case "EdDSA": {
      if (key.algorithm.name !== "Ed25519" && key.algorithm.name !== "Ed448") {
        throw unusable("Ed25519 or Ed448");
      }
      break;
    }
    case "Ed25519": {
      if (!isAlgorithm(key.algorithm, "Ed25519"))
        throw unusable("Ed25519");
      break;
    }
    case "ES256":
    case "ES384":
    case "ES512": {
      if (!isAlgorithm(key.algorithm, "ECDSA"))
        throw unusable("ECDSA");
      const expected = getNamedCurve(alg);
      const actual = key.algorithm.namedCurve;
      if (actual !== expected)
        throw unusable(expected, "algorithm.namedCurve");
      break;
    }
    default:
      throw new TypeError("CryptoKey does not support this operation");
  }
  checkUsage(key, usages);
}

// node_modules/jose/dist/node/esm/lib/invalid_key_input.js
function message(msg, actual, ...types4) {
  types4 = types4.filter(Boolean);
  if (types4.length > 2) {
    const last = types4.pop();
    msg += `one of type ${types4.join(", ")}, or ${last}.`;
  } else if (types4.length === 2) {
    msg += `one of type ${types4[0]} or ${types4[1]}.`;
  } else {
    msg += `of type ${types4[0]}.`;
  }
  if (actual == null) {
    msg += ` Received ${actual}`;
  } else if (typeof actual === "function" && actual.name) {
    msg += ` Received function ${actual.name}`;
  } else if (typeof actual === "object" && actual != null) {
    if (actual.constructor?.name) {
      msg += ` Received an instance of ${actual.constructor.name}`;
    }
  }
  return msg;
}
var invalid_key_input_default = (actual, ...types4) => {
  return message("Key must be ", actual, ...types4);
};
function withAlg(alg, actual, ...types4) {
  return message(`Key for the ${alg} algorithm must be `, actual, ...types4);
}

// node_modules/jose/dist/node/esm/runtime/is_key_like.js
var is_key_like_default = (key) => is_key_object_default(key) || isCryptoKey(key);
var types3 = ["KeyObject"];
if (globalThis.CryptoKey || webcrypto_default?.CryptoKey) {
  types3.push("CryptoKey");
}

// node_modules/jose/dist/node/esm/lib/is_disjoint.js
var isDisjoint = (...headers) => {
  const sources = headers.filter(Boolean);
  if (sources.length === 0 || sources.length === 1) {
    return true;
  }
  let acc;
  for (const header3 of sources) {
    const parameters = Object.keys(header3);
    if (!acc || acc.size === 0) {
      acc = new Set(parameters);
      continue;
    }
    for (const parameter of parameters) {
      if (acc.has(parameter)) {
        return false;
      }
      acc.add(parameter);
    }
  }
  return true;
};
var is_disjoint_default = isDisjoint;

// node_modules/jose/dist/node/esm/lib/is_object.js
function isObjectLike(value) {
  return typeof value === "object" && value !== null;
}
function isObject(input) {
  if (!isObjectLike(input) || Object.prototype.toString.call(input) !== "[object Object]") {
    return false;
  }
  if (Object.getPrototypeOf(input) === null) {
    return true;
  }
  let proto = input;
  while (Object.getPrototypeOf(proto) !== null) {
    proto = Object.getPrototypeOf(proto);
  }
  return Object.getPrototypeOf(input) === proto;
}

// node_modules/jose/dist/node/esm/runtime/get_named_curve.js
import { KeyObject } from "node:crypto";

// node_modules/jose/dist/node/esm/lib/is_jwk.js
function isJWK(key) {
  return isObject(key) && typeof key.kty === "string";
}
function isPrivateJWK(key) {
  return key.kty !== "oct" && typeof key.d === "string";
}
function isPublicJWK(key) {
  return key.kty !== "oct" && typeof key.d === "undefined";
}
function isSecretJWK(key) {
  return isJWK(key) && key.kty === "oct" && typeof key.k === "string";
}

// node_modules/jose/dist/node/esm/runtime/get_named_curve.js
var namedCurveToJOSE = (namedCurve) => {
  switch (namedCurve) {
    case "prime256v1":
      return "P-256";
    case "secp384r1":
      return "P-384";
    case "secp521r1":
      return "P-521";
    case "secp256k1":
      return "secp256k1";
    default:
      throw new JOSENotSupported("Unsupported key curve for this operation");
  }
};
var getNamedCurve2 = (kee, raw) => {
  let key;
  if (isCryptoKey(kee)) {
    key = KeyObject.from(kee);
  } else if (is_key_object_default(kee)) {
    key = kee;
  } else if (isJWK(kee)) {
    return kee.crv;
  } else {
    throw new TypeError(invalid_key_input_default(kee, ...types3));
  }
  if (key.type === "secret") {
    throw new TypeError('only "private" or "public" type keys can be used for this operation');
  }
  switch (key.asymmetricKeyType) {
    case "ed25519":
    case "ed448":
      return `Ed${key.asymmetricKeyType.slice(2)}`;
    case "x25519":
    case "x448":
      return `X${key.asymmetricKeyType.slice(1)}`;
    case "ec": {
      const namedCurve = key.asymmetricKeyDetails.namedCurve;
      if (raw) {
        return namedCurve;
      }
      return namedCurveToJOSE(namedCurve);
    }
    default:
      throw new TypeError("Invalid asymmetric key type for this operation");
  }
};
var get_named_curve_default = getNamedCurve2;

// node_modules/jose/dist/node/esm/runtime/check_key_length.js
import { KeyObject as KeyObject2 } from "node:crypto";
var check_key_length_default = (key, alg) => {
  let modulusLength;
  try {
    if (key instanceof KeyObject2) {
      modulusLength = key.asymmetricKeyDetails?.modulusLength;
    } else {
      modulusLength = Buffer.from(key.n, "base64url").byteLength << 3;
    }
  } catch {
  }
  if (typeof modulusLength !== "number" || modulusLength < 2048) {
    throw new TypeError(`${alg} requires key modulusLength to be 2048 bits or larger`);
  }
};

// node_modules/jose/dist/node/esm/runtime/asn1.js
import { createPrivateKey, createPublicKey, KeyObject as KeyObject3 } from "node:crypto";
import { Buffer as Buffer3 } from "node:buffer";
var fromSPKI = (pem2) => createPublicKey({
  key: Buffer3.from(pem2.replace(/(?:-----(?:BEGIN|END) PUBLIC KEY-----|\s)/g, ""), "base64"),
  type: "spki",
  format: "der"
});

// node_modules/jose/dist/node/esm/runtime/jwk_to_key.js
import { createPrivateKey as createPrivateKey2, createPublicKey as createPublicKey2 } from "node:crypto";
var parse = (key) => {
  if (key.d) {
    return createPrivateKey2({ format: "jwk", key });
  }
  return createPublicKey2({ format: "jwk", key });
};
var jwk_to_key_default = parse;

// node_modules/jose/dist/node/esm/key/import.js
async function importSPKI(spki, alg, options) {
  if (typeof spki !== "string" || spki.indexOf("-----BEGIN PUBLIC KEY-----") !== 0) {
    throw new TypeError('"spki" must be SPKI formatted string');
  }
  return fromSPKI(spki, alg, options);
}
async function importJWK(jwk, alg) {
  if (!isObject(jwk)) {
    throw new TypeError("JWK must be an object");
  }
  alg ||= jwk.alg;
  switch (jwk.kty) {
    case "oct":
      if (typeof jwk.k !== "string" || !jwk.k) {
        throw new TypeError('missing "k" (Key Value) Parameter value');
      }
      return decode(jwk.k);
    case "RSA":
      if ("oth" in jwk && jwk.oth !== void 0) {
        throw new JOSENotSupported('RSA JWK "oth" (Other Primes Info) Parameter value is not supported');
      }
    case "EC":
    case "OKP":
      return jwk_to_key_default({ ...jwk, alg });
    default:
      throw new JOSENotSupported('Unsupported "kty" (Key Type) Parameter value');
  }
}

// node_modules/jose/dist/node/esm/lib/check_key_type.js
var tag = (key) => key?.[Symbol.toStringTag];
var jwkMatchesOp = (alg, key, usage) => {
  if (key.use !== void 0 && key.use !== "sig") {
    throw new TypeError("Invalid key for this operation, when present its use must be sig");
  }
  if (key.key_ops !== void 0 && key.key_ops.includes?.(usage) !== true) {
    throw new TypeError(`Invalid key for this operation, when present its key_ops must include ${usage}`);
  }
  if (key.alg !== void 0 && key.alg !== alg) {
    throw new TypeError(`Invalid key for this operation, when present its alg must be ${alg}`);
  }
  return true;
};
var symmetricTypeCheck = (alg, key, usage, allowJwk) => {
  if (key instanceof Uint8Array)
    return;
  if (allowJwk && isJWK(key)) {
    if (isSecretJWK(key) && jwkMatchesOp(alg, key, usage))
      return;
    throw new TypeError(`JSON Web Key for symmetric algorithms must have JWK "kty" (Key Type) equal to "oct" and the JWK "k" (Key Value) present`);
  }
  if (!is_key_like_default(key)) {
    throw new TypeError(withAlg(alg, key, ...types3, "Uint8Array", allowJwk ? "JSON Web Key" : null));
  }
  if (key.type !== "secret") {
    throw new TypeError(`${tag(key)} instances for symmetric algorithms must be of type "secret"`);
  }
};
var asymmetricTypeCheck = (alg, key, usage, allowJwk) => {
  if (allowJwk && isJWK(key)) {
    switch (usage) {
      case "sign":
        if (isPrivateJWK(key) && jwkMatchesOp(alg, key, usage))
          return;
        throw new TypeError(`JSON Web Key for this operation be a private JWK`);
      case "verify":
        if (isPublicJWK(key) && jwkMatchesOp(alg, key, usage))
          return;
        throw new TypeError(`JSON Web Key for this operation be a public JWK`);
    }
  }
  if (!is_key_like_default(key)) {
    throw new TypeError(withAlg(alg, key, ...types3, allowJwk ? "JSON Web Key" : null));
  }
  if (key.type === "secret") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithms must not be of type "secret"`);
  }
  if (usage === "sign" && key.type === "public") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm signing must be of type "private"`);
  }
  if (usage === "decrypt" && key.type === "public") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm decryption must be of type "private"`);
  }
  if (key.algorithm && usage === "verify" && key.type === "private") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm verifying must be of type "public"`);
  }
  if (key.algorithm && usage === "encrypt" && key.type === "private") {
    throw new TypeError(`${tag(key)} instances for asymmetric algorithm encryption must be of type "public"`);
  }
};
function checkKeyType(allowJwk, alg, key, usage) {
  const symmetric = alg.startsWith("HS") || alg === "dir" || alg.startsWith("PBES2") || /^A\d{3}(?:GCM)?KW$/.test(alg);
  if (symmetric) {
    symmetricTypeCheck(alg, key, usage, allowJwk);
  } else {
    asymmetricTypeCheck(alg, key, usage, allowJwk);
  }
}
var check_key_type_default = checkKeyType.bind(void 0, false);
var checkKeyTypeWithJwk = checkKeyType.bind(void 0, true);

// node_modules/jose/dist/node/esm/lib/validate_crit.js
function validateCrit(Err, recognizedDefault, recognizedOption, protectedHeader, joseHeader) {
  if (joseHeader.crit !== void 0 && protectedHeader?.crit === void 0) {
    throw new Err('"crit" (Critical) Header Parameter MUST be integrity protected');
  }
  if (!protectedHeader || protectedHeader.crit === void 0) {
    return /* @__PURE__ */ new Set();
  }
  if (!Array.isArray(protectedHeader.crit) || protectedHeader.crit.length === 0 || protectedHeader.crit.some((input) => typeof input !== "string" || input.length === 0)) {
    throw new Err('"crit" (Critical) Header Parameter MUST be an array of non-empty strings when present');
  }
  let recognized;
  if (recognizedOption !== void 0) {
    recognized = new Map([...Object.entries(recognizedOption), ...recognizedDefault.entries()]);
  } else {
    recognized = recognizedDefault;
  }
  for (const parameter of protectedHeader.crit) {
    if (!recognized.has(parameter)) {
      throw new JOSENotSupported(`Extension Header Parameter "${parameter}" is not recognized`);
    }
    if (joseHeader[parameter] === void 0) {
      throw new Err(`Extension Header Parameter "${parameter}" is missing`);
    }
    if (recognized.get(parameter) && protectedHeader[parameter] === void 0) {
      throw new Err(`Extension Header Parameter "${parameter}" MUST be integrity protected`);
    }
  }
  return new Set(protectedHeader.crit);
}
var validate_crit_default = validateCrit;

// node_modules/jose/dist/node/esm/lib/validate_algorithms.js
var validateAlgorithms = (option, algorithms) => {
  if (algorithms !== void 0 && (!Array.isArray(algorithms) || algorithms.some((s) => typeof s !== "string"))) {
    throw new TypeError(`"${option}" option must be an array of strings`);
  }
  if (!algorithms) {
    return void 0;
  }
  return new Set(algorithms);
};
var validate_algorithms_default = validateAlgorithms;

// node_modules/jose/dist/node/esm/runtime/verify.js
import * as crypto3 from "node:crypto";
import { promisify as promisify2 } from "node:util";

// node_modules/jose/dist/node/esm/runtime/dsa_digest.js
function dsaDigest(alg) {
  switch (alg) {
    case "PS256":
    case "RS256":
    case "ES256":
    case "ES256K":
      return "sha256";
    case "PS384":
    case "RS384":
    case "ES384":
      return "sha384";
    case "PS512":
    case "RS512":
    case "ES512":
      return "sha512";
    case "Ed25519":
    case "EdDSA":
      return void 0;
    default:
      throw new JOSENotSupported(`alg ${alg} is not supported either by JOSE or your javascript runtime`);
  }
}

// node_modules/jose/dist/node/esm/runtime/node_key.js
import { constants, KeyObject as KeyObject4 } from "node:crypto";
var ecCurveAlgMap = /* @__PURE__ */ new Map([
  ["ES256", "P-256"],
  ["ES256K", "secp256k1"],
  ["ES384", "P-384"],
  ["ES512", "P-521"]
]);
function keyForCrypto(alg, key) {
  let asymmetricKeyType;
  let asymmetricKeyDetails;
  let isJWK2;
  if (key instanceof KeyObject4) {
    asymmetricKeyType = key.asymmetricKeyType;
    asymmetricKeyDetails = key.asymmetricKeyDetails;
  } else {
    isJWK2 = true;
    switch (key.kty) {
      case "RSA":
        asymmetricKeyType = "rsa";
        break;
      case "EC":
        asymmetricKeyType = "ec";
        break;
      case "OKP": {
        if (key.crv === "Ed25519") {
          asymmetricKeyType = "ed25519";
          break;
        }
        if (key.crv === "Ed448") {
          asymmetricKeyType = "ed448";
          break;
        }
        throw new TypeError("Invalid key for this operation, its crv must be Ed25519 or Ed448");
      }
      default:
        throw new TypeError("Invalid key for this operation, its kty must be RSA, OKP, or EC");
    }
  }
  let options;
  switch (alg) {
    case "Ed25519":
      if (asymmetricKeyType !== "ed25519") {
        throw new TypeError(`Invalid key for this operation, its asymmetricKeyType must be ed25519`);
      }
      break;
    case "EdDSA":
      if (!["ed25519", "ed448"].includes(asymmetricKeyType)) {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be ed25519 or ed448");
      }
      break;
    case "RS256":
    case "RS384":
    case "RS512":
      if (asymmetricKeyType !== "rsa") {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be rsa");
      }
      check_key_length_default(key, alg);
      break;
    case "PS256":
    case "PS384":
    case "PS512":
      if (asymmetricKeyType === "rsa-pss") {
        const { hashAlgorithm, mgf1HashAlgorithm, saltLength } = asymmetricKeyDetails;
        const length = parseInt(alg.slice(-3), 10);
        if (hashAlgorithm !== void 0 && (hashAlgorithm !== `sha${length}` || mgf1HashAlgorithm !== hashAlgorithm)) {
          throw new TypeError(`Invalid key for this operation, its RSA-PSS parameters do not meet the requirements of "alg" ${alg}`);
        }
        if (saltLength !== void 0 && saltLength > length >> 3) {
          throw new TypeError(`Invalid key for this operation, its RSA-PSS parameter saltLength does not meet the requirements of "alg" ${alg}`);
        }
      } else if (asymmetricKeyType !== "rsa") {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be rsa or rsa-pss");
      }
      check_key_length_default(key, alg);
      options = {
        padding: constants.RSA_PKCS1_PSS_PADDING,
        saltLength: constants.RSA_PSS_SALTLEN_DIGEST
      };
      break;
    case "ES256":
    case "ES256K":
    case "ES384":
    case "ES512": {
      if (asymmetricKeyType !== "ec") {
        throw new TypeError("Invalid key for this operation, its asymmetricKeyType must be ec");
      }
      const actual = get_named_curve_default(key);
      const expected = ecCurveAlgMap.get(alg);
      if (actual !== expected) {
        throw new TypeError(`Invalid key curve for the algorithm, its curve must be ${expected}, got ${actual}`);
      }
      options = { dsaEncoding: "ieee-p1363" };
      break;
    }
    default:
      throw new JOSENotSupported(`alg ${alg} is not supported either by JOSE or your javascript runtime`);
  }
  if (isJWK2) {
    return { format: "jwk", key, ...options };
  }
  return options ? { ...options, key } : key;
}

// node_modules/jose/dist/node/esm/runtime/sign.js
import * as crypto2 from "node:crypto";
import { promisify } from "node:util";

// node_modules/jose/dist/node/esm/runtime/hmac_digest.js
function hmacDigest(alg) {
  switch (alg) {
    case "HS256":
      return "sha256";
    case "HS384":
      return "sha384";
    case "HS512":
      return "sha512";
    default:
      throw new JOSENotSupported(`alg ${alg} is not supported either by JOSE or your javascript runtime`);
  }
}

// node_modules/jose/dist/node/esm/runtime/get_sign_verify_key.js
import { KeyObject as KeyObject5, createSecretKey } from "node:crypto";
function getSignVerifyKey(alg, key, usage) {
  if (key instanceof Uint8Array) {
    if (!alg.startsWith("HS")) {
      throw new TypeError(invalid_key_input_default(key, ...types3));
    }
    return createSecretKey(key);
  }
  if (key instanceof KeyObject5) {
    return key;
  }
  if (isCryptoKey(key)) {
    checkSigCryptoKey(key, alg, usage);
    return KeyObject5.from(key);
  }
  if (isJWK(key)) {
    if (alg.startsWith("HS")) {
      return createSecretKey(Buffer.from(key.k, "base64url"));
    }
    return key;
  }
  throw new TypeError(invalid_key_input_default(key, ...types3, "Uint8Array", "JSON Web Key"));
}

// node_modules/jose/dist/node/esm/runtime/sign.js
var oneShotSign = promisify(crypto2.sign);
var sign2 = async (alg, key, data) => {
  const k = getSignVerifyKey(alg, key, "sign");
  if (alg.startsWith("HS")) {
    const hmac = crypto2.createHmac(hmacDigest(alg), k);
    hmac.update(data);
    return hmac.digest();
  }
  return oneShotSign(dsaDigest(alg), data, keyForCrypto(alg, k));
};
var sign_default = sign2;

// node_modules/jose/dist/node/esm/runtime/verify.js
var oneShotVerify = promisify2(crypto3.verify);
var verify2 = async (alg, key, signature, data) => {
  const k = getSignVerifyKey(alg, key, "verify");
  if (alg.startsWith("HS")) {
    const expected = await sign_default(alg, k, data);
    const actual = signature;
    try {
      return crypto3.timingSafeEqual(actual, expected);
    } catch {
      return false;
    }
  }
  const algorithm = dsaDigest(alg);
  const keyInput = keyForCrypto(alg, k);
  try {
    return await oneShotVerify(algorithm, data, keyInput, signature);
  } catch {
    return false;
  }
};
var verify_default = verify2;

// node_modules/jose/dist/node/esm/jws/flattened/verify.js
async function flattenedVerify(jws, key, options) {
  if (!isObject(jws)) {
    throw new JWSInvalid("Flattened JWS must be an object");
  }
  if (jws.protected === void 0 && jws.header === void 0) {
    throw new JWSInvalid('Flattened JWS must have either of the "protected" or "header" members');
  }
  if (jws.protected !== void 0 && typeof jws.protected !== "string") {
    throw new JWSInvalid("JWS Protected Header incorrect type");
  }
  if (jws.payload === void 0) {
    throw new JWSInvalid("JWS Payload missing");
  }
  if (typeof jws.signature !== "string") {
    throw new JWSInvalid("JWS Signature missing or incorrect type");
  }
  if (jws.header !== void 0 && !isObject(jws.header)) {
    throw new JWSInvalid("JWS Unprotected Header incorrect type");
  }
  let parsedProt = {};
  if (jws.protected) {
    try {
      const protectedHeader = decode(jws.protected);
      parsedProt = JSON.parse(decoder.decode(protectedHeader));
    } catch {
      throw new JWSInvalid("JWS Protected Header is invalid");
    }
  }
  if (!is_disjoint_default(parsedProt, jws.header)) {
    throw new JWSInvalid("JWS Protected and JWS Unprotected Header Parameter names must be disjoint");
  }
  const joseHeader = {
    ...parsedProt,
    ...jws.header
  };
  const extensions = validate_crit_default(JWSInvalid, /* @__PURE__ */ new Map([["b64", true]]), options?.crit, parsedProt, joseHeader);
  let b64 = true;
  if (extensions.has("b64")) {
    b64 = parsedProt.b64;
    if (typeof b64 !== "boolean") {
      throw new JWSInvalid('The "b64" (base64url-encode payload) Header Parameter must be a boolean');
    }
  }
  const { alg } = joseHeader;
  if (typeof alg !== "string" || !alg) {
    throw new JWSInvalid('JWS "alg" (Algorithm) Header Parameter missing or invalid');
  }
  const algorithms = options && validate_algorithms_default("algorithms", options.algorithms);
  if (algorithms && !algorithms.has(alg)) {
    throw new JOSEAlgNotAllowed('"alg" (Algorithm) Header Parameter value not allowed');
  }
  if (b64) {
    if (typeof jws.payload !== "string") {
      throw new JWSInvalid("JWS Payload must be a string");
    }
  } else if (typeof jws.payload !== "string" && !(jws.payload instanceof Uint8Array)) {
    throw new JWSInvalid("JWS Payload must be a string or an Uint8Array instance");
  }
  let resolvedKey = false;
  if (typeof key === "function") {
    key = await key(parsedProt, jws);
    resolvedKey = true;
    checkKeyTypeWithJwk(alg, key, "verify");
    if (isJWK(key)) {
      key = await importJWK(key, alg);
    }
  } else {
    checkKeyTypeWithJwk(alg, key, "verify");
  }
  const data = concat(encoder.encode(jws.protected ?? ""), encoder.encode("."), typeof jws.payload === "string" ? encoder.encode(jws.payload) : jws.payload);
  let signature;
  try {
    signature = decode(jws.signature);
  } catch {
    throw new JWSInvalid("Failed to base64url decode the signature");
  }
  const verified = await verify_default(alg, key, signature, data);
  if (!verified) {
    throw new JWSSignatureVerificationFailed();
  }
  let payload;
  if (b64) {
    try {
      payload = decode(jws.payload);
    } catch {
      throw new JWSInvalid("Failed to base64url decode the payload");
    }
  } else if (typeof jws.payload === "string") {
    payload = encoder.encode(jws.payload);
  } else {
    payload = jws.payload;
  }
  const result = { payload };
  if (jws.protected !== void 0) {
    result.protectedHeader = parsedProt;
  }
  if (jws.header !== void 0) {
    result.unprotectedHeader = jws.header;
  }
  if (resolvedKey) {
    return { ...result, key };
  }
  return result;
}

// node_modules/jose/dist/node/esm/jws/compact/verify.js
async function compactVerify(jws, key, options) {
  if (jws instanceof Uint8Array) {
    jws = decoder.decode(jws);
  }
  if (typeof jws !== "string") {
    throw new JWSInvalid("Compact JWS must be a string or Uint8Array");
  }
  const { 0: protectedHeader, 1: payload, 2: signature, length } = jws.split(".");
  if (length !== 3) {
    throw new JWSInvalid("Invalid Compact JWS");
  }
  const verified = await flattenedVerify({ payload, protected: protectedHeader, signature }, key, options);
  const result = { payload: verified.payload, protectedHeader: verified.protectedHeader };
  if (typeof key === "function") {
    return { ...result, key: verified.key };
  }
  return result;
}

// node_modules/jose/dist/node/esm/lib/epoch.js
var epoch_default = (date) => Math.floor(date.getTime() / 1e3);

// node_modules/jose/dist/node/esm/lib/secs.js
var minute = 60;
var hour = minute * 60;
var day = hour * 24;
var week = day * 7;
var year = day * 365.25;
var REGEX = /^(\+|\-)? ?(\d+|\d+\.\d+) ?(seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d|weeks?|w|years?|yrs?|y)(?: (ago|from now))?$/i;
var secs_default = (str) => {
  const matched = REGEX.exec(str);
  if (!matched || matched[4] && matched[1]) {
    throw new TypeError("Invalid time period format");
  }
  const value = parseFloat(matched[2]);
  const unit = matched[3].toLowerCase();
  let numericDate;
  switch (unit) {
    case "sec":
    case "secs":
    case "second":
    case "seconds":
    case "s":
      numericDate = Math.round(value);
      break;
    case "minute":
    case "minutes":
    case "min":
    case "mins":
    case "m":
      numericDate = Math.round(value * minute);
      break;
    case "hour":
    case "hours":
    case "hr":
    case "hrs":
    case "h":
      numericDate = Math.round(value * hour);
      break;
    case "day":
    case "days":
    case "d":
      numericDate = Math.round(value * day);
      break;
    case "week":
    case "weeks":
    case "w":
      numericDate = Math.round(value * week);
      break;
    default:
      numericDate = Math.round(value * year);
      break;
  }
  if (matched[1] === "-" || matched[4] === "ago") {
    return -numericDate;
  }
  return numericDate;
};

// node_modules/jose/dist/node/esm/lib/jwt_claims_set.js
var normalizeTyp = (value) => value.toLowerCase().replace(/^application\//, "");
var checkAudiencePresence = (audPayload, audOption) => {
  if (typeof audPayload === "string") {
    return audOption.includes(audPayload);
  }
  if (Array.isArray(audPayload)) {
    return audOption.some(Set.prototype.has.bind(new Set(audPayload)));
  }
  return false;
};
var jwt_claims_set_default = (protectedHeader, encodedPayload, options = {}) => {
  let payload;
  try {
    payload = JSON.parse(decoder.decode(encodedPayload));
  } catch {
  }
  if (!isObject(payload)) {
    throw new JWTInvalid("JWT Claims Set must be a top-level JSON object");
  }
  const { typ } = options;
  if (typ && (typeof protectedHeader.typ !== "string" || normalizeTyp(protectedHeader.typ) !== normalizeTyp(typ))) {
    throw new JWTClaimValidationFailed('unexpected "typ" JWT header value', payload, "typ", "check_failed");
  }
  const { requiredClaims = [], issuer, subject, audience, maxTokenAge } = options;
  const presenceCheck = [...requiredClaims];
  if (maxTokenAge !== void 0)
    presenceCheck.push("iat");
  if (audience !== void 0)
    presenceCheck.push("aud");
  if (subject !== void 0)
    presenceCheck.push("sub");
  if (issuer !== void 0)
    presenceCheck.push("iss");
  for (const claim of new Set(presenceCheck.reverse())) {
    if (!(claim in payload)) {
      throw new JWTClaimValidationFailed(`missing required "${claim}" claim`, payload, claim, "missing");
    }
  }
  if (issuer && !(Array.isArray(issuer) ? issuer : [issuer]).includes(payload.iss)) {
    throw new JWTClaimValidationFailed('unexpected "iss" claim value', payload, "iss", "check_failed");
  }
  if (subject && payload.sub !== subject) {
    throw new JWTClaimValidationFailed('unexpected "sub" claim value', payload, "sub", "check_failed");
  }
  if (audience && !checkAudiencePresence(payload.aud, typeof audience === "string" ? [audience] : audience)) {
    throw new JWTClaimValidationFailed('unexpected "aud" claim value', payload, "aud", "check_failed");
  }
  let tolerance;
  switch (typeof options.clockTolerance) {
    case "string":
      tolerance = secs_default(options.clockTolerance);
      break;
    case "number":
      tolerance = options.clockTolerance;
      break;
    case "undefined":
      tolerance = 0;
      break;
    default:
      throw new TypeError("Invalid clockTolerance option type");
  }
  const { currentDate } = options;
  const now = epoch_default(currentDate || /* @__PURE__ */ new Date());
  if ((payload.iat !== void 0 || maxTokenAge) && typeof payload.iat !== "number") {
    throw new JWTClaimValidationFailed('"iat" claim must be a number', payload, "iat", "invalid");
  }
  if (payload.nbf !== void 0) {
    if (typeof payload.nbf !== "number") {
      throw new JWTClaimValidationFailed('"nbf" claim must be a number', payload, "nbf", "invalid");
    }
    if (payload.nbf > now + tolerance) {
      throw new JWTClaimValidationFailed('"nbf" claim timestamp check failed', payload, "nbf", "check_failed");
    }
  }
  if (payload.exp !== void 0) {
    if (typeof payload.exp !== "number") {
      throw new JWTClaimValidationFailed('"exp" claim must be a number', payload, "exp", "invalid");
    }
    if (payload.exp <= now - tolerance) {
      throw new JWTExpired('"exp" claim timestamp check failed', payload, "exp", "check_failed");
    }
  }
  if (maxTokenAge) {
    const age = now - payload.iat;
    const max = typeof maxTokenAge === "number" ? maxTokenAge : secs_default(maxTokenAge);
    if (age - tolerance > max) {
      throw new JWTExpired('"iat" claim timestamp check failed (too far in the past)', payload, "iat", "check_failed");
    }
    if (age < 0 - tolerance) {
      throw new JWTClaimValidationFailed('"iat" claim timestamp check failed (it should be in the past)', payload, "iat", "check_failed");
    }
  }
  return payload;
};

// node_modules/jose/dist/node/esm/jwt/verify.js
async function jwtVerify(jwt, key, options) {
  const verified = await compactVerify(jwt, key, options);
  if (verified.protectedHeader.crit?.includes("b64") && verified.protectedHeader.b64 === false) {
    throw new JWTInvalid("JWTs MUST NOT use unencoded payload");
  }
  const payload = jwt_claims_set_default(verified.protectedHeader, verified.payload, options);
  const result = { payload, protectedHeader: verified.protectedHeader };
  if (typeof key === "function") {
    return { ...result, key: verified.key };
  }
  return result;
}

// packages/server-core/src/jwt.ts
var ALG = "EdDSA";
var ISSUER = "shikhon-lms";
function pem(envVar) {
  const v = process.env[envVar];
  if (!v) throw new Error(`${envVar} env var is not set`);
  return v.includes("\\n") ? v.replace(/\\n/g, "\n") : v;
}
var _publicKey = null;
function publicKey() {
  if (!_publicKey) _publicKey = importSPKI(pem("JWT_PUBLIC_KEY"), ALG);
  return _publicKey;
}
async function verifyAccessToken(token) {
  const key = await publicKey();
  const { payload } = await jwtVerify(token, key, { issuer: ISSUER });
  if (!payload.sub || !payload.tid || !payload.role) {
    throw new Error("access token missing required claims");
  }
  return {
    sub: payload.sub,
    tid: payload.tid,
    role: payload.role,
    roles: payload.roles ?? [payload.role]
  };
}

// services/sync-svc/api/push.ts
var _handler = null;
async function handler() {
  if (_handler) return _handler;
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL env var is not set");
  const db = createDb2(url, { max: 5 });
  await assertRlsEnforced2(db);
  _handler = new SyncPushHandler(db);
  return _handler;
}
var CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": [
    "Content-Type",
    "Authorization",
    "X-Tenant-ID",
    "X-User-ID",
    "X-Role"
  ].join(", ")
};
function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on("data", (c) => chunks.push(c));
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}
function header(req, name) {
  const v = req.headers[name.toLowerCase()];
  return Array.isArray(v) ? v[0] ?? "" : v ?? "";
}
function json2(res, code, body) {
  const payload = JSON.stringify(body);
  res.writeHead(code, { ...CORS, "Content-Type": "application/json" });
  res.end(payload);
}
async function route(req, res) {
  if (req.method === "OPTIONS") {
    res.writeHead(204, CORS);
    res.end();
    return;
  }
  if (req.method !== "POST") {
    json2(res, 405, { error: "Method Not Allowed" });
    return;
  }
  const authHeader = header(req, "authorization");
  const token = authHeader.startsWith("Bearer ") ? authHeader.slice(7) : "";
  if (!token) {
    json2(res, 401, { error: "Unauthorized" });
    return;
  }
  let tenantId;
  let userId;
  let role;
  const SERVICE_API_KEY = process.env.SERVICE_API_KEY;
  if (SERVICE_API_KEY && token === SERVICE_API_KEY) {
    tenantId = header(req, "x-tenant-id");
    userId = header(req, "x-user-id");
    role = header(req, "x-role") || "teacher";
    if (!tenantId || !userId) {
      json2(res, 400, { error: "X-Tenant-ID and X-User-ID headers are required" });
      return;
    }
  } else {
    try {
      const claims = await verifyAccessToken(token);
      tenantId = claims.tid;
      userId = claims.sub;
      role = claims.role;
    } catch {
      json2(res, 401, { error: "Unauthorized" });
      return;
    }
  }
  let body;
  try {
    const raw = await readBody(req);
    body = JSON.parse(raw);
  } catch {
    json2(res, 400, { error: "Invalid JSON body" });
    return;
  }
  try {
    const h = await handler();
    const result = await h.handle(body, { tenantId, userId, role });
    json2(res, 200, result);
  } catch (err) {
    console.error("[sync/push]", err);
    const msg = err instanceof Error ? err.message : "Internal error";
    json2(res, 500, { error: msg });
  }
}

// services/sync-svc/src/pull.ts
var SCOPE_TABLES = {
  sections: "sections",
  enrolments: "enrolments",
  routineSlots: "routine_slots"
};
var SyncPullHandler = class {
  db;
  defaultLimit;
  now;
  constructor(db, opts = {}) {
    this.db = db;
    this.defaultLimit = opts.limit ?? 500;
    this.now = opts.now ?? Date.now;
  }
  async handle(params, ctx) {
    const scopes = params.scopes;
    for (const scope of scopes) {
      if (!SCOPE_TABLES[scope]) {
        throw Object.assign(new Error(`unknown scope: ${scope}`), { code: "UNKNOWN_SCOPE" });
      }
    }
    const limit = Math.min(params.limit ?? this.defaultLimit, 2e3);
    const serverNow = this.now();
    const changes = await this.db.withTenant(ctx, async (c) => {
      const logRows = await c.query(
        `SELECT id, scope, entity_id, op FROM sync_change_log
          WHERE tenant_id = app.current_tenant() AND scope = ANY($1) AND id > $2
          ORDER BY id ASC LIMIT $3`,
        [scopes, params.cursor, limit]
      );
      const byScope = /* @__PURE__ */ new Map();
      for (const row of logRows.rows) {
        if (row.op !== "U") continue;
        if (!byScope.has(row.scope)) byScope.set(row.scope, /* @__PURE__ */ new Set());
        byScope.get(row.scope).add(row.entity_id);
      }
      const dataByScopeAndId = /* @__PURE__ */ new Map();
      for (const [scope, ids] of byScope) {
        const table = SCOPE_TABLES[scope];
        const rows = await this.fetchRows(c, table, [...ids]);
        const m = /* @__PURE__ */ new Map();
        for (const row of rows) m.set(String(row.id), row);
        dataByScopeAndId.set(scope, m);
      }
      const out = [];
      for (const row of logRows.rows) {
        if (row.op === "D") {
          out.push({ scope: row.scope, entityId: row.entity_id, op: "D" });
          continue;
        }
        const data = dataByScopeAndId.get(row.scope)?.get(row.entity_id);
        if (!data) continue;
        out.push({ scope: row.scope, entityId: row.entity_id, op: "U", data });
      }
      const nextCursor = logRows.rows.length > 0 ? Number(logRows.rows[logRows.rows.length - 1].id) : params.cursor;
      return { out, nextCursor, hitLimit: logRows.rows.length === limit };
    });
    return {
      serverTime: new Date(serverNow).toISOString(),
      changes: changes.out,
      nextCursor: changes.nextCursor,
      hasMore: changes.hitLimit
    };
  }
  async fetchRows(c, table, ids) {
    if (ids.length === 0) return [];
    const { rows } = await c.query(`SELECT * FROM ${table} WHERE id = ANY($1)`, [ids]);
    return rows;
  }
};

// services/sync-svc/api/pull.ts
var _handler2 = null;
async function handler2() {
  if (_handler2) return _handler2;
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL env var is not set");
  const db = createDb2(url, { max: 5 });
  await assertRlsEnforced2(db);
  _handler2 = new SyncPullHandler(db);
  return _handler2;
}
var CORS2 = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
  "Access-Control-Allow-Headers": [
    "Content-Type",
    "Authorization",
    "X-Tenant-ID",
    "X-User-ID",
    "X-Role"
  ].join(", ")
};
function header2(req, name) {
  const v = req.headers[name.toLowerCase()];
  return Array.isArray(v) ? v[0] ?? "" : v ?? "";
}
function json3(res, code, body) {
  const payload = JSON.stringify(body);
  res.writeHead(code, { ...CORS2, "Content-Type": "application/json" });
  res.end(payload);
}
async function route2(req, res) {
  if (req.method === "OPTIONS") {
    res.writeHead(204, CORS2);
    res.end();
    return;
  }
  if (req.method !== "GET") {
    json3(res, 405, { error: "Method Not Allowed" });
    return;
  }
  const authHeader = header2(req, "authorization");
  const token = authHeader.startsWith("Bearer ") ? authHeader.slice(7) : "";
  if (!token) {
    json3(res, 401, { error: "Unauthorized" });
    return;
  }
  let tenantId;
  let userId;
  let role;
  const SERVICE_API_KEY = process.env.SERVICE_API_KEY;
  if (SERVICE_API_KEY && token === SERVICE_API_KEY) {
    tenantId = header2(req, "x-tenant-id");
    userId = header2(req, "x-user-id");
    role = header2(req, "x-role") || "teacher";
    if (!tenantId || !userId) {
      json3(res, 400, { error: "X-Tenant-ID and X-User-ID headers are required" });
      return;
    }
  } else {
    try {
      const claims = await verifyAccessToken(token);
      tenantId = claims.tid;
      userId = claims.sub;
      role = claims.role;
    } catch {
      json3(res, 401, { error: "Unauthorized" });
      return;
    }
  }
  const url = new URL(req.url ?? "/", "http://internal");
  const scopeParam = url.searchParams.get("scope") ?? "";
  const scopes = scopeParam.split(",").map((s) => s.trim()).filter(Boolean);
  if (scopes.length === 0) {
    json3(res, 400, { error: "scope query param is required (comma-separated)" });
    return;
  }
  const cursor = Number(url.searchParams.get("cursor") ?? "0");
  if (!Number.isFinite(cursor) || cursor < 0) {
    json3(res, 400, { error: "cursor must be a non-negative integer" });
    return;
  }
  const limitParam = url.searchParams.get("limit");
  const limit = limitParam ? Number(limitParam) : void 0;
  try {
    const h = await handler2();
    const result = await h.handle({ scopes, cursor, limit }, { tenantId, userId, role });
    json3(res, 200, result);
  } catch (err) {
    const code = err.code;
    if (code === "UNKNOWN_SCOPE") {
      json3(res, 400, { error: err.message });
      return;
    }
    console.error("[sync/pull]", err);
    const msg = err instanceof Error ? err.message : "Internal error";
    json3(res, 500, { error: msg });
  }
}

// services/sync-svc/api/index.ts
var ROUTES = { push: route, pull: route2 };
async function handler3(req, res) {
  const path = new URL(req.url ?? "/", "http://internal").pathname;
  const sub = path.split("/").filter(Boolean).pop() ?? "";
  const route3 = ROUTES[sub];
  if (!route3) {
    json(res, 404, { error: "not_found" }, corsHeaders());
    return;
  }
  if (req.method !== "OPTIONS") {
    const cls = req.method === "GET" ? "read" : "mutation";
    if (!await enforceRateLimit(req, res, corsHeaders(), cls)) return;
  }
  return route3(req, res);
}
export {
  handler3 as default
};
