// GENERATED by scripts/build.mjs from services/ans-svc/api/index.ts — do not edit directly.

// services/ans-svc/api/index.ts
import { createHmac, createHash } from "node:crypto";

// packages/server-core/src/db.ts
import pg from "pg";
function createDb(connectionString, opts = {}) {
  const pool = new pg.Pool({
    connectionString,
    max: 10,
    idleTimeoutMillis: 3e4,
    statement_timeout: 15e3,
    ...opts
  });
  async function inTx(setup, fn) {
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      await setup(client);
      const out = await fn(client);
      await client.query("COMMIT");
      return out;
    } catch (err) {
      try {
        await client.query("ROLLBACK");
      } catch {
      }
      throw err;
    } finally {
      client.release();
    }
  }
  return {
    pool,
    withTenant(ctx, fn) {
      if (!ctx.tenantId) throw new Error("tenant context required");
      return inTx(async (c) => {
        await c.query(
          `SELECT set_config('app.tenant_id', $1, true),
                  set_config('app.user_id',   $2, true),
                  set_config('app.role',      $3, true)`,
          [ctx.tenantId, ctx.userId, ctx.role]
        );
      }, fn);
    },
    withSystemRole(role, fn) {
      return inTx(async (c) => {
        await c.query(`SELECT set_config('app.role', $1, true)`, [role]);
      }, fn);
    },
    end: () => pool.end()
  };
}
async function assertRlsEnforced(db) {
  const { rows } = await db.pool.query(
    `SELECT rolname, rolbypassrls, rolsuper FROM pg_roles WHERE rolname = current_user`
  );
  const me = rows[0];
  if (!me) throw new Error("cannot resolve current_user");
  if (me.rolbypassrls || me.rolsuper) {
    throw new Error(
      `refusing to start: connected as "${me.rolname}" which has ${me.rolsuper ? "SUPERUSER" : "BYPASSRLS"} \u2014 RLS would not be enforced. Connect as the non-privileged runtime role instead.`
    );
  }
}
var _db = null;
async function sharedDb() {
  if (_db) return _db;
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL env var is not set");
  const db = createDb(url, { max: 5 });
  await assertRlsEnforced(db);
  _db = db;
  return db;
}

// packages/server-core/src/http.ts
function corsHeaders(extraHeaders = [], methods = "GET, POST, OPTIONS") {
  return {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": methods,
    "Access-Control-Allow-Headers": [
      "Content-Type",
      "Authorization",
      "X-Tenant-ID",
      "X-User-ID",
      "X-Role",
      ...extraHeaders
    ].join(", ")
  };
}
function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on("data", (c) => chunks.push(c));
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}
function header(req, name) {
  const v = req.headers[name.toLowerCase()];
  return Array.isArray(v) ? v[0] ?? "" : v ?? "";
}
function query(req) {
  const url = new URL(req.url ?? "/", "http://internal");
  return url.searchParams;
}
function json(res, code, body, cors) {
  const payload = JSON.stringify(body);
  res.writeHead(code, { ...cors, "Content-Type": "application/json" });
  res.end(payload);
}
var HttpError = class extends Error {
  // Longhand rather than constructor parameter properties: node --test
  // strips types instead of compiling them, and parameter properties are the
  // one TS-only construct it cannot strip. Since every server module reaches
  // this file, that single construct made all of server-core un-testable
  // under the project's `node --test file.ts` convention.
  status;
  code;
  /**
   * Structured context spread into the error body alongside `error` and
   * `message`. For refusals a screen has to act on rather than merely print —
   * the routine editor naming the class that already owns an hour, say — a
   * sentence is what the user reads and this is what the UI renders. Optional
   * everywhere; an endpoint that has nothing to add omits it.
   */
  detail;
  constructor(status, message, code, detail) {
    super(message);
    this.status = status;
    this.code = code;
    this.detail = detail;
  }
};

// packages/server-core/src/rate-limit.ts
var perHour = (n) => n / 3600;
var RATE_LIMITS = {
  // Hammering one phone with OTPs is the attack; 3/hour per phone stops it
  // dead. The IP allowance has to clear a whole school activating at once.
  otp_request: { ip: { capacity: 240, refill: perHour(240) }, identity: { capacity: 3, refill: perHour(3) } },
  // Verification is a guessing attack against a 6-digit code. identity-svc
  // already caps attempts per challenge; this bounds the outer loop of
  // requesting a fresh challenge and guessing again.
  otp_verify: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 10, refill: perHour(10) } },
  // Refresh and logout — authenticated, cheap, but part of the auth surface.
  auth: { ip: { capacity: 600, refill: perHour(600) } },
  // The only endpoint class with real per-request cost. Per-identity is the
  // spend control until F-1310's proper token metering lands.
  ai: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 30, refill: perHour(30) } },
  // Ordinary authenticated traffic. Sized for a school, not a person: a
  // sync/push after a day offline is one request, not many.
  mutation: { ip: { capacity: 900, refill: 15 } },
  read: { ip: { capacity: 1800, refill: 30 } },
  // Machine-to-machine: MFS webhooks, cron workers, ANS dispatch. Already
  // gated by signature or service key; this is a backstop against a loop.
  service: { ip: { capacity: 3e3, refill: 50 } }
};
function clientIp(req) {
  const xff = req.headers["x-forwarded-for"];
  const first = Array.isArray(xff) ? xff[0] : xff;
  const ip = first?.split(",")[0]?.trim() || req.headers["x-real-ip"]?.trim() || req.socket?.remoteAddress || "unknown";
  return ip.slice(0, 64);
}
function buildBuckets(cls, ip, identity) {
  const policy = RATE_LIMITS[cls];
  const buckets = [];
  if (ip) {
    buckets.push({ key: `${cls}:ip:${ip}`, capacity: policy.ip.capacity, refill: policy.ip.refill });
  }
  if (policy.identity && identity) {
    buckets.push({
      key: `${cls}:id:${identity}`,
      capacity: policy.identity.capacity,
      refill: policy.identity.refill
    });
  }
  return buckets;
}
async function consumeRateLimit(cls, ip, identity) {
  const buckets = buildBuckets(cls, ip, identity);
  if (buckets.length === 0) return { allowed: true, retryAfterSec: 0 };
  try {
    const db = await sharedDb();
    const { rows } = await db.pool.query("SELECT * FROM app.rate_limit_consume($1::jsonb)", [JSON.stringify(buckets)]);
    const row = rows[0];
    if (!row) return { allowed: true, retryAfterSec: 0 };
    if (!row.allowed) {
      console.warn(`[rate-limit] refused ${cls}, bucket=${row.blocked_key}, retry=${row.retry_after_sec}s`);
    }
    return { allowed: row.allowed, retryAfterSec: row.retry_after_sec };
  } catch (err) {
    console.error("[rate-limit] check failed, allowing request:", err);
    return { allowed: true, retryAfterSec: 0 };
  }
}
async function enforceRateLimit(req, res, cors, cls, identity) {
  const verdict = await consumeRateLimit(cls, clientIp(req), identity);
  return sendIfRefused(res, cors, verdict);
}
function sendIfRefused(res, cors, verdict) {
  if (verdict.allowed) return true;
  json(
    res,
    429,
    {
      error: "rate_limited",
      message: "too many requests \u2014 please wait before trying again",
      retryAfterSec: verdict.retryAfterSec
    },
    { ...cors, "Retry-After": String(verdict.retryAfterSec) }
  );
  return false;
}

// services/ans-svc/api/index.ts
var UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function requireServiceAuth(req, allowCron) {
  const authHeader = header(req, "authorization");
  const token = authHeader.startsWith("Bearer ") ? authHeader.slice(7) : "";
  const valid = [process.env.SERVICE_API_KEY, allowCron ? process.env.CRON_SECRET : void 0].filter(Boolean);
  if (!token || !valid.includes(token)) {
    throw new HttpError(401, "service credentials required", "unauthorized");
  }
}
async function students(req, res, cors) {
  if (req.method !== "GET") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  requireServiceAuth(req, false);
  const q = query(req);
  const tenantId = q.get("tenantId") ?? "";
  if (!UUID_RE.test(tenantId)) throw new HttpError(400, "tenantId must be a valid uuid", "invalid_tenant_id");
  const since = q.get("since");
  const gradYear = q.get("graduationYear");
  const db = await sharedDb();
  const records = await db.withTenant(
    { tenantId, userId: "", role: "academic_coordinator" },
    async (client) => {
      const r = await client.query(
        `SELECT a.global_person_id, a.student_id, a.institution_eiin,
                a.lifecycle_event, a.graduation_year, a.final_class_level,
                a.final_exam_name, a.final_gpa, a.final_letter_grade,
                a.achievements, a.co_curricular, a.subjects_studied,
                a.schema_version, a.record_version, a.effective_at,
                a.contact_shared,
                u.full_name_bn, u.full_name_en,
                CASE WHEN a.contact_shared THEN u.phone_e164 ELSE NULL END AS phone_e164
           FROM alumni_records a
           JOIN users u ON u.id = a.student_id
          WHERE ($1::timestamptz IS NULL OR a.updated_at > $1)
            AND ($2::smallint IS NULL OR a.graduation_year = $2)
          ORDER BY a.updated_at
          LIMIT 500`,
        [since || null, gradYear || null]
      );
      return r.rows;
    }
  );
  json(res, 200, {
    tenantId,
    count: records.length,
    records: records.map((r) => ({
      globalPersonId: r.global_person_id,
      // THE merge key (unified identifier)
      institutionId: tenantId,
      institutionEiin: r.institution_eiin,
      lifecycleEvent: r.lifecycle_event,
      graduationYear: r.graduation_year,
      finalClassLevel: r.final_class_level,
      finalExamName: r.final_exam_name,
      finalGpa: r.final_gpa,
      finalLetterGrade: r.final_letter_grade,
      achievements: r.achievements,
      coCurricular: r.co_curricular,
      subjectsStudied: r.subjects_studied,
      schemaVersion: r.schema_version,
      recordVersion: r.record_version,
      effectiveAt: r.effective_at,
      // Consent-gated (PDPA 2026): null unless the alum opted in.
      fullName: r.contact_shared ? { bn: r.full_name_bn, en: r.full_name_en } : null,
      phone: r.phone_e164
    }))
  }, cors);
}
var MAX_BATCH = 25;
async function dispatch(req, res, cors) {
  if (req.method !== "POST" && req.method !== "GET") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  requireServiceAuth(req, true);
  const db = await sharedDb();
  const signingSecret = process.env.ANS_SIGNING_SECRET ?? "";
  const pending = await db.withSystemRole("system_ingest", async (client) => {
    const r = await client.query(
      `SELECT l.id, l.tenant_id, l.endpoint_id, l.delivery_id, l.event_type,
              l.payload, l.attempts, l.max_attempts,
              e.base_url, e.signing_key_id, e.is_active
         FROM alumni_export_logs l
         JOIN ans_endpoints e ON e.id = l.endpoint_id
        WHERE l.status IN ('pending','failed')
          AND (l.next_attempt_at IS NULL OR l.next_attempt_at <= now())
        ORDER BY l.created_at
        LIMIT ${MAX_BATCH}`
    );
    return r.rows;
  }).catch(() => []);
  let delivered = 0;
  let failed = 0;
  let parked = 0;
  for (const row of pending) {
    const ctx = { tenantId: row.tenant_id, userId: "", role: "academic_coordinator" };
    const body = JSON.stringify(row.payload ?? {});
    if (!row.is_active || !signingSecret) {
      parked += 1;
      await db.withTenant(
        ctx,
        (c) => c.query(
          `UPDATE alumni_export_logs
              SET status = 'failed', attempts = attempts + 1,
                  error_code = $2,
                  next_attempt_at = now() + interval '6 hours'
            WHERE id = $1`,
          [row.id, row.is_active ? "signing_key_unavailable" : "endpoint_inactive"]
        )
      );
      continue;
    }
    const signature = createHmac("sha256", signingSecret).update(body).digest("hex");
    try {
      const resp = await fetch(`${row.base_url.replace(/\/$/, "")}/v1/webhooks/lms`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-Shikhon-Delivery-Id": row.delivery_id,
          "X-Shikhon-Event": row.event_type,
          "X-Shikhon-Key-Id": row.signing_key_id,
          "X-Shikhon-Signature": `sha256=${signature}`
        },
        body,
        signal: AbortSignal.timeout(1e4)
      });
      const ok = resp.status >= 200 && resp.status < 300;
      await db.withTenant(
        ctx,
        (c) => c.query(
          ok ? `UPDATE alumni_export_logs
                  SET status = 'delivered', attempts = attempts + 1, http_status = $2,
                      first_attempt_at = COALESCE(first_attempt_at, now()), completed_at = now()
                WHERE id = $1` : `UPDATE alumni_export_logs
                  SET status = CASE WHEN attempts + 1 >= max_attempts THEN 'dead_lettered'::ans_delivery_status
                                    ELSE 'failed'::ans_delivery_status END,
                      attempts = attempts + 1, http_status = $2,
                      first_attempt_at = COALESCE(first_attempt_at, now()),
                      next_attempt_at = now() + (interval '1 minute' * power(2, LEAST(attempts, 8)))
                WHERE id = $1`,
          [row.id, resp.status]
        )
      );
      if (ok) delivered += 1;
      else failed += 1;
    } catch (err) {
      failed += 1;
      await db.withTenant(
        ctx,
        (c) => c.query(
          `UPDATE alumni_export_logs
              SET status = CASE WHEN attempts + 1 >= max_attempts THEN 'dead_lettered'::ans_delivery_status
                                ELSE 'failed'::ans_delivery_status END,
                  attempts = attempts + 1, error_code = 'network_error', error_detail = $2,
                  first_attempt_at = COALESCE(first_attempt_at, now()),
                  next_attempt_at = now() + (interval '1 minute' * power(2, LEAST(attempts, 8)))
            WHERE id = $1`,
          [row.id, String(err.message ?? err).slice(0, 500)]
        )
      );
    }
  }
  json(res, 200, { ok: true, claimed: pending.length, delivered, failed, parked }, cors);
}
async function inbound(req, res, cors) {
  if (req.method !== "POST") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  const raw = await readBody(req);
  if (!raw || raw.length > 256 * 1024) {
    throw new HttpError(400, "body required (max 256 KB)", "invalid_body");
  }
  let parsed = {};
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new HttpError(400, "body must be JSON", "invalid_json");
  }
  const eventType = parsed.eventType ?? "unknown";
  const eventId = parsed.eventId ?? createHash("sha256").update(raw).digest("hex").slice(0, 32);
  const sig = header(req, "x-ans-signature");
  const sourceIp = req.headers["x-forwarded-for"]?.split(",")[0]?.trim() ?? null;
  const db = await sharedDb();
  await db.withSystemRole(
    "system_ingest",
    (client) => client.query(
      `INSERT INTO ans_inbound_events
         (tenant_id, global_person_id, event_type, ans_event_id, raw_body, signature_valid, source_ip)
       VALUES (NULL, $1, $2, $3, $4, $5, $6)
       ON CONFLICT (endpoint_id, ans_event_id) DO NOTHING`,
      [
        UUID_RE.test(parsed.globalPersonId ?? "") ? parsed.globalPersonId : null,
        eventType,
        eventId,
        raw,
        sig ? null : false,
        sourceIp
      ]
    )
  );
  json(res, 202, { ok: true, staged: true }, cors);
}
var ROUTES = {
  students,
  dispatch,
  inbound
};
async function handler(req, res) {
  const cors = corsHeaders();
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  const path = new URL(req.url ?? "/", "http://internal").pathname;
  const sub = path.split("/").filter(Boolean).pop() ?? "";
  const route = ROUTES[sub];
  if (!route) {
    json(res, 404, { error: "not_found" }, cors);
    return;
  }
  if (!await enforceRateLimit(req, res, cors, "service")) return;
  try {
    await route(req, res, cors);
  } catch (err) {
    if (err instanceof HttpError) {
      json(res, err.status, { error: err.code ?? "error", message: err.message }, cors);
      return;
    }
    console.error(`[ans/${sub}] unexpected error`, err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}
export {
  handler as default
};
