/**
 * Bundles browser-side and API-side TypeScript into self-contained files.
 *
 * Browser bundles (platform: browser):
 *   app.js  — the attendance screen and outbox (loaded as an ES module)
 *   sw.js   — the service worker (loaded as a classic script, IIFE format)
 *
 * API bundle (platform: node):
 *   api/v1/sync/push.js — Vercel's Node builder only transpiles a function's
 *   entry file; it does not resolve relative imports that reach outside the
 *   api/ directory (e.g. into services/ or packages/). Bundling the whole
 *   dependency graph ourselves, with only 'pg' left external (it ships via
 *   npm's "dependencies" and is resolved from node_modules at runtime),
 *   sidesteps that limitation entirely.
 */
import { build } from 'esbuild';
import { readFile, readdir, rm } from 'node:fs/promises';

const BROWSER = {
  bundle: true,
  minify: true,
  platform: 'browser',
  // esbuild resolves .ts imports natively; no plugin needed.
  resolveExtensions: ['.ts', '.js'],
  // Preserve function and class .name after minification. Two reasons:
  // (1) a stack trace with `at Fn.render (app.js:1:82934)` is unusable —
  //     class names in stacks are what makes the offline browser reports
  //     legible when they come back from a school phone;
  // (2) the tree-shake check below greps the bundle for View class names,
  //     and without keepNames every class would be `x`, `y`, `z`.
  // Size cost is ~0.3% on this bundle. Cheap.
  keepNames: true,
};

await build({
  ...BROWSER,
  entryPoints: ['apps/pwa/src/app.ts'],
  format: 'esm',
  outfile: 'apps/pwa/public/app.js',
  define: { 'process.env.NODE_ENV': '"production"' },
});

await build({
  ...BROWSER,
  entryPoints: ['apps/pwa/src/sw.ts'],
  // Service workers are registered as classic scripts; ES module SWs have
  // limited browser support on the Android Go devices this app targets.
  format: 'iife',
  outfile: 'apps/pwa/public/sw.js',
});

// Every Vercel Node function entry point, paired with the api/ path Vercel's
// file-based routing derives its route from. One esbuild call per entry —
// each becomes a self-contained file with the whole services/+packages/
// dependency graph inlined (see the file banner above for why).
//
// Each service is ONE dynamic-route function (an index.ts dispatcher routing
// to the per-endpoint handler files, which are unchanged) — the Hobby plan
// caps a deployment at 12 Serverless Functions, and the per-endpoint layout
// hit the cap with no room for the exams/finance/AI/ANS endpoints. External
// URLs are identical; only the function count changed. 9 functions, 3 spare.
const API_ENTRIES = [
  ['services/sync-svc/api/index.ts', 'api/v1/sync/[action].js'],
  // auth is a plain function + vercel.json rewrite (?path=) because a
  // multi-segment [...path] catch-all does not match on prebuilt functions.
  ['services/identity-svc/api/index.ts', 'api/v1/auth.js'],
  ['services/academics-svc/api/index.ts', 'api/v1/academics/[resource].js'],
  ['services/sms-svc/api/dispatch.ts', 'api/v1/sms/dispatch.js'],
  ['services/rms-svc/api/index.ts', 'api/v1/rms/[action].js'],
  ['services/finance-svc/api/webhooks/[provider].ts', 'api/v1/finance/webhooks/[provider].js'],
  ['services/finance-svc/api/index.ts', 'api/v1/finance/[resource].js'],
  ['services/ai-svc/api/index.ts', 'api/v1/ai/[engine].js'],
  ['services/ans-svc/api/index.ts', 'api/v1/ans/[action].js'],
  ['services/ops-svc/api/index.ts', 'api/v1/ops/[action].js'],
];

// The api/ tree is fully generated. Clear it first so entries removed from
// the list above can never linger on disk and deploy as extra functions.
await rm('api', { recursive: true, force: true });

for (const [entry, outfile] of API_ENTRIES) {
  await build({
    bundle: true,
    minify: false,
    platform: 'node',
    target: 'node22',
    format: 'esm',
    resolveExtensions: ['.ts', '.js'],
    external: ['pg', 'pg-native'],
    entryPoints: [entry],
    outfile,
    banner: { js: `// GENERATED by scripts/build.mjs from ${entry} — do not edit directly.` },
  });
}

// ─────────────────────────────────────────────────────────────────────────
//   Postcondition: every -view.ts's exported View class is in the bundle.
//
// The GuardianView incident — view committed, mount forgotten, the
// import line the only reference in the graph, esbuild correctly dropped
// the whole 395-line file, CI stayed green, prod carried a broken more-
// menu link for a day. Every check I had ran against source; none ran
// against what the bundle contained. This one does.
//
// A class name minified away would make this trivially wrong, so app.js
// is built minify: true above and the check runs against it. Class
// declarations survive minification as string references in prototype
// setup — esbuild keeps them for `.name` and error stacks. A source file
// with no `export class` in it (types, helpers, wiring) is skipped.
//
// Deliberate exception: a view a role never reaches (a dashboard only
// principals see, say) may legitimately be tree-shaken from a build
// scoped to another audience. Today every -view.ts IS reachable from
// some route, so the exception list stays empty. Add a name here when
// that changes — with the reason — so silence never means "I forgot".
// ─────────────────────────────────────────────────────────────────────────
const bundle = await readFile('apps/pwa/public/app.js', 'utf8');
const viewFiles = (await readdir('apps/pwa/src'))
  .filter((f) => f.endsWith('-view.ts'));
const VIEW_TREE_SHAKE_ALLOWED = new Set([
  // e.g. 'SomePrincipalOnlyView — only mounted for principals; no other role bundle needs it',
]);
const missing = [];
for (const file of viewFiles) {
  const src = await readFile(`apps/pwa/src/${file}`, 'utf8');
  const match = src.match(/^export class (\w+View)\b/m);
  if (!match) continue;
  const name = match[1];
  if (VIEW_TREE_SHAKE_ALLOWED.has(name)) continue;
  if (!bundle.includes(name)) missing.push({ file, name });
}
if (missing.length > 0) {
  console.error(
    `\n  ✗ ${missing.length} View class(es) are absent from apps/pwa/public/app.js:\n` +
    missing.map((m) => `      - ${m.name}   (from apps/pwa/src/${m.file})`).join('\n') +
    `\n\n    Either add a route or menu entry that instantiates each, or list it in\n` +
    `    scripts/build.mjs's VIEW_TREE_SHAKE_ALLOWED with the reason.\n`,
  );
  process.exit(1);
}

console.log(`build complete — app.js + sw.js + ${API_ENTRIES.length} API bundles written`);
