/**
 * Bundles browser-side and API-side TypeScript into self-contained files.
 *
 * Browser bundles (platform: browser):
 *   app.js  — the attendance screen and outbox (loaded as an ES module)
 *   sw.js   — the service worker (loaded as a classic script, IIFE format)
 *
 * API bundle (platform: node):
 *   api/v1/sync/push.js — Vercel's Node builder only transpiles a function's
 *   entry file; it does not resolve relative imports that reach outside the
 *   api/ directory (e.g. into services/ or packages/). Bundling the whole
 *   dependency graph ourselves, with only 'pg' left external (it ships via
 *   npm's "dependencies" and is resolved from node_modules at runtime),
 *   sidesteps that limitation entirely.
 */
import { build } from 'esbuild';
import { readFile, readdir, rm } from 'node:fs/promises';

const BROWSER = {
  bundle: true,
  minify: true,
  platform: 'browser',
  // esbuild resolves .ts imports natively; no plugin needed.
  resolveExtensions: ['.ts', '.js'],
  // Preserve function and class .name after minification. Two reasons:
  // (1) a stack trace with `at Fn.render (app.js:1:82934)` is unusable —
  //     class names in stacks are what makes the offline browser reports
  //     legible when they come back from a school phone;
  // (2) the tree-shake check below greps the bundle for View class names,
  //     and without keepNames every class would be `x`, `y`, `z`.
  // Size cost is ~0.3% on this bundle. Cheap.
  keepNames: true,
};

await build({
  ...BROWSER,
  entryPoints: ['apps/pwa/src/app.ts'],
  format: 'esm',
  outfile: 'apps/pwa/public/app.js',
  define: { 'process.env.NODE_ENV': '"production"' },
});

await build({
  ...BROWSER,
  entryPoints: ['apps/pwa/src/sw.ts'],
  // Service workers are registered as classic scripts; ES module SWs have
  // limited browser support on the Android Go devices this app targets.
  format: 'iife',
  outfile: 'apps/pwa/public/sw.js',
});

// Every Vercel Node function entry point, paired with the api/ path Vercel's
// file-based routing derives its route from. One esbuild call per entry —
// each becomes a self-contained file with the whole services/+packages/
// dependency graph inlined (see the file banner above for why).
//
// Each service is ONE dynamic-route function (an index.ts dispatcher routing
// to the per-endpoint handler files, which are unchanged) — the Hobby plan
// caps a deployment at 12 Serverless Functions, and the per-endpoint layout
// hit the cap with no room for the exams/finance/AI/ANS endpoints. External
// URLs are identical; only the function count changed. 9 functions, 3 spare.
const API_ENTRIES = [
  ['services/sync-svc/api/index.ts', 'api/v1/sync/[action].js'],
  // auth is a plain function + vercel.json rewrite (?path=) because a
  // multi-segment [...path] catch-all does not match on prebuilt functions.
  ['services/identity-svc/api/index.ts', 'api/v1/auth.js'],
  ['services/academics-svc/api/index.ts', 'api/v1/academics/[resource].js'],
  ['services/sms-svc/api/dispatch.ts', 'api/v1/sms/dispatch.js'],
  ['services/rms-svc/api/index.ts', 'api/v1/rms/[action].js'],
  ['services/finance-svc/api/webhooks/[provider].ts', 'api/v1/finance/webhooks/[provider].js'],
  ['services/finance-svc/api/index.ts', 'api/v1/finance/[resource].js'],
  ['services/ai-svc/api/index.ts', 'api/v1/ai/[engine].js'],
  ['services/ans-svc/api/index.ts', 'api/v1/ans/[action].js'],
  ['services/ops-svc/api/index.ts', 'api/v1/ops/[action].js'],
];

// The api/ tree is fully generated. Clear it first so entries removed from
// the list above can never linger on disk and deploy as extra functions.
await rm('api', { recursive: true, force: true });

for (const [entry, outfile] of API_ENTRIES) {
  await build({
    bundle: true,
    minify: false,
    platform: 'node',
    target: 'node22',
    format: 'esm',
    resolveExtensions: ['.ts', '.js'],
    external: ['pg', 'pg-native'],
    entryPoints: [entry],
    outfile,
    banner: { js: `// GENERATED by scripts/build.mjs from ${entry} — do not edit directly.` },
  });
}

// ─────────────────────────────────────────────────────────────────────────
//   Netlify Functions (v2) — the same handlers, a different edge.
//
// Netlify hands a Web Request and wants a Web Response; these handlers are
// written against Node's (req, res) because that is what Vercel gives them.
// netlify/adapter.mjs shims the two shapes so there is exactly ONE copy of
// every handler — forking them would mean maintaining two copies of the
// tenant guard and the rate limiter, and eventually fixing a security bug
// in only one.
//
// v2 functions declare their own route via `export const config = { path }`,
// so there are no redirects to keep in sync with this list. The paths below
// are byte-identical to the Vercel ones, which is the point: the PWA ships
// the same bundle to both hosts and neither knows about the other.
const NETLIFY_ENTRIES = [
  ['services/sync-svc/api/index.ts',                    'sync',            '/api/v1/sync/:action'],
  // Splat, not ':path*' — that is Vercel/Express syntax and Netlify v2 uses
  // URLPattern, where it silently matches nothing (verified live: 404).
  // The dispatcher already falls back from ?path= to parsing the real
  // pathname, so no rewrite is needed on this host.
  ['services/identity-svc/api/index.ts',                'auth',            '/api/v1/auth/*'],
  ['services/academics-svc/api/index.ts',               'academics',       '/api/v1/academics/:resource'],
  ['services/sms-svc/api/dispatch.ts',                  'sms-dispatch',    '/api/v1/sms/dispatch'],
  ['services/rms-svc/api/index.ts',                     'rms',             '/api/v1/rms/:action'],
  ['services/finance-svc/api/webhooks/[provider].ts',   'finance-webhook', '/api/v1/finance/webhooks/:provider'],
  ['services/finance-svc/api/index.ts',                 'finance',         '/api/v1/finance/:resource'],
  ['services/ai-svc/api/index.ts',                      'ai',              '/api/v1/ai/:engine'],
  ['services/ans-svc/api/index.ts',                     'ans',             '/api/v1/ans/:action'],
  ['services/ops-svc/api/index.ts',                     'ops',             '/api/v1/ops/:action'],
];

await rm('netlify/functions', { recursive: true, force: true });

for (const [entry, name, routePath] of NETLIFY_ENTRIES) {
  await build({
    // stdin rather than ten generated wrapper files on disk: the wrapper is
    // three lines and having it exist only inside the build keeps the repo
    // free of files nobody should edit.
    stdin: {
      contents: [
        `import handler from './${entry}';`,
        `import { netlifyAdapter } from './netlify/adapter.mjs';`,
        `export default netlifyAdapter(handler);`,
        `export const config = { path: ${JSON.stringify(routePath)} };`,
      ].join('\n'),
      resolveDir: '.',
      sourcefile: `netlify-${name}.js`,
      loader: 'js',
    },
    bundle: true,
    minify: false,
    platform: 'node',
    target: 'node22',
    format: 'esm',
    resolveExtensions: ['.ts', '.js'],
    external: ['pg', 'pg-native'],
    outfile: `netlify/functions/${name}.mjs`,
    banner: { js: `// GENERATED by scripts/build.mjs from ${entry} — do not edit directly.` },
  });
}


// Scheduled functions are SEPARATE from the HTTP ones on purpose.
//
// On Vercel a cron is an HTTP GET to a normal path, so one function served
// both the schedule and the request. Netlify makes a scheduled function
// internal-only: adding `schedule` to the ops function returned 403 to the
// PWA's product-event ingest (F-1503), which shares that dispatcher.
// Verified on the live deploy — non-scheduled function 204, scheduled 403.
//
// So the cron gets its own wrapper that invokes the same handler in
// process, and /api/v1/ops/* and /api/v1/sms/dispatch stay reachable.
const SCHEDULED_ENTRIES = [
  ['services/sms-svc/api/dispatch.ts', 'cron-sms',         '/api/v1/sms/dispatch',    '0 18 * * *'],
  ['services/ops-svc/api/index.ts',    'cron-maintenance', '/api/v1/ops/maintenance', '0 19 * * *'],
];

for (const [entry, name, invokePath, schedule] of SCHEDULED_ENTRIES) {
  await build({
    stdin: {
      contents: [
        `import handler from './${entry}';`,
        `import { netlifyAdapter } from './netlify/adapter.mjs';`,
        `const inner = netlifyAdapter(handler);`,
        // These handlers authenticate a bearer against CRON_SECRET /
        // SERVICE_API_KEY (see maintenance.ts, dispatch.ts). The schedule
        // runs in the same environment, so the secret is read from env and
        // passed through rather than the auth check being bypassed for
        // internal callers — a handler with a "trusted caller" branch is a
        // handler with a second, untested way in.
        `export default async () => {`,
        `  const token = process.env.CRON_SECRET || process.env.SERVICE_API_KEY || '';`,
        `  const res = await inner(new Request('https://internal${invokePath}', {`,
        `    method: 'POST', body: '{}',`,
        `    headers: { 'Content-Type': 'application/json', authorization: 'Bearer ' + token },`,
        `  }));`,
        `  const body = await res.text();`,
        `  if (res.status >= 400) console.error(${JSON.stringify(name)}, res.status, body);`,
        `  else console.log(${JSON.stringify(name)}, res.status, body.slice(0, 300));`,
        `  return new Response(null, { status: 204 });`,
        `};`,
        `export const config = { schedule: ${JSON.stringify(schedule)} };`,
      ].join('\n'),
      resolveDir: '.',
      sourcefile: `netlify-${name}.js`,
      loader: 'js',
    },
    bundle: true,
    minify: false,
    platform: 'node',
    target: 'node22',
    format: 'esm',
    resolveExtensions: ['.ts', '.js'],
    external: ['pg', 'pg-native'],
    outfile: `netlify/functions/${name}.mjs`,
    banner: { js: `// GENERATED by scripts/build.mjs from ${entry} — do not edit directly.` },
  });
}

// ─────────────────────────────────────────────────────────────────────────
//   Postcondition: every -view.ts's exported View class is in the bundle.
//
// The GuardianView incident — view committed, mount forgotten, the
// import line the only reference in the graph, esbuild correctly dropped
// the whole 395-line file, CI stayed green, prod carried a broken more-
// menu link for a day. Every check I had ran against source; none ran
// against what the bundle contained. This one does.
//
// A class name minified away would make this trivially wrong, so app.js
// is built minify: true above and the check runs against it. Class
// declarations survive minification as string references in prototype
// setup — esbuild keeps them for `.name` and error stacks. A source file
// with no `export class` in it (types, helpers, wiring) is skipped.
//
// Deliberate exception: a view a role never reaches (a dashboard only
// principals see, say) may legitimately be tree-shaken from a build
// scoped to another audience. Today every -view.ts IS reachable from
// some route, so the exception list stays empty. Add a name here when
// that changes — with the reason — so silence never means "I forgot".
// ─────────────────────────────────────────────────────────────────────────
const bundle = await readFile('apps/pwa/public/app.js', 'utf8');
const viewFiles = (await readdir('apps/pwa/src'))
  .filter((f) => f.endsWith('-view.ts'));
const VIEW_TREE_SHAKE_ALLOWED = new Set([
  // e.g. 'SomePrincipalOnlyView — only mounted for principals; no other role bundle needs it',
]);
const missing = [];
for (const file of viewFiles) {
  const src = await readFile(`apps/pwa/src/${file}`, 'utf8');
  const match = src.match(/^export class (\w+View)\b/m);
  if (!match) continue;
  const name = match[1];
  if (VIEW_TREE_SHAKE_ALLOWED.has(name)) continue;
  if (!bundle.includes(name)) missing.push({ file, name });
}
if (missing.length > 0) {
  console.error(
    `\n  ✗ ${missing.length} View class(es) are absent from apps/pwa/public/app.js:\n` +
    missing.map((m) => `      - ${m.name}   (from apps/pwa/src/${m.file})`).join('\n') +
    `\n\n    Either add a route or menu entry that instantiates each, or list it in\n` +
    `    scripts/build.mjs's VIEW_TREE_SHAKE_ALLOWED with the reason.\n`,
  );
  process.exit(1);
}

console.log(`build complete — app.js + sw.js + ${API_ENTRIES.length} API bundles written`);
