/**
 * Bundles browser-side and API-side TypeScript into self-contained files.
 *
 * Browser bundles (platform: browser):
 *   app.js  — the attendance screen and outbox (loaded as an ES module)
 *   sw.js   — the service worker (loaded as a classic script, IIFE format)
 *
 * API bundle (platform: node):
 *   api/v1/sync/push.js — Vercel's Node builder only transpiles a function's
 *   entry file; it does not resolve relative imports that reach outside the
 *   api/ directory (e.g. into services/ or packages/). Bundling the whole
 *   dependency graph ourselves, with only 'pg' left external (it ships via
 *   npm's "dependencies" and is resolved from node_modules at runtime),
 *   sidesteps that limitation entirely.
 */
import { build } from 'esbuild';

const BROWSER = {
  bundle: true,
  minify: true,
  platform: 'browser',
  // esbuild resolves .ts imports natively; no plugin needed.
  resolveExtensions: ['.ts', '.js'],
};

await build({
  ...BROWSER,
  entryPoints: ['apps/pwa/src/app.ts'],
  format: 'esm',
  outfile: 'apps/pwa/public/app.js',
  define: { 'process.env.NODE_ENV': '"production"' },
});

await build({
  ...BROWSER,
  entryPoints: ['apps/pwa/src/sw.ts'],
  // Service workers are registered as classic scripts; ES module SWs have
  // limited browser support on the Android Go devices this app targets.
  format: 'iife',
  outfile: 'apps/pwa/public/sw.js',
});

// Every Vercel Node function entry point, paired with the api/ path Vercel's
// file-based routing derives its route from. One esbuild call per entry —
// each becomes a self-contained file with the whole services/+packages/
// dependency graph inlined (see the file banner above for why).
const API_ENTRIES = [
  ['services/sync-svc/api/push.ts', 'api/v1/sync/push.js'],
  ['services/sync-svc/api/pull.ts', 'api/v1/sync/pull.js'],
  ['services/identity-svc/api/otp-request.ts', 'api/v1/auth/otp/request.js'],
  ['services/identity-svc/api/otp-verify.ts', 'api/v1/auth/otp/verify.js'],
  ['services/identity-svc/api/refresh.ts', 'api/v1/auth/refresh.js'],
  ['services/identity-svc/api/logout.ts', 'api/v1/auth/logout.js'],
  ['services/academics-svc/api/roster.ts', 'api/v1/academics/roster.js'],
  ['services/academics-svc/api/sections.ts', 'api/v1/academics/sections.js'],
  ['services/sms-svc/api/dispatch.ts', 'api/v1/sms/dispatch.js'],
  ['services/rms-svc/api/solve.ts', 'api/v1/rms/solve.js'],
  ['services/rms-svc/api/routine.ts', 'api/v1/rms/routine.js'],
  // bkash/nagad/rocket used to be three separate entries; merged into one
  // dynamic-route function — the Hobby plan caps a deployment at 12
  // Serverless Functions and this repo was at 14. See the file banner in
  // [provider].ts for the full rationale.
  ['services/finance-svc/api/webhooks/[provider].ts', 'api/v1/finance/webhooks/[provider].js'],
];

for (const [entry, outfile] of API_ENTRIES) {
  await build({
    bundle: true,
    minify: false,
    platform: 'node',
    target: 'node22',
    format: 'esm',
    resolveExtensions: ['.ts', '.js'],
    external: ['pg', 'pg-native'],
    entryPoints: [entry],
    outfile,
    banner: { js: `// GENERATED by scripts/build.mjs from ${entry} — do not edit directly.` },
  });
}

console.log(`build complete — app.js + sw.js + ${API_ENTRIES.length} API bundles written`);
