// GENERATED by scripts/build.mjs from services/sms-svc/api/dispatch.ts — do not edit directly.

// packages/server-core/src/db.ts
import pg from "pg";
function createDb(connectionString, opts = {}) {
  const pool = new pg.Pool({
    connectionString,
    max: 10,
    idleTimeoutMillis: 3e4,
    statement_timeout: 15e3,
    ...opts
  });
  async function inTx(setup, fn) {
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      await setup(client);
      const out = await fn(client);
      await client.query("COMMIT");
      return out;
    } catch (err) {
      try {
        await client.query("ROLLBACK");
      } catch {
      }
      throw err;
    } finally {
      client.release();
    }
  }
  return {
    pool,
    withTenant(ctx, fn) {
      if (!ctx.tenantId) throw new Error("tenant context required");
      return inTx(async (c) => {
        await c.query(
          `SELECT set_config('app.tenant_id', $1, true),
                  set_config('app.user_id',   $2, true),
                  set_config('app.role',      $3, true)`,
          [ctx.tenantId, ctx.userId, ctx.role]
        );
      }, fn);
    },
    withSystemRole(role, fn) {
      return inTx(async (c) => {
        await c.query(`SELECT set_config('app.role', $1, true)`, [role]);
      }, fn);
    },
    end: () => pool.end()
  };
}
async function assertRlsEnforced(db) {
  const { rows } = await db.pool.query(
    `SELECT rolname, rolbypassrls, rolsuper FROM pg_roles WHERE rolname = current_user`
  );
  const me = rows[0];
  if (!me) throw new Error("cannot resolve current_user");
  if (me.rolbypassrls || me.rolsuper) {
    throw new Error(
      `refusing to start: connected as "${me.rolname}" which has ${me.rolsuper ? "SUPERUSER" : "BYPASSRLS"} \u2014 RLS would not be enforced. Connect as the non-privileged runtime role instead.`
    );
  }
}
var _db = null;
async function sharedDb() {
  if (_db) return _db;
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL env var is not set");
  const db = createDb(url, { max: 5 });
  await assertRlsEnforced(db);
  _db = db;
  return db;
}

// packages/server-core/src/http.ts
function corsHeaders(extraHeaders = [], methods = "GET, POST, OPTIONS") {
  return {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": methods,
    "Access-Control-Allow-Headers": [
      "Content-Type",
      "Authorization",
      "X-Tenant-ID",
      "X-User-ID",
      "X-Role",
      ...extraHeaders
    ].join(", ")
  };
}
function header(req, name) {
  const v = req.headers[name.toLowerCase()];
  return Array.isArray(v) ? v[0] ?? "" : v ?? "";
}
function query(req) {
  const url = new URL(req.url ?? "/", "http://internal");
  return url.searchParams;
}
function json(res, code, body, cors) {
  const payload = JSON.stringify(body);
  res.writeHead(code, { ...cors, "Content-Type": "application/json" });
  res.end(payload);
}

// packages/server-core/src/rate-limit.ts
var perHour = (n) => n / 3600;
var RATE_LIMITS = {
  // Hammering one phone with OTPs is the attack; 3/hour per phone stops it
  // dead. The IP allowance has to clear a whole school activating at once.
  otp_request: { ip: { capacity: 240, refill: perHour(240) }, identity: { capacity: 3, refill: perHour(3) } },
  // Verification is a guessing attack against a 6-digit code. identity-svc
  // already caps attempts per challenge; this bounds the outer loop of
  // requesting a fresh challenge and guessing again.
  otp_verify: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 10, refill: perHour(10) } },
  // Refresh and logout — authenticated, cheap, but part of the auth surface.
  auth: { ip: { capacity: 600, refill: perHour(600) } },
  // The only endpoint class with real per-request cost. Per-identity is the
  // spend control until F-1310's proper token metering lands.
  ai: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 30, refill: perHour(30) } },
  // Ordinary authenticated traffic. Sized for a school, not a person: a
  // sync/push after a day offline is one request, not many.
  mutation: { ip: { capacity: 900, refill: 15 } },
  read: { ip: { capacity: 1800, refill: 30 } },
  // Machine-to-machine: MFS webhooks, cron workers, ANS dispatch. Already
  // gated by signature or service key; this is a backstop against a loop.
  service: { ip: { capacity: 3e3, refill: 50 } }
};
function clientIp(req) {
  const xff = req.headers["x-forwarded-for"];
  const first = Array.isArray(xff) ? xff[0] : xff;
  const ip = first?.split(",")[0]?.trim() || req.headers["x-real-ip"]?.trim() || req.socket?.remoteAddress || "unknown";
  return ip.slice(0, 64);
}
function buildBuckets(cls, ip, identity) {
  const policy = RATE_LIMITS[cls];
  const buckets = [];
  if (ip) {
    buckets.push({ key: `${cls}:ip:${ip}`, capacity: policy.ip.capacity, refill: policy.ip.refill });
  }
  if (policy.identity && identity) {
    buckets.push({
      key: `${cls}:id:${identity}`,
      capacity: policy.identity.capacity,
      refill: policy.identity.refill
    });
  }
  return buckets;
}
async function consumeRateLimit(cls, ip, identity) {
  const buckets = buildBuckets(cls, ip, identity);
  if (buckets.length === 0) return { allowed: true, retryAfterSec: 0 };
  try {
    const db = await sharedDb();
    const { rows } = await db.pool.query("SELECT * FROM app.rate_limit_consume($1::jsonb)", [JSON.stringify(buckets)]);
    const row = rows[0];
    if (!row) return { allowed: true, retryAfterSec: 0 };
    if (!row.allowed) {
      console.warn(`[rate-limit] refused ${cls}, bucket=${row.blocked_key}, retry=${row.retry_after_sec}s`);
    }
    return { allowed: row.allowed, retryAfterSec: row.retry_after_sec };
  } catch (err) {
    console.error("[rate-limit] check failed, allowing request:", err);
    return { allowed: true, retryAfterSec: 0 };
  }
}
async function enforceRateLimit(req, res, cors, cls, identity) {
  const verdict = await consumeRateLimit(cls, clientIp(req), identity);
  return sendIfRefused(res, cors, verdict);
}
function sendIfRefused(res, cors, verdict) {
  if (verdict.allowed) return true;
  json(
    res,
    429,
    {
      error: "rate_limited",
      message: "too many requests \u2014 please wait before trying again",
      retryAfterSec: verdict.retryAfterSec
    },
    { ...cors, "Retry-After": String(verdict.retryAfterSec) }
  );
  return false;
}

// packages/server-core/src/crypto.ts
import { randomBytes, randomInt, createHash, timingSafeEqual } from "node:crypto";
function randomOpaqueToken(bytes = 32) {
  return randomBytes(bytes).toString("base64url");
}

// services/sms-svc/src/dispatch.ts
var TEMPLATES = {
  "attendance.absent.v2": (name, day, org) => `\u0986\u09AA\u09A8\u09BE\u09B0 \u09B8\u09A8\u09CD\u09A4\u09BE\u09A8 ${name} \u0986\u099C (${day}) \u09AC\u09BF\u09A6\u09CD\u09AF\u09BE\u09B2\u09AF\u09BC\u09C7 \u0985\u09A8\u09C1\u09AA\u09B8\u09CD\u09A5\u09BF\u09A4 \u099B\u09BF\u09B2\u0964 \u2014 ${org}`,
  "attendance.late.v1": (name, day, org) => `\u0986\u09AA\u09A8\u09BE\u09B0 \u09B8\u09A8\u09CD\u09A4\u09BE\u09A8 ${name} \u0986\u099C (${day}) \u09AC\u09BF\u09A6\u09CD\u09AF\u09BE\u09B2\u09AF\u09BC\u09C7 \u09A6\u09C7\u09B0\u09BF\u09A4\u09C7 \u0989\u09AA\u09B8\u09CD\u09A5\u09BF\u09A4 \u09B9\u09AF\u09BC\u09C7\u099B\u09C7\u0964 \u2014 ${org}`
};
var NOTICE_SMS_MAX_BODY = 180;
function noticeSmsBody(title, body, org) {
  const head = title.trim();
  const rest = body.trim().replace(/\s+/g, " ");
  const room = NOTICE_SMS_MAX_BODY - head.length - org.length - 6;
  const tail = room > 20 && rest.length > 0 ? rest.length <= room ? rest : `${rest.slice(0, room - 1)}\u2026` : "";
  return tail ? `${head}: ${tail} \u2014 ${org}` : `${head} \u2014 ${org}`;
}
var SmsDispatchWorker = class {
  db;
  graceMinutes;
  enqueueBatchSize;
  dispatchBatchSize;
  now;
  constructor(db, opts = {}) {
    this.db = db;
    this.graceMinutes = opts.graceMinutes ?? 20;
    this.enqueueBatchSize = opts.enqueueBatchSize ?? 200;
    this.dispatchBatchSize = opts.dispatchBatchSize ?? 200;
    this.now = opts.now ?? Date.now;
  }
  async run(tenantId) {
    const ctx = { tenantId, userId: "", role: "system_ingest" };
    return this.db.withTenant(ctx, async (client) => {
      const budget = await this.loadTenantBudget(client, tenantId);
      const attendance = await this.enqueue(client, tenantId, budget);
      const notices = await this.enqueueNotices(client, tenantId, budget);
      const suppressed = { ...attendance.suppressed };
      for (const [k, v] of Object.entries(notices.suppressed)) {
        suppressed[k] = (suppressed[k] ?? 0) + v;
      }
      const dispatched = await this.dispatch(client, tenantId);
      return {
        tenantId,
        eventsConsidered: attendance.eventsConsidered + notices.eventsConsidered,
        smsQueued: attendance.smsQueued + notices.smsQueued,
        suppressed,
        dispatched
      };
    });
  }
  /**
   * Weekend, cap, cap already spent today, and the name the school signs its
   * messages with. Read once per run and shared by both senders.
   */
  async loadTenantBudget(client, tenantId) {
    const res = await client.query(
      `SELECT weekend_days, sms_daily_cap,
              COALESCE(NULLIF(settings->'branding'->>'shortName', ''),
                       NULLIF(settings->'branding'->>'nameBn', ''),
                       name_bn) AS org_name
         FROM tenants WHERE id = $1`,
      [tenantId]
    );
    const row = res.rows[0];
    const used = await client.query(
      `SELECT count(*) FROM sms_outbox
        WHERE tenant_id = $1 AND created_on = CURRENT_DATE AND status <> 'suppressed'`,
      [tenantId]
    );
    return {
      weekendDays: new Set(row?.weekend_days ?? [5, 6]),
      dailyCap: row?.sms_daily_cap ?? 2e3,
      capUsed: Number(used.rows[0].count),
      // Falls back to a neutral word, never to the platform's name.
      orgName: row?.org_name ?? "\u09AC\u09BF\u09A6\u09CD\u09AF\u09BE\u09B2\u09AF\u09BC"
    };
  }
  async enqueue(client, tenantId, budget) {
    const suppressed = {};
    let smsQueued = 0;
    const { weekendDays, dailyCap } = budget;
    let capUsed = budget.capUsed;
    const events = await client.query(
      `SELECT id, payload, occurred_at FROM event_outbox
        WHERE tenant_id = $1 AND event_type = 'attendance.marked.v1' AND published_at IS NULL
          AND occurred_at <= now() - ($2 || ' minutes')::interval
        ORDER BY id ASC LIMIT $3`,
      [tenantId, this.graceMinutes, this.enqueueBatchSize]
    );
    for (const ev of events.rows) {
      const payload = ev.payload;
      const reason = await this.suppressionReason(client, tenantId, payload, weekendDays, capUsed, dailyCap);
      if (reason) {
        suppressed[reason] = (suppressed[reason] ?? 0) + 1;
        await this.markAttendanceSmsState(client, tenantId, payload, "suppressed");
        await this.markPublished(client, ev.id);
        continue;
      }
      const guardians = await client.query(
        `SELECT g.guardian_id, u.phone_e164 FROM guardianships g
           JOIN users u ON u.id = g.guardian_id
          WHERE g.tenant_id = $1 AND g.student_id = $2 AND g.receives_sms = true`,
        [tenantId, payload.studentId]
      );
      if (guardians.rows.length === 0) {
        suppressed.no_guardian = (suppressed.no_guardian ?? 0) + 1;
        await this.markAttendanceSmsState(client, tenantId, payload, "suppressed");
        await this.markPublished(client, ev.id);
        continue;
      }
      const studentRes = await client.query(
        `SELECT full_name_bn, full_name_en FROM users WHERE id = $1`,
        [payload.studentId]
      );
      const studentName = studentRes.rows[0]?.full_name_bn ?? studentRes.rows[0]?.full_name_en ?? "\u09B6\u09BF\u0995\u09CD\u09B7\u09BE\u09B0\u09CD\u09A5\u09C0";
      const templateCode = payload.status === "late" ? "attendance.late.v1" : "attendance.absent.v2";
      const body = TEMPLATES[templateCode](studentName, payload.takenOn, budget.orgName);
      const segments = Math.max(1, Math.ceil(body.length / 70));
      let anyQueued = false;
      for (const g of guardians.rows) {
        if (!g.phone_e164 || capUsed >= dailyCap) continue;
        const dedupeKey = `${payload.status}:${payload.takenOn}:${payload.studentId}:${g.guardian_id}`;
        const inserted = await client.query(
          `INSERT INTO sms_outbox
             (tenant_id, recipient_id, msisdn, template_code, locale, body, encoding, segments, dedupe_key, context)
           VALUES ($1, $2, $3, $4, 'bn', $5, 'unicode', $6, $7, $8)
           ON CONFLICT (tenant_id, created_on, dedupe_key) DO NOTHING
           RETURNING id`,
          [
            tenantId,
            g.guardian_id,
            g.phone_e164,
            templateCode,
            body,
            segments,
            dedupeKey,
            JSON.stringify({ studentId: payload.studentId, sectionId: payload.sectionId, sessionId: payload.sessionId })
          ]
        );
        if (inserted.rowCount && inserted.rowCount > 0) {
          smsQueued++;
          capUsed++;
          anyQueued = true;
        }
      }
      await this.markAttendanceSmsState(client, tenantId, payload, anyQueued ? "queued" : "suppressed");
      if (!anyQueued) suppressed.daily_cap_exceeded = (suppressed.daily_cap_exceeded ?? 0) + 1;
      await this.markPublished(client, ev.id);
    }
    budget.capUsed = capUsed;
    return { eventsConsidered: events.rows.length, smsQueued, suppressed };
  }
  /**
   * Stage 1, second consumer: notice.published.v1 (R-2).
   *
   * Deliberately the SAME stage as attendance rather than a second pipeline.
   * SMS is roughly 80% of the infrastructure bill (docs/05 §5), and a second
   * path would be a second place for the daily cap to be miscounted, the
   * weekend to be forgotten, and a parent to be texted twice.
   *
   * What differs from attendance: there is no grace window (a notice is
   * published deliberately, not accumulated), and the recipients come from
   * notice_receipts — already resolved and frozen at publish time — rather
   * than from a live guardianship lookup.
   */
  async enqueueNotices(client, tenantId, budget) {
    const suppressed = {};
    let smsQueued = 0;
    let capUsed = budget.capUsed;
    const events = await client.query(
      `SELECT id, payload FROM event_outbox
        WHERE tenant_id = $1 AND event_type = 'notice.published.v1' AND published_at IS NULL
        ORDER BY id ASC LIMIT $2`,
      [tenantId, this.enqueueBatchSize]
    );
    for (const ev of events.rows) {
      const noticeId = ev.payload?.noticeId;
      if (!noticeId) {
        await this.markPublished(client, ev.id);
        continue;
      }
      const noticeRes = await client.query(
        `SELECT title, body, category, send_sms FROM notices WHERE id = $1`,
        [noticeId]
      );
      const notice = noticeRes.rows[0];
      if (!notice || !notice.send_sms) {
        await this.markPublished(client, ev.id);
        continue;
      }
      if (notice.category !== "emergency") {
        const today = new Date(this.now()).toISOString().slice(0, 10);
        const dow = (/* @__PURE__ */ new Date(`${today}T00:00:00Z`)).getUTCDay();
        if (budget.weekendDays.has(dow)) {
          suppressed.weekend = (suppressed.weekend ?? 0) + 1;
          await this.markPublished(client, ev.id);
          continue;
        }
        const holiday = await client.query(
          `SELECT 1 FROM calendar_days WHERE tenant_id = $1 AND day = $2 AND kind = 'holiday' LIMIT 1`,
          [tenantId, today]
        );
        if ((holiday.rowCount ?? 0) > 0) {
          suppressed.holiday = (suppressed.holiday ?? 0) + 1;
          await this.markPublished(client, ev.id);
          continue;
        }
      }
      const recipients = await client.query(
        `SELECT DISTINCT r.user_id, u.phone_e164
           FROM notice_receipts r
           JOIN users u ON u.id = r.user_id
          WHERE r.tenant_id = $1 AND r.notice_id = $2
            AND u.status = 'active' AND u.phone_e164 IS NOT NULL
            AND (NOT EXISTS (SELECT 1 FROM guardianships g
                              WHERE g.tenant_id = $1 AND g.guardian_id = u.id)
                 OR EXISTS (SELECT 1 FROM guardianships g
                             WHERE g.tenant_id = $1 AND g.guardian_id = u.id
                               AND g.receives_sms = true))`,
        [tenantId, noticeId]
      );
      const body = noticeSmsBody(notice.title, notice.body, budget.orgName);
      const segments = Math.max(1, Math.ceil(body.length / 70));
      for (const r of recipients.rows) {
        if (!r.phone_e164) continue;
        if (capUsed >= budget.dailyCap) {
          suppressed.daily_cap_exceeded = (suppressed.daily_cap_exceeded ?? 0) + 1;
          continue;
        }
        const inserted = await client.query(
          `INSERT INTO sms_outbox
             (tenant_id, recipient_id, msisdn, template_code, locale, body, encoding, segments, dedupe_key, context)
           VALUES ($1, $2, $3, 'notice.published.v1', 'bn', $4, 'unicode', $5, $6, $7)
           ON CONFLICT (tenant_id, created_on, dedupe_key) DO NOTHING
           RETURNING id`,
          [
            tenantId,
            r.user_id,
            r.phone_e164,
            body,
            segments,
            `notice:${noticeId}:${r.user_id}`,
            JSON.stringify({ noticeId, category: notice.category })
          ]
        );
        if (inserted.rowCount && inserted.rowCount > 0) {
          smsQueued++;
          capUsed++;
        }
      }
      await this.markPublished(client, ev.id);
    }
    budget.capUsed = capUsed;
    return { eventsConsidered: events.rows.length, smsQueued, suppressed };
  }
  async suppressionReason(client, tenantId, payload, weekendDays, capUsed, dailyCap) {
    if (capUsed >= dailyCap) return "daily_cap_exceeded";
    const dow = (/* @__PURE__ */ new Date(`${payload.takenOn}T00:00:00Z`)).getUTCDay();
    if (weekendDays.has(dow)) return "weekend";
    const holiday = await client.query(
      `SELECT 1 FROM calendar_days WHERE tenant_id = $1 AND day = $2 AND kind = 'holiday' LIMIT 1`,
      [tenantId, payload.takenOn]
    );
    if ((holiday.rowCount ?? 0) > 0) return "holiday";
    return null;
  }
  async markAttendanceSmsState(client, tenantId, payload, state) {
    await client.query(
      `UPDATE attendance_records SET sms_state = $5
        WHERE tenant_id = $1 AND taken_on = $2 AND session_id = $3 AND student_id = $4`,
      [tenantId, payload.takenOn, payload.sessionId, payload.studentId, state]
    );
  }
  async markPublished(client, eventId) {
    await client.query(`UPDATE event_outbox SET published_at = now() WHERE id = $1`, [eventId]);
  }
  async dispatch(client, tenantId) {
    const queued = await client.query(
      `SELECT id, created_on, msisdn, body FROM sms_outbox
        WHERE tenant_id = $1 AND status = 'queued'
        ORDER BY priority, queued_at LIMIT $2`,
      [tenantId, this.dispatchBatchSize]
    );
    let dispatched = 0;
    for (const row of queued.rows) {
      const providerMsgId = await this.sendStub(row.msisdn, row.body);
      await client.query(
        `UPDATE sms_outbox
            SET status = 'sent', sent_at = now(), provider = 'stub',
                provider_msg_id = $4, attempts = attempts + 1
          WHERE tenant_id = $1 AND created_on = $2 AND id = $3`,
        [tenantId, row.created_on, row.id, providerMsgId]
      );
      dispatched++;
    }
    return dispatched;
  }
  /** Stand-in for a real SMS aggregator call — no credentials exist yet. */
  async sendStub(msisdn, body) {
    const providerMsgId = `stub_${randomOpaqueToken(8)}`;
    console.log(`[sms-dispatch] STUB SEND to=${msisdn} id=${providerMsgId} body=${JSON.stringify(body)}`);
    return providerMsgId;
  }
};

// services/sms-svc/api/dispatch.ts
var UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
async function handler(req, res) {
  const cors = corsHeaders([], "GET, POST, OPTIONS");
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "GET" && req.method !== "POST") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  if (!await enforceRateLimit(req, res, cors, "service")) return;
  const authHeader = header(req, "authorization");
  const token = authHeader.startsWith("Bearer ") ? authHeader.slice(7) : "";
  const validTokens = [process.env.SERVICE_API_KEY, process.env.CRON_SECRET].filter(Boolean);
  if (validTokens.length === 0 || !validTokens.includes(token)) {
    json(res, 401, { error: "unauthorized" }, cors);
    return;
  }
  const requestedTenantId = query(req).get("tenantId") ?? "";
  let tenantIds;
  if (requestedTenantId) {
    if (!UUID_RE.test(requestedTenantId)) {
      json(res, 400, { error: "invalid_tenant_id" }, cors);
      return;
    }
    tenantIds = [requestedTenantId];
  } else {
    tenantIds = (process.env.SMS_WORKER_TENANT_IDS ?? "").split(",").map((s) => s.trim()).filter(Boolean);
    if (tenantIds.length === 0) {
      json(res, 200, { ok: true, results: [], note: "no tenantId given and SMS_WORKER_TENANT_IDS is empty" }, cors);
      return;
    }
  }
  try {
    const db = await sharedDb();
    const worker = new SmsDispatchWorker(db);
    const results = [];
    for (const tenantId of tenantIds) {
      try {
        results.push(await worker.run(tenantId));
      } catch (err) {
        console.error(`[sms-dispatch] tenant ${tenantId} failed`, err);
        results.push({ tenantId, error: err instanceof Error ? err.message : "unknown_error" });
      }
    }
    json(res, 200, { ok: true, results }, cors);
  } catch (err) {
    console.error("[sms-dispatch] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}
export {
  handler as default
};
