// GENERATED by scripts/build.mjs from services/sms-svc/api/dispatch.ts — do not edit directly.

// packages/server-core/src/db.ts
import pg from "pg";
function createDb(connectionString, opts = {}) {
  const pool = new pg.Pool({
    connectionString,
    max: 10,
    idleTimeoutMillis: 3e4,
    statement_timeout: 15e3,
    ...opts
  });
  async function inTx(setup, fn) {
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      await setup(client);
      const out = await fn(client);
      await client.query("COMMIT");
      return out;
    } catch (err) {
      try {
        await client.query("ROLLBACK");
      } catch {
      }
      throw err;
    } finally {
      client.release();
    }
  }
  return {
    pool,
    withTenant(ctx, fn) {
      if (!ctx.tenantId) throw new Error("tenant context required");
      return inTx(async (c) => {
        await c.query(
          `SELECT set_config('app.tenant_id', $1, true),
                  set_config('app.user_id',   $2, true),
                  set_config('app.role',      $3, true)`,
          [ctx.tenantId, ctx.userId, ctx.role]
        );
      }, fn);
    },
    withSystemRole(role, fn) {
      return inTx(async (c) => {
        await c.query(`SELECT set_config('app.role', $1, true)`, [role]);
      }, fn);
    },
    end: () => pool.end()
  };
}
async function assertRlsEnforced(db) {
  const { rows } = await db.pool.query(
    `SELECT rolname, rolbypassrls, rolsuper FROM pg_roles WHERE rolname = current_user`
  );
  const me = rows[0];
  if (!me) throw new Error("cannot resolve current_user");
  if (me.rolbypassrls || me.rolsuper) {
    throw new Error(
      `refusing to start: connected as "${me.rolname}" which has ${me.rolsuper ? "SUPERUSER" : "BYPASSRLS"} \u2014 RLS would not be enforced. Connect as the non-privileged runtime role instead.`
    );
  }
}
var _db = null;
async function sharedDb() {
  if (_db) return _db;
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL env var is not set");
  const db = createDb(url, { max: 5 });
  await assertRlsEnforced(db);
  _db = db;
  return db;
}

// packages/server-core/src/http.ts
function allowedOrigins(env = process.env) {
  return (env.ALLOWED_ORIGINS ?? "").split(",").map((o) => o.trim()).filter((o) => o.length > 0);
}
function corsOriginFor(requestOrigin, env = process.env) {
  const allow = allowedOrigins(env);
  if (allow.length === 0) return { origin: "*", vary: false };
  if (requestOrigin && allow.includes(requestOrigin)) {
    return { origin: requestOrigin, vary: true };
  }
  return { origin: allow[0], vary: true };
}
function corsHeaders(extraHeaders = [], methods = "GET, POST, OPTIONS", requestOrigin) {
  const { origin, vary } = corsOriginFor(requestOrigin);
  return {
    ...vary ? { Vary: "Origin" } : {},
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": methods,
    "Access-Control-Allow-Headers": [
      "Content-Type",
      "Authorization",
      "X-Tenant-ID",
      "X-User-ID",
      "X-Role",
      ...extraHeaders
    ].join(", ")
  };
}
function header(req, name) {
  const v = req.headers[name.toLowerCase()];
  return Array.isArray(v) ? v[0] ?? "" : v ?? "";
}
function query(req) {
  const url = new URL(req.url ?? "/", "http://internal");
  return url.searchParams;
}
function json(res, code, body, cors) {
  const payload = JSON.stringify(body);
  res.writeHead(code, { ...cors, "Content-Type": "application/json" });
  res.end(payload);
}

// packages/server-core/src/rate-limit.ts
var perHour = (n) => n / 3600;
var RATE_LIMITS = {
  // Hammering one phone with OTPs is the attack; 3/hour per phone stops it
  // dead. The IP allowance has to clear a whole school activating at once.
  otp_request: { ip: { capacity: 240, refill: perHour(240) }, identity: { capacity: 3, refill: perHour(3) } },
  // Verification is a guessing attack against a 6-digit code. identity-svc
  // already caps attempts per challenge; this bounds the outer loop of
  // requesting a fresh challenge and guessing again.
  otp_verify: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 10, refill: perHour(10) } },
  // Refresh and logout — authenticated, cheap, but part of the auth surface.
  auth: { ip: { capacity: 600, refill: perHour(600) } },
  // The only endpoint class with real per-request cost. Per-identity is the
  // spend control until F-1310's proper token metering lands.
  ai: { ip: { capacity: 600, refill: perHour(600) }, identity: { capacity: 30, refill: perHour(30) } },
  // Ordinary authenticated traffic. Sized for a school, not a person: a
  // sync/push after a day offline is one request, not many.
  mutation: { ip: { capacity: 900, refill: 15 } },
  read: { ip: { capacity: 1800, refill: 30 } },
  // Machine-to-machine: MFS webhooks, cron workers, ANS dispatch. Already
  // gated by signature or service key; this is a backstop against a loop.
  service: { ip: { capacity: 3e3, refill: 50 } }
};
function clientIp(req) {
  const xff = req.headers["x-forwarded-for"];
  const first = Array.isArray(xff) ? xff[0] : xff;
  const ip = first?.split(",")[0]?.trim() || req.headers["x-real-ip"]?.trim() || req.socket?.remoteAddress || "unknown";
  return ip.slice(0, 64);
}
function buildBuckets(cls, ip, identity) {
  const policy = RATE_LIMITS[cls];
  const buckets = [];
  if (ip) {
    buckets.push({ key: `${cls}:ip:${ip}`, capacity: policy.ip.capacity, refill: policy.ip.refill });
  }
  if (policy.identity && identity) {
    buckets.push({
      key: `${cls}:id:${identity}`,
      capacity: policy.identity.capacity,
      refill: policy.identity.refill
    });
  }
  return buckets;
}
async function consumeRateLimit(cls, ip, identity) {
  const buckets = buildBuckets(cls, ip, identity);
  if (buckets.length === 0) return { allowed: true, retryAfterSec: 0 };
  try {
    const db = await sharedDb();
    const { rows } = await db.pool.query("SELECT * FROM app.rate_limit_consume($1::jsonb)", [JSON.stringify(buckets)]);
    const row = rows[0];
    if (!row) return { allowed: true, retryAfterSec: 0 };
    if (!row.allowed) {
      console.warn(`[rate-limit] refused ${cls}, bucket=${row.blocked_key}, retry=${row.retry_after_sec}s`);
    }
    return { allowed: row.allowed, retryAfterSec: row.retry_after_sec };
  } catch (err) {
    console.error("[rate-limit] check failed, allowing request:", err);
    return { allowed: true, retryAfterSec: 0 };
  }
}
async function enforceRateLimit(req, res, cors, cls, identity) {
  const verdict = await consumeRateLimit(cls, clientIp(req), identity);
  return sendIfRefused(res, cors, verdict);
}
function sendIfRefused(res, cors, verdict) {
  if (verdict.allowed) return true;
  json(
    res,
    429,
    {
      error: "rate_limited",
      message: "too many requests \u2014 please wait before trying again",
      retryAfterSec: verdict.retryAfterSec
    },
    { ...cors, "Retry-After": String(verdict.retryAfterSec) }
  );
  return false;
}

// packages/server-core/src/service-auth.ts
import { createHash, timingSafeEqual } from "node:crypto";
function keyFingerprint(key) {
  return createHash("sha256").update(key, "utf8").digest("hex").slice(0, 8);
}
function sameSecret(a, b) {
  if (!a || !b) return false;
  const ha = createHash("sha256").update(a, "utf8").digest();
  const hb = createHash("sha256").update(b, "utf8").digest();
  return timingSafeEqual(ha, hb);
}
function matchServiceKey(token, env = process.env, opts = {}) {
  if (!token) return null;
  if (env.SERVICE_API_KEY && sameSecret(token, env.SERVICE_API_KEY)) return "current";
  if (env.SERVICE_API_KEY_NEXT && sameSecret(token, env.SERVICE_API_KEY_NEXT)) return "next";
  if (opts.allowCron && env.CRON_SECRET && sameSecret(token, env.CRON_SECRET)) return "cron";
  return null;
}
function looksLikeBrowser(req) {
  for (const name of ["origin", "cookie", "sec-fetch-site"]) {
    const v = req.headers[name];
    if (typeof v === "string" ? v.length > 0 : Array.isArray(v) && v.length > 0) return name;
  }
  return null;
}
function logServiceKeyEvent(fields) {
  console.warn(JSON.stringify({ at: "service-auth", ...fields }));
}

// services/sms-svc/src/provider.ts
var StubProvider = class {
  name = "stub";
  live = false;
  async send(msisdn, body, csmsId) {
    const providerMsgId = `stub_${csmsId}`;
    console.log(`[sms-dispatch] STUB SEND to=${msisdn} id=${providerMsgId} body=${JSON.stringify(body)}`);
    return { providerMsgId, provider: "stub", costBdt: null };
  }
};
var SslWirelessProvider = class {
  name = "ssl_wireless";
  live = true;
  endpoint;
  token;
  sid;
  constructor(o) {
    this.endpoint = o.endpoint;
    this.token = o.token;
    this.sid = o.sid;
  }
  async send(msisdn, body, csmsId) {
    const res = await fetch(this.endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        api_token: this.token,
        sid: this.sid,
        msisdn: msisdn.replace(/^\+/, ""),
        sms: body,
        csms_id: csmsId
      }),
      // A school's cron must not hang on an aggregator having a bad night.
      // The row stays 'queued' and the next run retries it.
      signal: AbortSignal.timeout(15e3)
    });
    if (!res.ok) {
      throw new Error(`ssl_wireless HTTP ${res.status}`);
    }
    const payload = await res.json().catch(() => ({}));
    if (payload.status && payload.status.toUpperCase() !== "SUCCESS") {
      throw new Error(`ssl_wireless ${payload.status}: ${payload.error_message ?? "no detail"}`);
    }
    const reference = payload.smsinfo?.[0]?.reference_id;
    return {
      providerMsgId: reference ?? csmsId,
      provider: this.name,
      // Not reported per-message by this API; billing is reconciled from the
      // provider's own statement. NULL rather than a guess.
      costBdt: null
    };
  }
};
function resolveProvider(env = process.env) {
  const name = (env.SMS_PROVIDER ?? "").trim().toLowerCase();
  if (!name || name === "stub") return new StubProvider();
  if (name === "ssl_wireless") {
    const token = env.SMS_API_TOKEN ?? "";
    const sid = env.SMS_SENDER_ID ?? "";
    const endpoint = env.SMS_ENDPOINT ?? "";
    const missing = [
      !endpoint && "SMS_ENDPOINT",
      !token && "SMS_API_TOKEN",
      !sid && "SMS_SENDER_ID"
    ].filter(Boolean);
    if (missing.length > 0) {
      throw new Error(
        `SMS_PROVIDER=ssl_wireless but ${missing.join(", ")} ${missing.length === 1 ? "is" : "are"} not set`
      );
    }
    return new SslWirelessProvider({ endpoint, token, sid });
  }
  throw new Error(`unknown SMS_PROVIDER "${name}" \u2014 expected 'stub' or 'ssl_wireless'`);
}

// packages/server-core/src/web-push.ts
import {
  createECDH,
  createCipheriv,
  hkdfSync,
  randomBytes,
  createHash as createHash2,
  createPrivateKey,
  createPublicKey,
  sign as signSync
} from "node:crypto";
function b64url(buf) {
  return buf.toString("base64").replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
function unb64url(s) {
  return Buffer.from(s.replace(/-/g, "+").replace(/_/g, "/"), "base64");
}
function encryptPayload(payload, keys, opts = {}) {
  const plaintext = Buffer.isBuffer(payload) ? payload : Buffer.from(payload, "utf8");
  const clientPublic = unb64url(keys.p256dh);
  const authSecret = unb64url(keys.auth);
  if (clientPublic.length !== 65 || clientPublic[0] !== 4) {
    throw new Error("p256dh must be a 65-byte uncompressed P-256 point");
  }
  if (authSecret.length !== 16) {
    throw new Error("auth secret must be 16 bytes");
  }
  const salt = opts.salt ?? randomBytes(16);
  const ecdh = createECDH("prime256v1");
  if (opts.senderPrivateKey) ecdh.setPrivateKey(opts.senderPrivateKey);
  else ecdh.generateKeys();
  const senderPublic = ecdh.getPublicKey();
  const sharedSecret = ecdh.computeSecret(clientPublic);
  const prkInfo = Buffer.concat([
    Buffer.from("WebPush: info\0", "utf8"),
    clientPublic,
    senderPublic
  ]);
  const ikm = Buffer.from(hkdfSync("sha256", sharedSecret, authSecret, prkInfo, 32));
  const cek = Buffer.from(hkdfSync(
    "sha256",
    ikm,
    salt,
    Buffer.from("Content-Encoding: aes128gcm\0", "utf8"),
    16
  ));
  const nonce = Buffer.from(hkdfSync(
    "sha256",
    ikm,
    salt,
    Buffer.from("Content-Encoding: nonce\0", "utf8"),
    12
  ));
  const padded = Buffer.concat([plaintext, Buffer.from([2])]);
  const cipher = createCipheriv("aes-128-gcm", cek, nonce);
  const ciphertext = Buffer.concat([cipher.update(padded), cipher.final(), cipher.getAuthTag()]);
  const header2 = Buffer.alloc(21);
  salt.copy(header2, 0);
  header2.writeUInt32BE(4096, 16);
  header2.writeUInt8(senderPublic.length, 20);
  return Buffer.concat([header2, senderPublic, ciphertext]);
}
function privateKeyObject(rawPrivate) {
  if (rawPrivate.length !== 32) throw new Error("VAPID private key must be 32 bytes");
  const pkcs8 = Buffer.concat([
    Buffer.from("308141020100301306072a8648ce3d020106082a8648ce3d030107042730250201010420", "hex"),
    rawPrivate
  ]);
  return createPrivateKey({ key: pkcs8, format: "der", type: "pkcs8" });
}
function vapidHeader(endpoint, keys, opts = {}) {
  const aud = new URL(endpoint).origin;
  const now = opts.nowSeconds ?? Math.floor(Date.now() / 1e3);
  const exp = now + (opts.ttlSeconds ?? 12 * 60 * 60);
  const header2 = b64url(Buffer.from(JSON.stringify({ typ: "JWT", alg: "ES256" })));
  const claims = { aud, exp, sub: opts.subject ?? "mailto:ops@shikhonbd.com" };
  const body = b64url(Buffer.from(JSON.stringify(claims)));
  const signingInput = `${header2}.${body}`;
  const signature = signSync("sha256", Buffer.from(signingInput, "utf8"), {
    key: privateKeyObject(unb64url(keys.privateKey)),
    dsaEncoding: "ieee-p1363"
  });
  return `vapid t=${signingInput}.${b64url(signature)}, k=${keys.publicKey}`;
}
function vapidFromEnv(env = process.env) {
  const publicKey = (env.VAPID_PUBLIC_KEY ?? "").trim();
  const privateKey = (env.VAPID_PRIVATE_KEY ?? "").trim();
  if (!publicKey || !privateKey) return null;
  if (unb64url(publicKey).length !== 65) {
    throw new Error("VAPID_PUBLIC_KEY must be a 65-byte uncompressed P-256 point");
  }
  if (unb64url(privateKey).length !== 32) {
    throw new Error("VAPID_PRIVATE_KEY must be a 32-byte P-256 scalar");
  }
  return { publicKey, privateKey };
}
var MAX_PAYLOAD_BYTES = 3800;
async function sendPush(target, payload, keys, opts = {}) {
  const bytes = Buffer.byteLength(payload, "utf8");
  if (bytes > MAX_PAYLOAD_BYTES) {
    return {
      ok: false,
      gone: false,
      status: 0,
      error: `payload ${bytes}B exceeds ${MAX_PAYLOAD_BYTES}B`
    };
  }
  let body;
  try {
    body = encryptPayload(payload, target);
  } catch (err) {
    return { ok: false, gone: false, status: 0, error: err.message };
  }
  const doFetch = opts.fetchImpl ?? fetch;
  try {
    const res = await doFetch(target.endpoint, {
      method: "POST",
      headers: {
        "Authorization": vapidHeader(target.endpoint, keys, { subject: opts.subject }),
        "Content-Encoding": "aes128gcm",
        "Content-Type": "application/octet-stream",
        // A notice is worth delivering late; 12 hours lets a phone that is off
        // overnight still get it. Longer would deliver yesterday's news.
        "TTL": String(opts.ttlSeconds ?? 12 * 60 * 60),
        "Urgency": opts.urgency ?? "normal"
      },
      body
    });
    if (res.status === 404 || res.status === 410) {
      return { ok: false, gone: true, status: res.status };
    }
    if (res.status >= 200 && res.status < 300) {
      return { ok: true, status: res.status };
    }
    return {
      ok: false,
      gone: false,
      status: res.status,
      error: `push service returned ${res.status}`
    };
  } catch (err) {
    return { ok: false, gone: false, status: 0, error: err.message };
  }
}
function endpointFingerprint(endpoint) {
  return createHash2("sha256").update(endpoint).digest("hex").slice(0, 12);
}

// services/sms-svc/src/push-send.ts
var EMPTY_PUSH_RESULT = {
  attempted: 0,
  accepted: 0,
  smsSuppressed: 0,
  pruned: 0,
  couldHaveSuppressed: 0
};
function pushReplacesSms(settings) {
  if (!settings || typeof settings !== "object") return false;
  const push = settings.push;
  if (!push || typeof push !== "object") return false;
  return push.replacesSms === true;
}
function pushPayloadFor(smsBody, orgName, url, tag) {
  const signature = ` \u2014 ${orgName}`;
  const body = smsBody.endsWith(signature) ? smsBody.slice(0, -signature.length) : smsBody;
  return JSON.stringify({ title: orgName, body, url, tag });
}
var PushSender = class {
  vapid;
  fetchImpl;
  maxDevices;
  constructor(vapid, opts = {}) {
    this.vapid = vapid;
    this.fetchImpl = opts.fetchImpl;
    this.maxDevices = opts.maxDevices ?? 500;
  }
  async run(client, tenantId, opts) {
    const result = { ...EMPTY_PUSH_RESULT };
    const { rows: queued } = await client.query(
      `SELECT o.id, o.created_on, o.recipient_id, o.body, o.dedupe_key,
              o.template_code,
              o.context->>'category'  AS category,
              o.context->>'noticeId'  AS notice_id
         FROM sms_outbox o
        WHERE o.tenant_id = $1
          AND o.status = 'queued'
          AND o.recipient_id IS NOT NULL
          AND o.template_code NOT LIKE 'auth.%'
          AND EXISTS (SELECT 1 FROM push_subscriptions s
                       WHERE s.tenant_id = o.tenant_id
                         AND s.user_id = o.recipient_id)
        ORDER BY o.priority, o.queued_at
        LIMIT $2`,
      [tenantId, this.maxDevices]
    );
    if (queued.length === 0) return result;
    const recipientIds = [...new Set(queued.map((q) => q.recipient_id))];
    const { rows: devices } = await client.query(
      `SELECT id, user_id, endpoint, p256dh, auth
         FROM push_subscriptions
        WHERE tenant_id = $1 AND user_id = ANY($2::uuid[])`,
      [tenantId, recipientIds]
    );
    const byUser = /* @__PURE__ */ new Map();
    for (const d of devices) {
      const list = byUser.get(d.user_id);
      if (list) list.push(d);
      else byUser.set(d.user_id, [d]);
    }
    const gone = [];
    const succeeded = [];
    for (const msg of queued) {
      const targets = byUser.get(msg.recipient_id) ?? [];
      if (targets.length === 0) continue;
      result.attempted += 1;
      const url = msg.notice_id ? "#/inbox" : "#/home";
      const payload = pushPayloadFor(msg.body, opts.orgName, url, msg.dedupe_key);
      let anyAccepted = false;
      for (const t of targets) {
        const target = {
          endpoint: t.endpoint,
          p256dh: t.p256dh,
          auth: t.auth
        };
        const outcome = await sendPush(target, payload, this.vapid, {
          fetchImpl: this.fetchImpl,
          // An absence notice matters this morning, not this evening, but it
          // is still worth delivering to a phone that was off for an hour.
          urgency: msg.category === "emergency" ? "high" : "normal"
        });
        if (outcome.ok) {
          anyAccepted = true;
          result.accepted += 1;
          succeeded.push(t.id);
        } else if (outcome.gone) {
          gone.push(t.id);
        } else {
          console.warn(
            "[push] %s failed: %s",
            endpointFingerprint(t.endpoint),
            outcome.error
          );
        }
      }
      if (!anyAccepted) continue;
      const suppressible = msg.category !== "emergency";
      if (!suppressible) continue;
      if (!opts.replacesSms) {
        result.couldHaveSuppressed += 1;
        continue;
      }
      const { rowCount } = await client.query(
        `UPDATE sms_outbox
            SET status = 'suppressed', error_code = 'delivered_by_push'
          WHERE tenant_id = $1 AND created_on = $2 AND id = $3
            AND status = 'queued'`,
        [tenantId, msg.created_on, msg.id]
      );
      if (rowCount) result.smsSuppressed += 1;
    }
    if (succeeded.length > 0) {
      await client.query(
        `UPDATE push_subscriptions
            SET last_success_at = now(), failure_count = 0
          WHERE tenant_id = $1 AND id = ANY($2::uuid[])`,
        [tenantId, succeeded]
      );
    }
    if (gone.length > 0) {
      const { rowCount } = await client.query(
        `DELETE FROM push_subscriptions WHERE tenant_id = $1 AND id = ANY($2::uuid[])`,
        [tenantId, gone]
      );
      result.pruned = rowCount ?? 0;
    }
    return result;
  }
};

// packages/server-core/src/go-live.ts
function smsTestRecipients(env = process.env) {
  return (env.SMS_TEST_RECIPIENTS ?? "").split(",").map((n) => n.trim()).filter((n) => n.length > 0);
}

// services/sms-svc/src/dispatch.ts
function nonWorkingReasonFor(isoDay, weekendDays, overrides) {
  if (overrides.has("holiday")) return "holiday";
  const dow = (/* @__PURE__ */ new Date(`${isoDay}T00:00:00Z`)).getUTCDay();
  if (!weekendDays.has(dow)) return null;
  if (overrides.has("working_weekend")) return null;
  return "weekend";
}
var TEMPLATES = {
  "attendance.absent.v2": (name, day, org) => `\u0986\u09AA\u09A8\u09BE\u09B0 \u09B8\u09A8\u09CD\u09A4\u09BE\u09A8 ${name} \u0986\u099C (${day}) \u09AC\u09BF\u09A6\u09CD\u09AF\u09BE\u09B2\u09AF\u09BC\u09C7 \u0985\u09A8\u09C1\u09AA\u09B8\u09CD\u09A5\u09BF\u09A4 \u099B\u09BF\u09B2\u0964 \u2014 ${org}`,
  "attendance.late.v1": (name, day, org) => `\u0986\u09AA\u09A8\u09BE\u09B0 \u09B8\u09A8\u09CD\u09A4\u09BE\u09A8 ${name} \u0986\u099C (${day}) \u09AC\u09BF\u09A6\u09CD\u09AF\u09BE\u09B2\u09AF\u09BC\u09C7 \u09A6\u09C7\u09B0\u09BF\u09A4\u09C7 \u0989\u09AA\u09B8\u09CD\u09A5\u09BF\u09A4 \u09B9\u09AF\u09BC\u09C7\u099B\u09C7\u0964 \u2014 ${org}`
};
var NOTICE_SMS_DEFAULT_MAX = 180;
var NOTICE_SMS_HARD_CEILING = 480;
var NOTICE_SMS_MIN = 70;
function noticeSmsMaxChars(settings) {
  const raw = settings?.sms?.noticeMaxChars;
  let n;
  if (typeof raw === "number") n = raw;
  else if (typeof raw === "string" && raw.trim() !== "") n = Number(raw);
  else return NOTICE_SMS_DEFAULT_MAX;
  if (!Number.isFinite(n)) return NOTICE_SMS_DEFAULT_MAX;
  return Math.max(NOTICE_SMS_MIN, Math.min(NOTICE_SMS_HARD_CEILING, Math.floor(n)));
}
function noticeSmsBody(title, body, org, maxChars = NOTICE_SMS_DEFAULT_MAX) {
  const head = title.trim();
  const rest = body.trim().replace(/\s+/g, " ");
  const room = maxChars - head.length - org.length - 6;
  const tail = room > 20 && rest.length > 0 ? rest.length <= room ? rest : `${rest.slice(0, room - 1)}\u2026` : "";
  return tail ? `${head}: ${tail} \u2014 ${org}` : `${head} \u2014 ${org}`;
}
var SmsDispatchWorker = class {
  db;
  graceMinutes;
  enqueueBatchSize;
  dispatchBatchSize;
  now;
  provider;
  pushSender;
  /** R-8 §4. Non-null only when the deployment is restricted to test numbers. */
  allowlist;
  constructor(db, opts = {}) {
    this.db = db;
    this.graceMinutes = opts.graceMinutes ?? 20;
    this.enqueueBatchSize = opts.enqueueBatchSize ?? 200;
    this.dispatchBatchSize = opts.dispatchBatchSize ?? 200;
    this.now = opts.now ?? Date.now;
    this.provider = opts.provider ?? resolveProvider();
    const allow = opts.testRecipients ?? smsTestRecipients();
    this.allowlist = allow.length > 0 ? new Set(allow) : null;
    const vapid = opts.vapid ?? vapidFromEnv();
    this.pushSender = vapid ? new PushSender(vapid, { fetchImpl: opts.fetchImpl }) : null;
  }
  async run(tenantId) {
    const ctx = { tenantId, userId: "", role: "system_ingest" };
    return this.db.withTenant(ctx, async (client) => {
      const budget = await this.loadTenantBudget(client, tenantId);
      const attendance = await this.enqueue(client, tenantId, budget);
      const notices = await this.enqueueNotices(client, tenantId, budget);
      const suppressed = { ...attendance.suppressed };
      for (const [k, v] of Object.entries(notices.suppressed)) {
        suppressed[k] = (suppressed[k] ?? 0) + v;
      }
      const push = this.pushSender ? await this.pushSender.run(client, tenantId, {
        replacesSms: budget.pushReplacesSms,
        orgName: budget.orgName
      }) : { ...EMPTY_PUSH_RESULT };
      const dispatched = await this.dispatch(client, tenantId);
      return {
        tenantId,
        eventsConsidered: attendance.eventsConsidered + notices.eventsConsidered,
        smsQueued: attendance.smsQueued + notices.smsQueued,
        suppressed,
        dispatched,
        push
      };
    });
  }
  /**
   * Weekend, cap, cap already spent today, and the name the school signs its
   * messages with. Read once per run and shared by both senders.
   */
  async loadTenantBudget(client, tenantId) {
    const res = await client.query(
      `SELECT weekend_days, sms_daily_cap, settings,
              COALESCE(NULLIF(settings->'branding'->>'shortName', ''),
                       NULLIF(settings->'branding'->>'nameBn', ''),
                       name_bn) AS org_name
         FROM tenants WHERE id = $1`,
      [tenantId]
    );
    const row = res.rows[0];
    const used = await client.query(
      `SELECT count(*) FROM sms_outbox
        WHERE tenant_id = $1 AND created_on = CURRENT_DATE AND status <> 'suppressed'`,
      [tenantId]
    );
    return {
      weekendDays: new Set(row?.weekend_days ?? [5, 6]),
      dailyCap: row?.sms_daily_cap ?? 2e3,
      capUsed: Number(used.rows[0].count),
      // Falls back to a neutral word, never to the platform's name.
      orgName: row?.org_name ?? "\u09AC\u09BF\u09A6\u09CD\u09AF\u09BE\u09B2\u09AF\u09BC",
      noticeMaxChars: noticeSmsMaxChars(row?.settings),
      pushReplacesSms: pushReplacesSms(row?.settings)
    };
  }
  async enqueue(client, tenantId, budget) {
    const suppressed = {};
    let smsQueued = 0;
    const { weekendDays, dailyCap } = budget;
    let capUsed = budget.capUsed;
    const events = await client.query(
      `SELECT id, payload, occurred_at FROM event_outbox
        WHERE tenant_id = $1 AND event_type = 'attendance.marked.v1' AND published_at IS NULL
          AND occurred_at <= now() - ($2 || ' minutes')::interval
        ORDER BY id ASC LIMIT $3`,
      [tenantId, this.graceMinutes, this.enqueueBatchSize]
    );
    for (const ev of events.rows) {
      const payload = ev.payload;
      const reason = await this.suppressionReason(client, tenantId, payload, weekendDays, capUsed, dailyCap);
      if (reason) {
        suppressed[reason] = (suppressed[reason] ?? 0) + 1;
        await this.markAttendanceSmsState(client, tenantId, payload, "suppressed");
        await this.markPublished(client, ev.id);
        continue;
      }
      const guardians = await client.query(
        `SELECT g.guardian_id, u.phone_e164 FROM guardianships g
           JOIN users u ON u.id = g.guardian_id
          WHERE g.tenant_id = $1 AND g.student_id = $2 AND g.receives_sms = true`,
        [tenantId, payload.studentId]
      );
      if (guardians.rows.length === 0) {
        suppressed.no_guardian = (suppressed.no_guardian ?? 0) + 1;
        await this.markAttendanceSmsState(client, tenantId, payload, "suppressed");
        await this.markPublished(client, ev.id);
        continue;
      }
      const studentRes = await client.query(
        `SELECT full_name_bn, full_name_en FROM users WHERE id = $1`,
        [payload.studentId]
      );
      const studentName = studentRes.rows[0]?.full_name_bn ?? studentRes.rows[0]?.full_name_en ?? "\u09B6\u09BF\u0995\u09CD\u09B7\u09BE\u09B0\u09CD\u09A5\u09C0";
      const templateCode = payload.status === "late" ? "attendance.late.v1" : "attendance.absent.v2";
      const body = TEMPLATES[templateCode](studentName, payload.takenOn, budget.orgName);
      const segments = Math.max(1, Math.ceil(body.length / 70));
      let anyQueued = false;
      for (const g of guardians.rows) {
        if (!g.phone_e164 || capUsed >= dailyCap) continue;
        const dedupeKey = `${payload.status}:${payload.takenOn}:${payload.studentId}:${g.guardian_id}`;
        const inserted = await client.query(
          `INSERT INTO sms_outbox
             (tenant_id, recipient_id, msisdn, template_code, locale, body, encoding, segments, dedupe_key, context)
           VALUES ($1, $2, $3, $4, 'bn', $5, 'unicode', $6, $7, $8)
           ON CONFLICT (tenant_id, created_on, dedupe_key) DO NOTHING
           RETURNING id`,
          [
            tenantId,
            g.guardian_id,
            g.phone_e164,
            templateCode,
            body,
            segments,
            dedupeKey,
            JSON.stringify({ studentId: payload.studentId, sectionId: payload.sectionId, sessionId: payload.sessionId })
          ]
        );
        if (inserted.rowCount && inserted.rowCount > 0) {
          smsQueued++;
          capUsed++;
          anyQueued = true;
        }
      }
      await this.markAttendanceSmsState(client, tenantId, payload, anyQueued ? "queued" : "suppressed");
      if (!anyQueued) suppressed.daily_cap_exceeded = (suppressed.daily_cap_exceeded ?? 0) + 1;
      await this.markPublished(client, ev.id);
    }
    budget.capUsed = capUsed;
    return { eventsConsidered: events.rows.length, smsQueued, suppressed };
  }
  /**
   * Stage 1, second consumer: notice.published.v1 (R-2).
   *
   * Deliberately the SAME stage as attendance rather than a second pipeline.
   * SMS is roughly 80% of the infrastructure bill (docs/05 §5), and a second
   * path would be a second place for the daily cap to be miscounted, the
   * weekend to be forgotten, and a parent to be texted twice.
   *
   * What differs from attendance: there is no grace window (a notice is
   * published deliberately, not accumulated), and the recipients come from
   * notice_receipts — already resolved and frozen at publish time — rather
   * than from a live guardianship lookup.
   */
  async enqueueNotices(client, tenantId, budget) {
    const suppressed = {};
    let smsQueued = 0;
    let capUsed = budget.capUsed;
    const events = await client.query(
      `SELECT id, payload FROM event_outbox
        WHERE tenant_id = $1 AND event_type = 'notice.published.v1' AND published_at IS NULL
        ORDER BY id ASC LIMIT $2`,
      [tenantId, this.enqueueBatchSize]
    );
    for (const ev of events.rows) {
      const noticeId = ev.payload?.noticeId;
      if (!noticeId) {
        await this.markPublished(client, ev.id);
        continue;
      }
      const noticeRes = await client.query(
        `SELECT title, body, category, send_sms FROM notices WHERE id = $1`,
        [noticeId]
      );
      const notice = noticeRes.rows[0];
      if (!notice || !notice.send_sms) {
        await this.markPublished(client, ev.id);
        continue;
      }
      if (notice.category !== "emergency") {
        const today = new Date(this.now()).toISOString().slice(0, 10);
        const overrides = await this.calendarOverrides(client, tenantId, today);
        const reason = nonWorkingReasonFor(today, budget.weekendDays, overrides);
        if (reason) {
          suppressed[reason] = (suppressed[reason] ?? 0) + 1;
          await this.markPublished(client, ev.id);
          continue;
        }
      }
      const recipients = await client.query(
        `SELECT DISTINCT r.user_id, u.phone_e164
           FROM notice_receipts r
           JOIN users u ON u.id = r.user_id
          WHERE r.tenant_id = $1 AND r.notice_id = $2
            AND u.status = 'active' AND u.phone_e164 IS NOT NULL
            AND (NOT EXISTS (SELECT 1 FROM guardianships g
                              WHERE g.tenant_id = $1 AND g.guardian_id = u.id)
                 OR EXISTS (SELECT 1 FROM guardianships g
                             WHERE g.tenant_id = $1 AND g.guardian_id = u.id
                               AND g.receives_sms = true))`,
        [tenantId, noticeId]
      );
      const body = noticeSmsBody(
        notice.title,
        notice.body,
        budget.orgName,
        budget.noticeMaxChars
      );
      const segments = Math.max(1, Math.ceil(body.length / 70));
      for (const r of recipients.rows) {
        if (!r.phone_e164) continue;
        if (capUsed >= budget.dailyCap) {
          suppressed.daily_cap_exceeded = (suppressed.daily_cap_exceeded ?? 0) + 1;
          continue;
        }
        const inserted = await client.query(
          `INSERT INTO sms_outbox
             (tenant_id, recipient_id, msisdn, template_code, locale, body, encoding, segments, dedupe_key, context)
           VALUES ($1, $2, $3, 'notice.published.v1', 'bn', $4, 'unicode', $5, $6, $7)
           ON CONFLICT (tenant_id, created_on, dedupe_key) DO NOTHING
           RETURNING id`,
          [
            tenantId,
            r.user_id,
            r.phone_e164,
            body,
            segments,
            `notice:${noticeId}:${r.user_id}`,
            JSON.stringify({ noticeId, category: notice.category })
          ]
        );
        if (inserted.rowCount && inserted.rowCount > 0) {
          smsQueued++;
          capUsed++;
        }
      }
      await this.markPublished(client, ev.id);
    }
    budget.capUsed = capUsed;
    return { eventsConsidered: events.rows.length, smsQueued, suppressed };
  }
  async suppressionReason(client, tenantId, payload, weekendDays, capUsed, dailyCap) {
    if (capUsed >= dailyCap) return "daily_cap_exceeded";
    const overrides = await this.calendarOverrides(client, tenantId, payload.takenOn);
    return nonWorkingReasonFor(payload.takenOn, weekendDays, overrides);
  }
  /**
   * Which of the two day-deciding kinds apply to this date.
   *
   * One query where there used to be one query — the holiday lookup simply
   * widened its IN list, so the working-weekend rule costs no extra round
   * trip. Scoped by tenant_id in the predicate AND by RLS underneath, so an
   * override in one school cannot silence or unsilence another's.
   */
  async calendarOverrides(client, tenantId, isoDay) {
    const { rows } = await client.query(
      `SELECT DISTINCT kind FROM calendar_days
        WHERE tenant_id = $1 AND day = $2
          AND kind IN ('holiday', 'working_weekend')`,
      [tenantId, isoDay]
    );
    return new Set(rows.map((r) => r.kind));
  }
  async markAttendanceSmsState(client, tenantId, payload, state) {
    await client.query(
      `UPDATE attendance_records SET sms_state = $5
        WHERE tenant_id = $1 AND taken_on = $2 AND session_id = $3 AND student_id = $4`,
      [tenantId, payload.takenOn, payload.sessionId, payload.studentId, state]
    );
  }
  async markPublished(client, eventId) {
    await client.query(`UPDATE event_outbox SET published_at = now() WHERE id = $1`, [eventId]);
  }
  async dispatch(client, tenantId) {
    let withheld = 0;
    const queued = await client.query(
      `SELECT id, created_on, msisdn, body FROM sms_outbox
        WHERE tenant_id = $1 AND status = 'queued'
        ORDER BY priority, queued_at LIMIT $2`,
      [tenantId, this.dispatchBatchSize]
    );
    let dispatched = 0;
    for (const row of queued.rows) {
      if (this.allowlist && !this.allowlist.has(row.msisdn)) {
        await client.query(
          `UPDATE sms_outbox
              SET status = 'suppressed', error_code = 'not_in_test_allowlist'
            WHERE tenant_id = $1 AND created_on = $2 AND id = $3`,
          [tenantId, row.created_on, row.id]
        );
        withheld += 1;
        continue;
      }
      let sent;
      try {
        sent = await this.provider.send(row.msisdn, row.body, row.id);
      } catch (err) {
        await client.query(
          `UPDATE sms_outbox
              SET attempts = attempts + 1,
                  error_code = left($4, 120),
                  status = CASE WHEN attempts + 1 >= 5 THEN 'failed' ELSE 'queued' END
            WHERE tenant_id = $1 AND created_on = $2 AND id = $3`,
          [
            tenantId,
            row.created_on,
            row.id,
            err instanceof Error ? err.message : "send failed"
          ]
        );
        continue;
      }
      await client.query(
        `UPDATE sms_outbox
            SET status = 'sent', sent_at = now(), provider = $5,
                provider_msg_id = $4, attempts = attempts + 1,
                cost_bdt = COALESCE($6, cost_bdt)
          WHERE tenant_id = $1 AND created_on = $2 AND id = $3`,
        [
          tenantId,
          row.created_on,
          row.id,
          sent.providerMsgId,
          sent.provider,
          sent.costBdt ?? null
        ]
      );
      dispatched++;
    }
    if (withheld > 0) {
      console.warn(
        "[sms] %d message(s) withheld \u2014 SMS_TEST_RECIPIENTS allowlist is set",
        withheld
      );
    }
    return dispatched;
  }
};

// services/sms-svc/api/dispatch.ts
var UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
async function handler(req, res) {
  const cors = corsHeaders([], "GET, POST, OPTIONS");
  if (req.method === "OPTIONS") {
    res.writeHead(204, cors);
    res.end();
    return;
  }
  if (req.method !== "GET" && req.method !== "POST") {
    json(res, 405, { error: "method_not_allowed" }, cors);
    return;
  }
  if (!await enforceRateLimit(req, res, cors, "service")) return;
  const authHeader = header(req, "authorization");
  const token = authHeader.startsWith("Bearer ") ? authHeader.slice(7) : "";
  const keyLabel = matchServiceKey(token, process.env, { allowCron: true });
  if (!keyLabel) {
    json(res, 401, { error: "unauthorized" }, cors);
    return;
  }
  const browserHeader = looksLikeBrowser(req);
  if (browserHeader) {
    logServiceKeyEvent({
      event: "service_key_from_browser",
      endpoint: "sms/dispatch",
      fingerprint: keyFingerprint(token),
      keyLabel,
      detail: browserHeader
    });
    json(res, 403, { error: "service_key_from_browser" }, cors);
    return;
  }
  const requestedTenantId = query(req).get("tenantId") ?? "";
  let tenantIds;
  if (requestedTenantId) {
    if (!UUID_RE.test(requestedTenantId)) {
      json(res, 400, { error: "invalid_tenant_id" }, cors);
      return;
    }
    tenantIds = [requestedTenantId];
  } else {
    tenantIds = (process.env.SMS_WORKER_TENANT_IDS ?? "").split(",").map((s) => s.trim()).filter(Boolean);
    if (tenantIds.length === 0) {
      json(res, 200, { ok: true, results: [], note: "no tenantId given and SMS_WORKER_TENANT_IDS is empty" }, cors);
      return;
    }
  }
  try {
    const db = await sharedDb();
    const worker = new SmsDispatchWorker(db);
    const results = [];
    for (const tenantId of tenantIds) {
      try {
        results.push(await worker.run(tenantId));
      } catch (err) {
        console.error(`[sms-dispatch] tenant ${tenantId} failed`, err);
        results.push({ tenantId, error: err instanceof Error ? err.message : "unknown_error" });
      }
    }
    json(res, 200, { ok: true, results }, cors);
  } catch (err) {
    console.error("[sms-dispatch] unexpected error", err);
    json(res, 500, { error: "internal_error" }, cors);
  }
}
export {
  handler as default
};
