BEGIN;
DROP TRIGGER  IF EXISTS trg_enrolment_section_count ON enrolments;
DROP FUNCTION IF EXISTS app.refresh_section_count();
ALTER TABLE IF EXISTS staff_profiles DROP CONSTRAINT IF EXISTS fk_staff_department;
ALTER TABLE IF EXISTS sections       DROP CONSTRAINT IF EXISTS fk_sections_home_room;
DROP TABLE IF EXISTS enrolments                CASCADE;
DROP TABLE IF EXISTS section_subject_teachers  CASCADE;
DROP TABLE IF EXISTS teacher_subject_expertise CASCADE;
DROP TABLE IF EXISTS class_subjects            CASCADE;
DROP TABLE IF EXISTS subjects                  CASCADE;
DROP TABLE IF EXISTS rooms                     CASCADE;
DROP TABLE IF EXISTS sections                  CASCADE;
DROP TABLE IF EXISTS classes                   CASCADE;
DROP TABLE IF EXISTS departments               CASCADE;
DROP TABLE IF EXISTS calendar_days             CASCADE;
DROP TABLE IF EXISTS terms                     CASCADE;
DROP TABLE IF EXISTS academic_years            CASCADE;
DROP TYPE IF EXISTS academic_group;
COMMIT;
