BEGIN;
DROP FUNCTION IF EXISTS app.compute_exam_gpa(uuid, uuid, uuid);
DROP FUNCTION IF EXISTS app.compute_subject_grade(uuid, numeric, numeric, numeric, numeric, numeric, numeric, numeric, numeric, numeric, boolean, uuid);
DROP TRIGGER  IF EXISTS trg_marks_immutable ON exam_marks;
DROP FUNCTION IF EXISTS app.block_published_mark_update();
DROP TABLE IF EXISTS exam_results          CASCADE;
DROP TABLE IF EXISTS grading_bands         CASCADE;
DROP TABLE IF EXISTS grading_scales        CASCADE;
DROP TABLE IF EXISTS answer_scripts        CASCADE;
DROP TABLE IF EXISTS mark_corrections      CASCADE;
DROP TABLE IF EXISTS exam_marks            CASCADE;
DROP TABLE IF EXISTS exam_subjects         CASCADE;
DROP TABLE IF EXISTS exams                 CASCADE;
DROP TABLE IF EXISTS question_paper_items  CASCADE;
DROP TABLE IF EXISTS question_papers       CASCADE;
DROP TABLE IF EXISTS question_item_options CASCADE;
DROP TABLE IF EXISTS question_item_parts   CASCADE;
DROP TABLE IF EXISTS question_items        CASCADE;
DROP TYPE IF EXISTS exam_status;
DROP TYPE IF EXISTS difficulty_band;
DROP TYPE IF EXISTS item_source;
DROP TYPE IF EXISTS bloom_level;
DROP TYPE IF EXISTS question_type;
COMMIT;
