BEGIN;
ALTER TABLE IF EXISTS attendance_sessions DROP CONSTRAINT IF EXISTS fk_att_session_slot;
DROP FUNCTION IF EXISTS app.teacher_day(uuid, date);
DROP TRIGGER  IF EXISTS trg_substitute_free ON routine_substitutions;
DROP FUNCTION IF EXISTS app.check_substitute_free();
DROP TRIGGER  IF EXISTS trg_merged_section_clash ON routine_slot_sections;
DROP FUNCTION IF EXISTS app.check_merged_section_clash();
DROP TABLE IF EXISTS class_delivery_log     CASCADE;
DROP TABLE IF EXISTS routine_substitutions  CASCADE;
DROP TABLE IF EXISTS teacher_leaves         CASCADE;
DROP TABLE IF EXISTS teacher_availability   CASCADE;
DROP TABLE IF EXISTS routine_slot_sections  CASCADE;
DROP TABLE IF EXISTS routine_slots          CASCADE;
DROP TABLE IF EXISTS routines               CASCADE;
DROP TABLE IF EXISTS period_definitions     CASCADE;
DROP TABLE IF EXISTS period_templates       CASCADE;
DROP FUNCTION IF EXISTS app.sync_slot_time_range();
DROP TYPE IF EXISTS substitution_action;
DROP TYPE IF EXISTS slot_kind;
DROP TYPE IF EXISTS leave_status;
DROP TYPE IF EXISTS routine_status;
DROP TYPE IF EXISTS period_kind;
DROP TYPE IF EXISTS timerange;
COMMIT;
